const IMG = '../stock/media/16-9 Aspect Ratio(image).png';
const IMG45 = '../stock/media/4-5 Aspect Ratio(image).png';

const tilt = (sel, amt = 18) => `const el=document.querySelector('${sel}');el.onmousemove=e=>{const r=el.getBoundingClientRect();const x=(e.clientX-r.left)/r.width-.5;const y=(e.clientY-r.top)/r.height-.5;el.style.transform='rotateY('+(x*${amt})+'deg) rotateX('+(-y*${amt})+'deg)';};el.onmouseleave=()=>el.style.transform='';`;

module.exports = [
  // ── 3D cubes & objects ──
  { slug: '3d-cube-auto-spin', title: 'Auto Spin 3D Cube', category: '3d-effects', tags: ['3d', 'cube', 'spin'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#0a0a0c;perspective:800px}.scene{transform-style:preserve-3d;animation:spin 8s linear infinite}@keyframes spin{to{transform:rotateX(-18deg) rotateY(360deg)}}.cube{position:relative;width:120px;height:120px;transform-style:preserve-3d}.face{position:absolute;width:120px;height:120px;border:2px solid rgba(255,255,255,.15);display:grid;place-items:center;font-weight:800;font-size:1.1rem;color:#fff;backface-visibility:hidden}.f-front{background:#6c8cff;transform:translateZ(60px)}.f-back{background:#764ba2;transform:rotateY(180deg) translateZ(60px)}.f-right{background:#ff6cb0;transform:rotateY(90deg) translateZ(60px)}.f-left{background:#6cffb8;color:#111;transform:rotateY(-90deg) translateZ(60px)}.f-top{background:#f59e0b;color:#111;transform:rotateX(90deg) translateZ(60px)}.f-bottom{background:#111;transform:rotateX(-90deg) translateZ(60px)}`,
    body: `<div class="scene"><div class="cube"><div class="face f-front">F</div><div class="face f-back">B</div><div class="face f-right">R</div><div class="face f-left">L</div><div class="face f-top">T</div><div class="face f-bottom">Bo</div></div></div>` },

  { slug: '3d-cube-mouse-rotate', title: 'Mouse Rotate 3D Cube', category: '3d-effects', tags: ['3d', 'cube', 'mouse'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#111;perspective:900px}.wrap{width:140px;height:140px;transform-style:preserve-3d;transition:transform .08s ease-out}.cube{position:relative;width:120px;height:120px;transform-style:preserve-3d;margin:10px}.face{position:absolute;inset:0;border-radius:8px;display:grid;place-items:center;font-weight:800;color:#fff;backface-visibility:hidden;border:1px solid rgba(255,255,255,.1)}.f1{background:#6c8cff;transform:translateZ(60px)}.f2{background:#ff6cb0;transform:rotateY(180deg) translateZ(60px)}.f3{background:#6cffb8;color:#111;transform:rotateY(90deg) translateZ(60px)}.f4{background:#764ba2;transform:rotateY(-90deg) translateZ(60px)}.f5{background:#f59e0b;color:#111;transform:rotateX(90deg) translateZ(60px)}.f6{background:#222;transform:rotateX(-90deg) translateZ(60px)}`,
    body: `<div class="wrap" id="w"><div class="cube"><div class="face f1">1</div><div class="face f2">2</div><div class="face f3">3</div><div class="face f4">4</div><div class="face f5">5</div><div class="face f6">6</div></div></div>`,
    script: `let rx=-15,ry=20;const w=document.getElementById('w');addEventListener('mousemove',e=>{ry=(e.clientX/innerWidth-.5)*70;rx=-(e.clientY/innerHeight-.5)*50;w.style.transform='rotateX('+rx+'deg) rotateY('+ry+'deg)';});` },

  { slug: '3d-cube-image-faces', title: 'Image Face 3D Cube', category: '3d-effects', tags: ['3d', 'cube', 'image'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#000;perspective:1000px}.cube{position:relative;width:160px;height:160px;transform-style:preserve-3d;animation:rot 12s linear infinite}@keyframes rot{to{transform:rotateX(-12deg) rotateY(360deg)}}.face{position:absolute;inset:0;backface-visibility:hidden;overflow:hidden;border-radius:4px;border:2px solid rgba(255,255,255,.1)}.face img{width:100%;height:100%;object-fit:cover}.f1{transform:translateZ(80px)}.f2{transform:rotateY(180deg) translateZ(80px)}.f3{transform:rotateY(90deg) translateZ(80px)}.f4{transform:rotateY(-90deg) translateZ(80px)}`,
    body: `<div class="cube"><div class="face f1"><img src="${IMG45}" alt=""></div><div class="face f2"><img src="${IMG45}" alt="" style="filter:hue-rotate(90deg)"></div><div class="face f3"><img src="${IMG45}" alt="" style="filter:hue-rotate(180deg)"></div><div class="face f4"><img src="${IMG45}" alt="" style="filter:hue-rotate(270deg)"></div></div>` },

  { slug: '3d-prism-trio', title: '3D Prism Trio', category: '3d-effects', tags: ['3d', 'prism', 'shapes'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#0d0d0f;perspective:700px;gap:2rem}.row{display:flex;gap:3rem;transform-style:preserve-3d;animation:bob 4s ease-in-out infinite}@keyframes bob{0%,100%{transform:rotateX(10deg) translateY(0)}50%{transform:rotateX(10deg) translateY(-12px)}}.prism{width:0;height:0;border-left:40px solid transparent;border-right:40px solid transparent;border-bottom:70px solid var(--c);filter:drop-shadow(0 12px 20px rgba(0,0,0,.4));transform:rotateY(var(--r))}`,
    body: `<div class="row"><div class="prism" style="--c:#6c8cff;--r:0deg"></div><div class="prism" style="--c:#ff6cb0;--r:120deg"></div><div class="prism" style="--c:#6cffb8;--r:240deg"></div></div>` },

  // ── 3D cards ──
  { slug: '3d-card-flip-hover', title: '3D Flip Card Hover', category: '3d-effects', tags: ['3d', 'card', 'flip'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#0d0d0f;perspective:1000px;padding:2rem}.card{width:min(280px,85vw);height:180px;position:relative;transform-style:preserve-3d;transition:transform .7s cubic-bezier(.22,.61,.36,1);cursor:pointer}.card:hover{transform:rotateY(180deg)}.face{position:absolute;inset:0;border-radius:16px;backface-visibility:hidden;display:grid;place-items:center;color:#fff;font-weight:800;font-size:1.3rem}.front{background:linear-gradient(135deg,#6c8cff,#764ba2)}.back{background:linear-gradient(135deg,#ff6cb0,#6cffb8);color:#111;transform:rotateY(180deg)}`,
    body: `<div class="card"><div class="face front">Hover me</div><div class="face back">Flipped!</div></div>` },

  { slug: '3d-card-tilt-depth', title: '3D Tilt Depth Card', category: '3d-effects', tags: ['3d', 'card', 'tilt', 'depth'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#111;perspective:900px;padding:2rem}.card{width:min(300px,90vw);padding:2rem;border-radius:20px;background:linear-gradient(145deg,#1a1a2e,#2a2a40);border:1px solid rgba(255,255,255,.08);color:#fff;transform-style:preserve-3d;transition:transform .12s ease-out;box-shadow:0 20px 50px rgba(0,0,0,.4)}h3{font-size:1.3rem;transform:translateZ(40px);margin-bottom:.5rem}p{color:#888;font-size:.9rem;transform:translateZ(25px)}.badge{position:absolute;top:1rem;right:1rem;padding:4px 10px;border-radius:99px;background:#6c8cff;font-size:.7rem;font-weight:700;transform:translateZ(50px)}`,
    body: `<div class="card" id="c"><span class="badge">3D</span><h3>Depth card</h3><p>Layers float at different Z depths on mouse tilt.</p></div>`,
    script: tilt('#c', 22) },

  { slug: '3d-card-stack-float', title: '3D Floating Card Stack', category: '3d-effects', tags: ['3d', 'card', 'stack', 'float'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#0a0a0c;perspective:800px}.stack{position:relative;width:240px;height:300px;transform-style:preserve-3d;animation:float 3s ease-in-out infinite}@keyframes float{0%,100%{transform:rotateX(8deg) translateY(0)}50%{transform:rotateX(8deg) translateY(-14px)}}.card{position:absolute;inset:0;border-radius:16px;overflow:hidden;box-shadow:0 20px 50px rgba(0,0,0,.5)}.card img{width:100%;height:100%;object-fit:cover}.card:nth-child(1){transform:translateZ(0)}.card:nth-child(2){transform:translateZ(-20px) translateY(8px) scale(.97)}.card:nth-child(3){transform:translateZ(-40px) translateY(16px) scale(.94)}`,
    body: `<div class="stack">${Array.from({length:3},()=>`<div class="card"><img src="${IMG45}" alt=""></div>`).join('')}</div>` },

  { slug: '3d-card-spread-mouse', title: '3D Mouse Spread Cards', category: '3d-effects', tags: ['3d', 'card', 'spread', 'mouse'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#111;perspective:1000px;overflow:hidden}.deck{position:relative;width:200px;height:260px;transform-style:preserve-3d}.card{position:absolute;inset:0;border-radius:14px;overflow:hidden;transition:transform .4s cubic-bezier(.22,.61,.36,1);box-shadow:0 16px 40px rgba(0,0,0,.4)}.card img{width:100%;height:100%;object-fit:cover}`,
    body: `<div class="deck" id="d">${Array.from({length:5},()=>'<div class="card"><img src="'+IMG45+'" alt=""></div>').join('')}</div>`,
    script: `const d=document.getElementById('d'),cards=[...d.children];addEventListener('mousemove',e=>{const x=(e.clientX/innerWidth-.5)*2;cards.forEach((c,i)=>{const o=i-(cards.length-1)/2;c.style.transform='translateX('+(o*x*55)+'px) rotateY('+(o*x*12)+'deg) translateZ('+(Math.abs(o)*-15)+'px)';c.style.zIndex=i;});});` },

  { slug: '3d-card-accordion-fold', title: '3D Accordion Fold', category: '3d-effects', tags: ['3d', 'card', 'accordion', 'fold'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#fafafa;perspective:900px;padding:2rem}.fold{display:flex;transform-style:preserve-3d;cursor:pointer}.panel{width:70px;height:200px;background:linear-gradient(180deg,var(--c),color-mix(in srgb,var(--c),#000 30%));transform-origin:left;transition:transform .5s cubic-bezier(.22,.61,.36,1);display:grid;place-items:center;color:#fff;font-weight:800;font-size:.9rem;border-right:1px solid rgba(255,255,255,.2)}.fold:hover .panel:nth-child(1){transform:rotateY(-40deg)}.fold:hover .panel:nth-child(2){transform:rotateY(-25deg)}.fold:hover .panel:nth-child(3){transform:rotateY(-10deg)}.fold:hover .panel:nth-child(5){transform:rotateY(10deg)}.fold:hover .panel:nth-child(6){transform:rotateY(25deg)}.fold:hover .panel:nth-child(7){transform:rotateY(40deg)}`,
    body: `<div class="fold">${['#6c8cff','#7a7fff','#8a6cff','#9a5cff','#aa4cff','#ba3cff','#ca2cff'].map((c,i)=>`<div class="panel" style="--c:${c}">${i+1}</div>`).join('')}</div>` },

  { slug: '3d-flip-tile-grid', title: '3D Flip Tile Grid', category: '3d-effects', tags: ['3d', 'grid', 'flip', 'tiles'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#0d0d0f;perspective:600px;padding:2rem}.grid{display:grid;grid-template-columns:repeat(3,80px);gap:10px}.tile{aspect-ratio:1;position:relative;transform-style:preserve-3d;transition:transform .5s cubic-bezier(.22,.61,.36,1);cursor:pointer}.tile:hover{transform:rotateY(180deg)}.side{position:absolute;inset:0;border-radius:10px;backface-visibility:hidden;display:grid;place-items:center;font-weight:800;color:#fff}.front{background:linear-gradient(135deg,#6c8cff,#764ba2)}.back{background:linear-gradient(135deg,#ff6cb0,#6cffb8);color:#111;transform:rotateY(180deg)}`,
    body: `<div class="grid">${Array.from({length:9},(_,i)=>`<div class="tile"><div class="side front">${i+1}</div><div class="side back">✓</div></div>`).join('')}</div>` },

  // ── 3D buttons & UI ──
  { slug: '3d-button-extrude', title: '3D Extrude Button', category: '3d-effects', tags: ['3d', 'button', 'extrude'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#f5f5f5}.btn{position:relative;padding:16px 40px;border:none;border-radius:10px;background:#6c8cff;color:#fff;font-weight:700;font-size:1rem;cursor:pointer;box-shadow:0 6px 0 #4a5fd4,0 8px 20px rgba(108,140,255,.35);transition:transform .1s,box-shadow .1s}.btn:hover{transform:translateY(-2px);box-shadow:0 8px 0 #4a5fd4,0 12px 28px rgba(108,140,255,.4)}.btn:active{transform:translateY(4px);box-shadow:0 2px 0 #4a5fd4,0 4px 12px rgba(108,140,255,.3)}`,
    body: `<button class="btn">Press me</button>` },

  { slug: '3d-button-layer-stack', title: '3D Layer Stack Button', category: '3d-effects', tags: ['3d', 'button', 'stack'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#111;perspective:500px}.btn-wrap{position:relative;transform-style:preserve-3d;transition:transform .15s}.layer{position:absolute;inset:-4px;border-radius:12px;background:var(--c);transform:translateZ(var(--z))}.layer--1{--c:#4a5fd4;--z:-8px}.layer--2{--c:#5a6fe4;--z:-4px}.btn{position:relative;padding:14px 36px;border:none;border-radius:10px;background:#6c8cff;color:#fff;font-weight:700;font-size:.95rem;cursor:pointer;transform:translateZ(0)}.btn-wrap:hover{transform:rotateX(8deg)}.btn-wrap:active{transform:rotateX(12deg) translateY(2px)}`,
    body: `<div class="btn-wrap"><div class="layer layer--1"></div><div class="layer layer--2"></div><button class="btn">Stacked</button></div>` },

  { slug: '3d-toggle-switch', title: '3D Toggle Switch', category: '3d-effects', tags: ['3d', 'toggle', 'switch'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#0d0d0f;perspective:400px}.track{width:64px;height:36px;border-radius:99px;background:#222;position:relative;cursor:pointer;box-shadow:inset 0 4px 8px rgba(0,0,0,.5);transform:rotateX(15deg)}.knob{position:absolute;top:4px;left:4px;width:28px;height:28px;border-radius:50%;background:linear-gradient(145deg,#888,#555);box-shadow:0 4px 8px rgba(0,0,0,.4);transition:transform .3s cubic-bezier(.22,.61,.36,1),background .3s}.track.on{background:#6c8cff}.track.on .knob{transform:translateX(28px);background:linear-gradient(145deg,#fff,#ddd)}`,
    body: `<div class="track" id="t"><div class="knob"></div></div>`,
    script: `document.getElementById('t').onclick=function(){this.classList.toggle('on');};` },

  // ── 3D text ──
  { slug: '3d-text-extrude-layers', title: '3D Extruded Text', category: '3d-effects', tags: ['3d', 'text', 'extrude'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#0a0a0c;perspective:600px}h1{font-size:clamp(3rem,10vw,6rem);font-weight:900;color:#6c8cff;position:relative;transform:rotateX(12deg) rotateY(-8deg);text-shadow:1px 1px 0 #5a7ae8,2px 2px 0 #4a6ad8,3px 3px 0 #3a5ac8,4px 4px 0 #2a4ab8,5px 5px 0 #1a3aa8,6px 6px 0 #0a2a98,8px 8px 20px rgba(0,0,0,.5)}`,
    body: `<h1>DEPTH</h1>` },

  { slug: '3d-text-rotate-cylinder', title: '3D Rotating Text Ring', category: '3d-effects', tags: ['3d', 'text', 'rotate'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#000;perspective:800px;overflow:hidden}.ring{position:relative;width:280px;height:120px;transform-style:preserve-3d;animation:spin 10s linear infinite}@keyframes spin{to{transform:rotateY(360deg)}}.char{position:absolute;left:50%;top:50%;font-size:2rem;font-weight:900;color:#fff;transform-style:preserve-3d;transform-origin:center center -140px}`,
    body: `<div class="ring" id="r"></div>`,
    script: `const r=document.getElementById('r'),txt='ROTATE 3D • ';[...txt].forEach((ch,i)=>{const s=document.createElement('span');s.className='char';s.textContent=ch;s.style.transform='rotateY('+(i/txt.length*360)+'deg) translateZ(140px)';r.appendChild(s);});` },

  { slug: '3d-text-wave-perspective', title: '3D Wave Text', category: '3d-effects', tags: ['3d', 'text', 'wave'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#111;perspective:500px}h1{font-size:clamp(2rem,6vw,4rem);font-weight:900;color:#fff;display:flex;gap:4px}.ch{display:inline-block;animation:wave 2s ease-in-out infinite;transform-style:preserve-3d}@keyframes wave{0%,100%{transform:rotateX(0) translateZ(0)}50%{transform:rotateX(40deg) translateZ(20px)}}.ch:nth-child(1){animation-delay:0s;color:#6c8cff}.ch:nth-child(2){animation-delay:.1s;color:#ff6cb0}.ch:nth-child(3){animation-delay:.2s;color:#6cffb8}.ch:nth-child(4){animation-delay:.3s;color:#f59e0b}.ch:nth-child(5){animation-delay:.4s;color:#764ba2}.ch:nth-child(6){animation-delay:.5s;color:#6c8cff}`,
    body: `<h1>${'WAVE3D'.split('').map(c=>`<span class="ch">${c}</span>`).join('')}</h1>` },

  // ── 3D carousels & galleries ──
  { slug: '3d-carousel-ring', title: '3D Ring Carousel', category: '3d-effects', tags: ['3d', 'carousel', 'ring'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#0d0d0f;perspective:900px;overflow:hidden}.ring{position:relative;width:200px;height:200px;transform-style:preserve-3d;animation:spin 14s linear infinite}@keyframes spin{to{transform:rotateY(360deg)}}.item{position:absolute;left:50%;top:50%;width:100px;height:130px;margin:-65px 0 0 -50px;border-radius:12px;overflow:hidden;backface-visibility:hidden;box-shadow:0 12px 30px rgba(0,0,0,.4)}.item img{width:100%;height:100%;object-fit:cover}`,
    body: `<div class="ring" id="r">${Array.from({length:6},(_,i)=>`<div class="item" style="transform:rotateY(${i*60}deg) translateZ(180px)"><img src="${IMG45}" alt=""></div>`).join('')}</div>` },

  { slug: '3d-gallery-perspective-wall', title: '3D Perspective Gallery', category: '3d-effects', tags: ['3d', 'gallery', 'perspective'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#111;perspective:1200px;overflow:hidden;padding:2rem}.wall{display:flex;gap:20px;transform:rotateX(8deg) rotateY(-12deg);transform-style:preserve-3d}.frame{width:min(140px,22vw);aspect-ratio:4/5;border-radius:12px;overflow:hidden;box-shadow:0 20px 50px rgba(0,0,0,.5);transition:transform .4s cubic-bezier(.22,.61,.36,1)}.frame:hover{transform:translateZ(30px) scale(1.05)}.frame img{width:100%;height:100%;object-fit:cover}`,
    body: `<div class="wall">${Array.from({length:5},()=>`<div class="frame"><img src="${IMG45}" alt=""></div>`).join('')}</div>` },

  { slug: '3d-image-tilt-frame', title: '3D Image Tilt Frame', category: '3d-effects', tags: ['3d', 'image', 'tilt'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#0d0d0f;perspective:1000px;padding:2rem}.frame{width:min(360px,90vw);border-radius:16px;overflow:hidden;transform-style:preserve-3d;transition:transform .12s ease-out;box-shadow:0 30px 60px rgba(0,0,0,.5)}.frame img{width:100%;display:block;transform:translateZ(20px)}.shine{position:absolute;inset:0;background:linear-gradient(135deg,rgba(255,255,255,.15),transparent 50%);pointer-events:none;transform:translateZ(30px)}`,
    body: `<div class="frame" id="f" style="position:relative"><img src="${IMG}" alt=""><div class="shine"></div></div>`,
    script: tilt('#f', 16) },

  { slug: '3d-parallax-layers-scene', title: '3D Parallax Layers', category: '3d-effects', tags: ['3d', 'parallax', 'layers'],
    style: `body{margin:0;min-height:100vh;background:#000;overflow:hidden;perspective:1000px}.scene{position:relative;height:100vh;transform-style:preserve-3d}.layer{position:absolute;inset:0;display:grid;place-items:center}.layer img{width:110%;height:110%;object-fit:cover;opacity:.5}.label{position:relative;z-index:5;color:#fff;font-size:3rem;font-weight:900;text-shadow:0 4px 30px rgba(0,0,0,.8)}`,
    body: `<div class="scene" id="s"><div class="layer" data-z="30"><img src="${IMG}" alt=""></div><div class="layer" data-z="60"><img src="${IMG}" alt="" style="filter:brightness(.6)"></div><div class="layer"><span class="label">Layers</span></div></div>`,
    script: `const s=document.getElementById('s');addEventListener('mousemove',e=>{const x=(e.clientX/innerWidth-.5)*2,y=(e.clientY/innerHeight-.5)*2;s.querySelectorAll('.layer').forEach(l=>{const z=+(l.dataset.z||0);l.style.transform='translateX('+(x*z)+'px) translateY('+(y*z)+'px) translateZ('+(z?-z:0)+'px)';});});` },

  // ── 3D scenes & experimental ──
  { slug: '3d-isometric-grid', title: '3D Isometric Grid', category: '3d-effects', tags: ['3d', 'isometric', 'grid'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#1a1a2e;perspective:800px;padding:2rem}.grid{display:grid;grid-template-columns:repeat(4,50px);gap:8px;transform:rotateX(55deg) rotateZ(-45deg);transform-style:preserve-3d}.cell{width:50px;height:50px;background:linear-gradient(135deg,#6c8cff,#764ba2);border-radius:6px;animation:rise 2s ease-in-out infinite;box-shadow:0 8px 0 #4a5fd4,0 12px 20px rgba(0,0,0,.3)}.cell:nth-child(odd){animation-delay:.3s;background:linear-gradient(135deg,#ff6cb0,#d44a8a);box-shadow:0 8px 0 #b43a7a,0 12px 20px rgba(0,0,0,.3)}@keyframes rise{0%,100%{transform:translateZ(0)}50%{transform:translateZ(20px)}}`,
    body: `<div class="grid">${Array.from({length:16},()=>'<div class="cell"></div>').join('')}</div>` },

  { slug: '3d-room-corner', title: '3D Room Corner', category: '3d-effects', tags: ['3d', 'room', 'perspective'],
    style: `body{margin:0;min-height:100vh;background:#111;perspective:600px;display:grid;place-items:center;overflow:hidden}.room{position:relative;width:min(400px,90vw);height:min(300px,60vh);transform-style:preserve-3d;transform:rotateX(5deg) rotateY(-15deg)}.wall{position:absolute;background:#2a2a40;border:1px solid #3a3a55}.floor{bottom:0;left:0;right:0;height:50%;transform-origin:bottom;transform:rotateX(90deg);background:linear-gradient(#333,#222)}.left{left:0;top:0;bottom:0;width:50%;transform-origin:left;transform:rotateY(90deg);background:#3a3a55}.back{inset:0;background:linear-gradient(180deg,#4a4a6a,#2a2a40)}.obj{position:absolute;bottom:30%;left:40%;width:60px;height:80px;background:#6c8cff;border-radius:8px;transform:translateZ(40px);box-shadow:0 10px 30px rgba(0,0,0,.4)}`,
    body: `<div class="room"><div class="wall back"></div><div class="wall left"></div><div class="wall floor"></div><div class="obj"></div></div>` },

  { slug: '3d-tunnel-scroll', title: '3D Tunnel Scroll', category: '3d-effects', tags: ['3d', 'tunnel', 'scroll'],
    style: `body{margin:0;background:#000;color:#fff;perspective:400px}.tunnel{height:400vh;position:relative}.ring{position:sticky;top:0;height:100vh;display:grid;place-items:center;transform-style:preserve-3d}.frame{position:absolute;width:min(300px,80vw);aspect-ratio:16/10;border:2px solid rgba(108,140,255,.3);border-radius:12px;display:grid;place-items:center;font-size:2rem;font-weight:800}`,
    body: `<div class="tunnel"><div class="ring" id="r">${Array.from({length:8},(_,i)=>`<div class="frame" data-i="${i}">${i+1}</div>`).join('')}</div></div>`,
    script: `const tunnel=document.querySelector('.tunnel'),frames=[...document.querySelectorAll('.frame')];addEventListener('scroll',()=>{const r=tunnel.getBoundingClientRect();const p=Math.min(1,Math.max(0,-r.top/(r.height-innerHeight));frames.forEach((f,i)=>{const d=i/frames.length;const z=-(d*400)+(p*400);const sc=1-d*.12+p*.12;f.style.transform='translateZ('+z+'px) scale('+sc+')';f.style.opacity=1-Math.abs(d-p)*1.5;});},{passive:true});` },

  { slug: '3d-mouse-tilt-scene', title: '3D Mouse Tilt Scene', category: '3d-effects', tags: ['3d', 'mouse', 'tilt', 'scene'],
    style: `body{margin:0;min-height:100vh;background:linear-gradient(180deg,#0d0d0f,#1a1a2e);display:grid;place-items:center;perspective:1000px;overflow:hidden}.scene{width:min(500px,90vw);height:min(320px,60vh);transform-style:preserve-3d;transition:transform .1s ease-out;position:relative}.card{position:absolute;border-radius:16px;display:grid;place-items:center;color:#fff;font-weight:800;font-size:1.2rem;box-shadow:0 20px 50px rgba(0,0,0,.4)}.c1{width:200px;height:140px;background:#6c8cff;transform:translateZ(60px);top:20%;left:10%}.c2{width:160px;height:120px;background:#ff6cb0;transform:translateZ(20px);top:40%;right:15%}.c3{width:180px;height:100px;background:#6cffb8;color:#111;transform:translateZ(100px);bottom:15%;left:30%}`,
    body: `<div class="scene" id="s"><div class="card c1">Front</div><div class="card c2">Mid</div><div class="card c3">Deep</div></div>`,
    script: `const s=document.getElementById('s');addEventListener('mousemove',e=>{const x=(e.clientX/innerWidth-.5)*30,y=-(e.clientY/innerHeight-.5)*20;s.style.transform='rotateY('+x+'deg) rotateX('+y+'deg)';});` },

  { slug: '3d-floating-orbs', title: '3D Floating Orbs', category: '3d-effects', tags: ['3d', 'orbs', 'float'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#050508;perspective:800px;overflow:hidden}.field{position:relative;width:min(400px,90vw);height:min(400px,70vh);transform-style:preserve-3d;animation:tilt 6s ease-in-out infinite}@keyframes tilt{0%,100%{transform:rotateX(10deg) rotateY(-10deg)}50%{transform:rotateX(-5deg) rotateY(10deg)}}.orb{position:absolute;width:var(--s,60px);height:var(--s,60px);border-radius:50%;background:radial-gradient(circle at 30% 30%,var(--c),color-mix(in srgb,var(--c),#000 40%));box-shadow:0 10px 30px color-mix(in srgb,var(--c),transparent 60%);transform:translate3d(var(--x),var(--y),var(--z));animation:bob 3s ease-in-out infinite;animation-delay:var(--d)}@keyframes bob{0%,100%{transform:translate3d(var(--x),var(--y),var(--z))}50%{transform:translate3d(var(--x),calc(var(--y) - 15px),var(--z))}}`,
    body: `<div class="field">${[{x:'10%',y:'20%',z:'40px',s:'70px',c:'#6c8cff',d:'0s'},{x:'60%',y:'10%',z:'80px',s:'50px',c:'#ff6cb0',d:'.5s'},{x:'30%',y:'55%',z:'20px',s:'90px',c:'#6cffb8',d:'1s'},{x:'70%',y:'60%',z:'100px',s:'45px',c:'#f59e0b',d:'1.5s'}].map(o=>`<div class="orb" style="--x:${o.x};--y:${o.y};--z:${o.z};--s:${o.s};--c:${o.c};--d:${o.d}"></div>`).join('')}</div>` },

  { slug: '3d-book-open', title: '3D Book Open', category: '3d-effects', tags: ['3d', 'book', 'open'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#2a2520;perspective:1200px;padding:2rem}.book{position:relative;width:min(320px,85vw);height:200px;transform-style:preserve-3d;cursor:pointer}.cover{position:absolute;inset:0;border-radius:4px 12px 12px 4px;background:linear-gradient(135deg,#6c8cff,#4a5fd4);transform-origin:left;transition:transform .8s cubic-bezier(.22,.61,.36,1);display:grid;place-items:center;color:#fff;font-weight:800;font-size:1.2rem;box-shadow:0 10px 30px rgba(0,0,0,.4)}.pages{position:absolute;inset:4px 0 4px 8px;background:#faf8f5;border-radius:2px;display:grid;place-items:center;color:#333;font-size:.9rem}.book.open .cover{transform:rotateY(-160deg)}`,
    body: `<div class="book" id="b"><div class="pages">Chapter 1</div><div class="cover">Open</div></div><p style="margin-top:1.5rem;color:#888;font-size:.85rem">Click to open</p>`,
    script: `document.getElementById('b').onclick=function(){this.classList.toggle('open');};` },

  { slug: '3d-door-swing', title: '3D Door Swing', category: '3d-effects', tags: ['3d', 'door', 'swing'],
    style: `body{margin:0;min-height:100vh;background:#111;perspective:800px;display:grid;place-items:center}.frame{position:relative;width:min(280px,80vw);height:min(360px,70vh);transform-style:preserve-3d}.door{position:absolute;inset:0;background:linear-gradient(135deg,#3a3a55,#2a2a40);border:3px solid #4a4a65;border-radius:4px;transform-origin:left;transition:transform .9s cubic-bezier(.22,.61,.36,1);cursor:pointer;display:grid;place-items:center;color:#888;font-weight:700}.door::before{content:'';position:absolute;right:20px;top:50%;width:12px;height:12px;border-radius:50%;background:#6c8cff;box-shadow:0 0 10px #6c8cff}.frame.open .door{transform:rotateY(-75deg)}.inside{position:absolute;inset:0;background:url('${IMG45}') center/cover;border-radius:4px}`,
    body: `<div class="frame" id="f"><div class="inside"></div><div class="door">Push</div></div>`,
    script: `document.getElementById('f').onclick=function(){this.classList.toggle('open');};` },

  { slug: '3d-hero-tilt-landing', title: '3D Tilt Hero Landing', category: '3d-effects', tags: ['3d', 'hero', 'tilt', 'landing'],
    style: `body{margin:0;min-height:100vh;background:#0a0a0c;color:#fff;perspective:1000px;overflow:hidden}.hero{min-height:100vh;display:grid;grid-template-columns:1fr 1fr;align-items:center;gap:2rem;padding:4rem 6%;transform-style:preserve-3d;transition:transform .1s ease-out}h1{font-size:clamp(2.2rem,4vw,3.5rem);font-weight:900;line-height:1.1;margin-bottom:1rem;transform:translateZ(40px)}p{color:#888;max-width:40ch;transform:translateZ(20px)}.visual{border-radius:16px;overflow:hidden;box-shadow:0 30px 60px rgba(0,0,0,.5);transform:translateZ(60px)}.visual img{width:100%;aspect-ratio:16/10;object-fit:cover}@media(max-width:768px){.hero{grid-template-columns:1fr;padding:3rem 1.5rem}}`,
    body: `<div class="hero" id="h"><div><h1>Build in 3D</h1><p>Mouse-tilted hero with floating depth layers for modern landing pages.</p></div><div class="visual"><img src="${IMG}" alt=""></div></div>`,
    script: tilt('#h', 6) },

  { slug: '3d-loader-cube', title: '3D Cube Loader', category: '3d-effects', tags: ['3d', 'loader', 'cube'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#fafafa;perspective:600px}.wrap{text-align:center}.cube{position:relative;width:40px;height:40px;transform-style:preserve-3d;animation:spin 1.2s linear infinite;margin:0 auto 1rem}@keyframes spin{to{transform:rotateX(45deg) rotateY(360deg)}}.f{position:absolute;inset:0;background:#6c8cff;opacity:.9}.f1{transform:translateZ(20px)}.f2{transform:rotateY(180deg) translateZ(20px);background:#ff6cb0}.f3{transform:rotateY(90deg) translateZ(20px);background:#6cffb8}.f4{transform:rotateY(-90deg) translateZ(20px);background:#764ba2}p{font-size:.85rem;color:#888}`,
    body: `<div class="wrap"><div class="cube"><div class="f f1"></div><div class="f f2"></div><div class="f f3"></div><div class="f f4"></div></div><p>Loading</p></div>` },

  { slug: '3d-scroll-rotate-showcase', title: '3D Scroll Rotate Showcase', category: '3d-effects', tags: ['3d', 'scroll', 'rotate'],
    style: `body{margin:0;background:#0d0d0f;color:#fff;perspective:1000px}.pin{height:300vh}.stage{position:sticky;top:0;height:100vh;display:grid;place-items:center;transform-style:preserve-3d}.panel{width:min(320px,85vw);padding:2.5rem;border-radius:20px;background:linear-gradient(135deg,#6c8cff,#764ba2);text-align:center;box-shadow:0 30px 80px rgba(108,140,255,.3)}.panel h2{font-size:2rem;font-weight:900;margin-bottom:.5rem}.panel p{color:rgba(255,255,255,.8)}`,
    body: `<div class="pin"><div class="stage"><div class="panel" id="p"><h2>Rotate</h2><p>Scroll to spin in 3D space</p></div></div></div>`,
    script: `const pin=document.querySelector('.pin'),p=document.getElementById('p');addEventListener('scroll',()=>{const r=pin.getBoundingClientRect();const pr=Math.min(1,Math.max(0,-r.top/(r.height-innerHeight)));p.style.transform='rotateY('+(pr*360)+'deg) rotateX('+(pr*20)+'deg) translateZ('+(pr*80)+'px)';},{passive:true});` },

  { slug: '3d-ribbon-banner', title: '3D Ribbon Banner', category: '3d-effects', tags: ['3d', 'ribbon', 'banner'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#111;perspective:600px;padding:2rem}.ribbon{position:relative;padding:14px 48px;background:linear-gradient(180deg,#6c8cff,#4a5fd4);color:#fff;font-weight:800;font-size:1rem;letter-spacing:.08em;transform:rotateX(20deg) rotateZ(-2deg);box-shadow:0 12px 0 #3a4fc4,0 20px 40px rgba(0,0,0,.4)}.ribbon::before,.ribbon::after{content:'';position:absolute;top:100%;width:0;height:0;border-style:solid}.ribbon::before{left:0;border-width:10px 0 0 14px;border-color:#3a4fc4 transparent transparent}.ribbon::after{right:0;border-width:10px 14px 0 0;border-color:#3a4fc4 transparent transparent}`,
    body: `<div class="ribbon">NEW COLLECTION</div>` },

  { slug: '3d-layered-squares', title: '3D Layered Squares', category: '3d-effects', tags: ['3d', 'layers', 'squares'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#0d0d0f;perspective:700px}.stack{position:relative;width:120px;height:120px;transform-style:preserve-3d;animation:spin 12s linear infinite}@keyframes spin{to{transform:rotateX(20deg) rotateY(360deg)}}.sq{position:absolute;inset:0;border-radius:12px;border:2px solid rgba(255,255,255,.15)}.sq:nth-child(1){background:rgba(108,140,255,.9);transform:translateZ(0)}.sq:nth-child(2){background:rgba(255,108,176,.8);transform:translateZ(25px)}.sq:nth-child(3){background:rgba(108,255,184,.7);transform:translateZ(50px)}.sq:nth-child(4){background:rgba(245,158,11,.6);transform:translateZ(75px)}`,
    body: `<div class="stack"><div class="sq"></div><div class="sq"></div><div class="sq"></div><div class="sq"></div></div>` },

  { slug: '3d-hover-lift-grid', title: '3D Hover Lift Grid', category: '3d-effects', tags: ['3d', 'grid', 'hover', 'lift'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#fafafa;perspective:800px;padding:2rem}.grid{display:grid;grid-template-columns:repeat(3,90px);gap:14px;transform:rotateX(12deg);transform-style:preserve-3d}.cell{aspect-ratio:1;border-radius:12px;background:linear-gradient(135deg,#fff,#f0f0f0);box-shadow:0 4px 0 #ddd,0 8px 20px rgba(0,0,0,.08);display:grid;place-items:center;font-weight:700;color:#333;transition:transform .3s cubic-bezier(.22,.61,.36,1),box-shadow .3s;cursor:pointer}.cell:hover{transform:translateZ(24px) translateY(-8px);box-shadow:0 12px 0 #ccc,0 20px 40px rgba(0,0,0,.12)}`,
    body: `<div class="grid">${Array.from({length:9},(_,i)=>`<div class="cell">${i+1}</div>`).join('')}</div>` },

  { slug: '3d-spinning-donut', title: '3D Spinning Donut', category: '3d-effects', tags: ['3d', 'donut', 'spin'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#000;perspective:700px}.donut{width:120px;height:120px;border-radius:50%;border:24px solid transparent;border-top-color:#6c8cff;border-right-color:#ff6cb0;transform-style:preserve-3d;animation:donut 2s linear infinite;box-shadow:inset 0 0 30px rgba(108,140,255,.2),0 0 40px rgba(108,140,255,.15)}@keyframes donut{0%{transform:rotateX(60deg) rotateZ(0)}100%{transform:rotateX(60deg) rotateZ(360deg)}}`,
    body: `<div class="donut"></div>` },

  { slug: '3d-card-cylinder-scroll', title: '3D Cylinder Card Scroll', category: '3d-effects', tags: ['3d', 'cylinder', 'scroll'],
    style: `body{margin:0;background:#111;color:#fff;perspective:800px;overflow-x:auto;overflow-y:hidden;height:100vh}.track{display:flex;gap:0;padding:20vh 50vw;width:max-content;transform-style:preserve-3d}.card{flex:0 0 200px;height:260px;margin:0 20px;border-radius:14px;overflow:hidden;box-shadow:0 20px 50px rgba(0,0,0,.5);will-change:transform}.card img{width:100%;height:100%;object-fit:cover}`,
    body: `<div class="track" id="t">${Array.from({length:8},()=>'<div class="card"><img src="'+IMG45+'" alt=""></div>').join('')}</div>`,
    script: `const cards=[...document.querySelectorAll('.card')];function u(){const cx=innerWidth/2;cards.forEach(c=>{const r=c.getBoundingClientRect();const d=(r.left+r.width/2-cx)/cx;c.style.transform='rotateY('+d*45+'deg) translateZ('+Math.abs(d)*-80+'px)';c.style.opacity=1-Math.abs(d)*.35;});}addEventListener('scroll',u,{passive:true});document.documentElement.style.overflowX='auto';document.documentElement.style.overflowY='hidden';u();` },
];
