const IMG = '../stock/media/16-9 Aspect Ratio(image).png';
const IMG45 = '../stock/media/4-5 Aspect Ratio(image).png';

const tilt = (sel, rx = 20, ry = 20) =>
  `const el=document.querySelector('${sel}');addEventListener('mousemove',e=>{const x=(e.clientX/innerWidth-.5)*${ry*2};const y=-(e.clientY/innerHeight-.5)*${rx*2};el.style.transform='rotateX('+y+'deg) rotateY('+x+'deg)';});addEventListener('mouseleave',()=>el.style.transform='');`;

const tiltLocal = (sel, amt = 18) =>
  `const el=document.querySelector('${sel}');el.addEventListener('mousemove',e=>{const r=el.getBoundingClientRect();const x=(e.clientX-r.left)/r.width-.5;const y=(e.clientY-r.top)/r.height-.5;el.style.transform='rotateY('+(x*${amt})+'deg) rotateX('+(-y*${amt})+'deg)';});el.addEventListener('mouseleave',()=>el.style.transform='');`;

module.exports = [
  { slug: '3d-mouse-page-tilt', title: '3D Page Mouse Tilt', category: '3d-mouse', tags: ['3d', 'mouse', 'page', 'tilt'],
    style: `body{margin:0;min-height:100vh;background:linear-gradient(135deg,#0d0d0f,#1a1a2e);perspective:1200px;overflow:hidden}.page{min-height:100vh;display:grid;place-items:center;transform-style:preserve-3d;transition:transform .08s ease-out}h1{font-size:clamp(2.5rem,7vw,4.5rem);font-weight:900;color:#fff;transform:translateZ(60px);text-align:center}p{color:#888;margin-top:1rem;transform:translateZ(30px);text-align:center}`,
    body: `<div class="page" id="p"><div><h1>Move mouse</h1><p>Whole scene tilts in 3D</p></div></div>`,
    script: tilt('#p', 12, 16) },

  { slug: '3d-mouse-cube-track', title: '3D Cube Mouse Track', category: '3d-mouse', tags: ['3d', 'mouse', 'cube'],
    style: `body{margin:0;min-height:100vh;background:#050508;display:grid;place-items:center;perspective:900px;overflow:hidden}.stage{width:160px;height:160px;transform-style:preserve-3d;transition:transform .1s ease-out}.cube{position:relative;width:100px;height:100px;transform-style:preserve-3d;margin:30px}.face{position:absolute;inset:0;border-radius:6px;backface-visibility:hidden;border:1px solid rgba(255,255,255,.12);display:grid;place-items:center;font-weight:800;color:#fff}.f1{background:#6c8cff;transform:translateZ(50px)}.f2{background:#ff6cb0;transform:rotateY(180deg) translateZ(50px)}.f3{background:#6cffb8;color:#111;transform:rotateY(90deg) translateZ(50px)}.f4{background:#764ba2;transform:rotateY(-90deg) translateZ(50px)}.f5{background:#f59e0b;color:#111;transform:rotateX(90deg) translateZ(50px)}.f6{background:#222;transform:rotateX(-90deg) translateZ(50px)}`,
    body: `<div class="stage" id="s"><div class="cube"><div class="face f1">1</div><div class="face f2">2</div><div class="face f3">3</div><div class="face f4">4</div><div class="face f5">5</div><div class="face f6">6</div></div></div>`,
    script: `const s=document.getElementById('s');addEventListener('mousemove',e=>{const x=(e.clientX/innerWidth-.5)*80;const y=-(e.clientY/innerHeight-.5)*60;const z=Math.hypot(x,y)*.3;s.style.transform='rotateX('+y+'deg) rotateY('+x+'deg) translateZ('+z+'px)';});` },

  { slug: '3d-mouse-card-lift', title: '3D Card Lift to Cursor', category: '3d-mouse', tags: ['3d', 'mouse', 'card', 'lift'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#111;perspective:1000px;padding:2rem}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;max-width:420px;transform-style:preserve-3d}.card{aspect-ratio:1;border-radius:14px;background:linear-gradient(135deg,#1a1a2e,#2a2a40);border:1px solid rgba(255,255,255,.08);display:grid;place-items:center;color:#fff;font-weight:700;transition:transform .2s cubic-bezier(.22,.61,.36,1),box-shadow .2s;cursor:default}`,
    body: `<div class="grid" id="g">${Array.from({length:9},(_,i)=>`<div class="card" data-i="${i}">${i+1}</div>`).join('')}</div>`,
    script: `const cards=[...document.querySelectorAll('.card')];addEventListener('mousemove',e=>{cards.forEach(c=>{const r=c.getBoundingClientRect();const cx=r.left+r.width/2,cy=r.top+r.height/2;const dx=e.clientX-cx,dy=e.clientY-cy;const d=Math.hypot(dx,dy);const lift=Math.max(0,180-d)/180;c.style.transform='translateZ('+(lift*50)+'px) rotateX('+(-dy*.04)+'deg) rotateY('+(dx*.04)+'deg)';c.style.boxShadow='0 '+(lift*20)+'px '+(lift*40)+'px rgba(108,140,255,'+(lift*.3)+')';});});` },

  { slug: '3d-mouse-grid-wave', title: '3D Grid Mouse Wave', category: '3d-mouse', tags: ['3d', 'mouse', 'grid', 'wave'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#0a0a0c;perspective:800px;padding:2rem}.grid{display:grid;grid-template-columns:repeat(6,36px);gap:6px;transform:rotateX(55deg) rotateZ(-45deg);transform-style:preserve-3d}.cell{width:36px;height:36px;border-radius:6px;background:linear-gradient(135deg,#6c8cff,#764ba2);transition:transform .25s cubic-bezier(.22,.61,.36,1)}`,
    body: `<div class="grid" id="g">${Array.from({length:36},()=>'<div class="cell"></div>').join('')}</div>`,
    script: `const cells=[...document.querySelectorAll('.cell')];addEventListener('mousemove',e=>{cells.forEach(c=>{const r=c.getBoundingClientRect();const d=Math.hypot(e.clientX-(r.left+r.width/2),e.clientY-(r.top+r.height/2));const h=Math.max(0,120-d)/120;c.style.transform='translateZ('+(h*35)+'px)';});});` },

  { slug: '3d-mouse-image-depth', title: '3D Image Mouse Depth', category: '3d-mouse', tags: ['3d', 'mouse', 'image', 'depth'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#000;perspective:1000px;padding:2rem}.frame{position:relative;width:min(360px,90vw);aspect-ratio:16/10;border-radius:16px;transform-style:preserve-3d;transition:transform .1s ease-out;overflow:hidden}.layer{position:absolute;inset:0}.layer img{width:100%;height:100%;object-fit:cover}.layer--fg{transform:translateZ(40px);mix-blend-mode:screen;opacity:.3}`,
    body: `<div class="frame" id="f"><div class="layer"><img src="${IMG}" alt=""></div><div class="layer layer--fg"><img src="${IMG}" alt=""></div></div>`,
    script: tiltLocal('#f', 20) },

  { slug: '3d-mouse-magnetic-cube', title: '3D Magnetic Cube', category: '3d-mouse', tags: ['3d', 'mouse', 'magnetic', 'cube'],
    style: `body{margin:0;min-height:100vh;background:#111;display:grid;place-items:center;perspective:900px;overflow:hidden}.wrap{transform-style:preserve-3d;transition:transform .15s ease-out}.cube{position:relative;width:90px;height:90px;transform-style:preserve-3d}.face{position:absolute;inset:0;background:#6c8cff;border:1px solid rgba(255,255,255,.2)}.f1{transform:translateZ(45px)}.f2{transform:rotateY(180deg) translateZ(45px);background:#ff6cb0}.f3{transform:rotateY(90deg) translateZ(45px);background:#6cffb8}.f4{transform:rotateY(-90deg) translateZ(45px);background:#764ba2}`,
    body: `<div class="wrap" id="w"><div class="cube"><div class="face f1"></div><div class="face f2"></div><div class="face f3"></div><div class="face f4"></div></div></div>`,
    script: `const w=document.getElementById('w');let cx=0,cy=0,tx=0,ty=0;addEventListener('mousemove',e=>{tx=(e.clientX/innerWidth-.5)*120;ty=-(e.clientY/innerHeight-.5)*80;});function tick(){cx+=(tx-cx)*.08;cy+=(ty-cy)*.08;w.style.transform='translate('+cx*.4+'px,'+cy*.4+'px) rotateX('+cy+'deg) rotateY('+cx+'deg)';requestAnimationFrame(tick);}tick();` },

  { slug: '3d-mouse-layer-parallax', title: '3D Layer Mouse Parallax', category: '3d-mouse', tags: ['3d', 'mouse', 'parallax', 'layers'],
    style: `body{margin:0;min-height:100vh;background:#0d0d0f;overflow:hidden;perspective:1200px}.scene{position:relative;height:100vh;transform-style:preserve-3d}.layer{position:absolute;inset:0;display:grid;place-items:center;will-change:transform}.layer--back img{width:120%;height:120%;object-fit:cover;opacity:.4}.layer--mid{font-size:clamp(4rem,15vw,10rem);font-weight:900;color:rgba(108,140,255,.15)}.layer--front{color:#fff;text-align:center}h1{font-size:clamp(2rem,5vw,3rem);font-weight:800}`,
    body: `<div class="scene" id="s"><div class="layer layer--back" data-z="20"><img src="${IMG}" alt=""></div><div class="layer layer--mid" data-z="50">3D</div><div class="layer layer--front" data-z="80"><h1>Parallax depth</h1></div></div>`,
    script: `const layers=[...document.querySelectorAll('.layer')];addEventListener('mousemove',e=>{const x=(e.clientX/innerWidth-.5)*2,y=(e.clientY/innerHeight-.5)*2;layers.forEach(l=>{const z=+(l.dataset.z||0);l.style.transform='translateX('+(x*z)+'px) translateY('+(y*z)+'px) translateZ('+z+'px)';});});` },

  { slug: '3d-mouse-carousel-tilt', title: '3D Carousel Mouse Tilt', category: '3d-mouse', tags: ['3d', 'mouse', 'carousel'],
    style: `body{margin:0;min-height:100vh;background:#0a0a0c;display:grid;place-items:center;perspective:1000px;overflow:hidden}.ring{position:relative;width:200px;height:200px;transform-style:preserve-3d;transition:transform .12s ease-out}.item{position:absolute;left:50%;top:50%;width:100px;height:130px;margin:-65px 0 0 -50px;border-radius:12px;overflow:hidden;box-shadow:0 12px 30px rgba(0,0,0,.5)}.item img{width:100%;height:100%;object-fit:cover}`,
    body: `<div class="ring" id="r">${Array.from({length:6},(_,i)=>`<div class="item" style="transform:rotateY(${i*60}deg) translateZ(160px)"><img src="${IMG45}" alt=""></div>`).join('')}</div>`,
    script: `const r=document.getElementById('r');addEventListener('mousemove',e=>{const x=(e.clientX/innerWidth-.5)*50;const y=-(e.clientY/innerHeight-.5)*30;const rot=(e.clientX/innerWidth)*360;r.style.transform='rotateX('+y+'deg) rotateY('+(x+rot*.2)+'deg)';});` },

  { slug: '3d-mouse-text-letters', title: '3D Letter Mouse Depth', category: '3d-mouse', tags: ['3d', 'mouse', 'text', 'letters'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#000;perspective:800px}h1{font-size:clamp(2.5rem,8vw,5rem);font-weight:900;color:#fff;display:flex;gap:6px;transform-style:preserve-3d}.ch{display:inline-block;transition:transform .2s cubic-bezier(.22,.61,.36,1)}`,
    body: `<h1 id="h">${'MOUSE'.split('').map(c=>`<span class="ch">${c}</span>`).join('')}</h1>`,
    script: `const chs=[...document.querySelectorAll('.ch')];addEventListener('mousemove',e=>{chs.forEach(ch=>{const r=ch.getBoundingClientRect();const dx=e.clientX-(r.left+r.width/2),dy=e.clientY-(r.top+r.height/2);const d=Math.hypot(dx,dy);const z=Math.max(0,150-d)/150;ch.style.transform='translateZ('+(z*60)+'px) rotateX('+(-dy*.08)+'deg) rotateY('+(dx*.08)+'deg)';});});` },

  { slug: '3d-mouse-panel-fan', title: '3D Panel Mouse Fan', category: '3d-mouse', tags: ['3d', 'mouse', 'fan', 'panels'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#fafafa;perspective:900px;padding:2rem}.fan{display:flex;gap:0;transform-style:preserve-3d}.panel{width:70px;height:200px;border-radius:10px;background:linear-gradient(180deg,var(--c),color-mix(in srgb,var(--c),#000 25%));margin:0 -8px;transition:transform .3s cubic-bezier(.22,.61,.36,1);display:grid;place-items:center;color:#fff;font-weight:800;font-size:.85rem;box-shadow:0 8px 24px rgba(0,0,0,.12)}`,
    body: `<div class="fan" id="f">${['#6c8cff','#7a7fff','#8a6cff','#9a5cff','#aa4cff','#ba3cff','#ca2cff'].map((c,i)=>`<div class="panel" style="--c:${c}" data-i="${i}">${i+1}</div>`).join('')}</div>`,
    script: `const panels=[...document.querySelectorAll('.panel')];addEventListener('mousemove',e=>{const x=(e.clientX/innerWidth-.5)*2;panels.forEach((p,i)=>{const o=i-(panels.length-1)/2;p.style.transform='rotateY('+(o*x*18)+'deg) translateZ('+(Math.abs(o)*8)+'px)';});});` },

  { slug: '3d-mouse-cube-explode', title: '3D Cube Explode Mouse', category: '3d-mouse', tags: ['3d', 'mouse', 'cube', 'explode'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#050508;perspective:900px}.wrap{position:relative;width:120px;height:120px;transform-style:preserve-3d}.face{position:absolute;width:56px;height:56px;border-radius:8px;display:grid;place-items:center;font-weight:800;color:#fff;transition:transform .35s cubic-bezier(.22,.61,.36,1)}.f1{background:#6c8cff;top:0;left:32px}.f2{background:#ff6cb0;top:32px;right:0}.f3{background:#6cffb8;color:#111;bottom:0;left:32px}.f4{background:#764ba2;top:32px;left:0}.f5{background:#f59e0b;color:#111;top:32px;left:32px}`,
    body: `<div class="wrap" id="w"><div class="face f1">N</div><div class="face f2">E</div><div class="face f3">S</div><div class="face f4">W</div><div class="face f5">C</div></div>`,
    script: `const faces=[...document.querySelectorAll('.face')],w=document.getElementById('w');addEventListener('mousemove',e=>{const r=w.getBoundingClientRect();const dx=(e.clientX-(r.left+r.width/2))/r.width;const dy=(e.clientY-(r.top+r.height/2))/r.height;const spread=Math.min(1,Math.hypot(dx,dy)*2);faces[0].style.transform='translateY('+(-spread*40)+'px) translateZ('+(spread*30)+'px)';faces[1].style.transform='translateX('+(spread*40)+'px) translateZ('+(spread*30)+'px)';faces[2].style.transform='translateY('+(spread*40)+'px) translateZ('+(spread*30)+'px)';faces[3].style.transform='translateX('+(-spread*40)+'px) translateZ('+(spread*30)+'px)';faces[4].style.transform='translateZ('+(spread*50)+'px) scale('+(1+spread*.2)+')';});` },

  { slug: '3d-mouse-tile-ripple', title: '3D Tile Ripple Mouse', category: '3d-mouse', tags: ['3d', 'mouse', 'ripple', 'tiles'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#111;perspective:700px;padding:2rem}.grid{display:grid;grid-template-columns:repeat(8,28px);gap:4px;transform:rotateX(45deg);transform-style:preserve-3d}.tile{width:28px;height:28px;border-radius:4px;background:#6c8cff;transition:transform .3s cubic-bezier(.22,.61,.36,1)}`,
    body: `<div class="grid">${Array.from({length:64},()=>'<div class="tile"></div>').join('')}</div>`,
    script: `const tiles=[...document.querySelectorAll('.tile')];let mx=0,my=0;addEventListener('mousemove',e=>{mx=e.clientX;my=e.clientY;tiles.forEach(t=>{const r=t.getBoundingClientRect();const d=Math.hypot(mx-(r.left+r.width/2),my-(r.top+r.height/2));const h=Math.max(0,1-d/100);t.style.transform='translateZ('+(h*40)+'px)';t.style.background=h>.5?'#ff6cb0':'#6c8cff';});});` },

  { slug: '3d-mouse-anchor-rotate', title: '3D Anchor Rotate Scene', category: '3d-mouse', tags: ['3d', 'mouse', 'anchor', 'rotate'],
    style: `body{margin:0;min-height:100vh;background:radial-gradient(circle at center,#1a1a2e,#050508);perspective:1000px;overflow:hidden}.scene{position:fixed;inset:0;display:grid;place-items:center;transform-style:preserve-3d;transition:transform .08s ease-out}.box{width:min(300px,80vw);padding:2.5rem;border-radius:20px;background:rgba(255,255,255,.05);border:1px solid rgba(255,255,255,.1);color:#fff;text-align:center;backdrop-filter:blur(8px)}h2{font-size:1.5rem;font-weight:800;margin-bottom:.5rem}p{color:#888;font-size:.9rem}`,
    body: `<div class="scene" id="s"><div class="box"><h2>Anchor rotate</h2><p>Scene pivots around your cursor</p></div></div>`,
    script: `const s=document.getElementById('s');addEventListener('mousemove',e=>{const x=(e.clientX/innerWidth-.5)*40;const y=-(e.clientY/innerHeight-.5)*30;s.style.transform='rotateX('+y+'deg) rotateY('+x+'deg)';s.style.transformOrigin=e.clientX+'px '+e.clientY+'px';});` },

  { slug: '3d-mouse-stack-shift', title: '3D Stack Mouse Shift', category: '3d-mouse', tags: ['3d', 'mouse', 'stack'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#0d0d0f;perspective:900px}.stack{position:relative;width:220px;height:280px;transform-style:preserve-3d}.card{position:absolute;inset:0;border-radius:14px;overflow:hidden;transition:transform .35s cubic-bezier(.22,.61,.36,1);box-shadow:0 16px 40px rgba(0,0,0,.4)}.card img{width:100%;height:100%;object-fit:cover}`,
    body: `<div class="stack" id="s">${Array.from({length:4},()=>'<div class="card"><img src="'+IMG45+'" alt=""></div>').join('')}</div>`,
    script: `const cards=[...document.querySelectorAll('.card')];addEventListener('mousemove',e=>{const x=(e.clientX/innerWidth-.5)*2,y=(e.clientY/innerHeight-.5)*2;cards.forEach((c,i)=>{c.style.transform='translateX('+(x*i*18)+'px) translateY('+(y*i*12)+'px) translateZ('+(-i*25+x*20)+'px) rotateY('+(x*8)+'deg) rotateX('+(-y*8)+'deg)';c.style.zIndex=i;});});` },

  { slug: '3d-mouse-product-box', title: '3D Product Box Mouse', category: '3d-mouse', tags: ['3d', 'mouse', 'product'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#f5f5f5;perspective:1000px;padding:2rem}.box{position:relative;width:200px;height:200px;transform-style:preserve-3d;transition:transform .12s ease-out}.side{position:absolute;display:grid;place-items:center;backface-visibility:hidden;border:1px solid rgba(0,0,0,.08)}.side img{width:100%;height:100%;object-fit:cover}.front{width:200px;height:200px;transform:translateZ(100px)}.back{width:200px;height:200px;transform:rotateY(180deg) translateZ(100px)}.right{width:200px;height:200px;transform:rotateY(90deg) translateZ(100px)}.left{width:200px;height:200px;transform:rotateY(-90deg) translateZ(100px)}.top{width:200px;height:200px;background:#fff;transform:rotateX(90deg) translateZ(100px)}.bottom{width:200px;height:200px;background:#eee;transform:rotateX(-90deg) translateZ(100px)}`,
    body: `<div class="box" id="b"><div class="side front"><img src="${IMG45}" alt=""></div><div class="side back"><img src="${IMG45}" alt="" style="filter:hue-rotate(180deg)"></div><div class="side right"><img src="${IMG45}" alt="" style="filter:hue-rotate(90deg)"></div><div class="side left"><img src="${IMG45}" alt="" style="filter:hue-rotate(270deg)"></div><div class="side top"></div><div class="side bottom"></div></div>`,
    script: tiltLocal('#b', 24) },

  { slug: '3d-mouse-bento-tilt', title: '3D Bento Mouse Tilt', category: '3d-mouse', tags: ['3d', 'mouse', 'bento'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#0a0a0c;perspective:900px;padding:2rem}.bento{display:grid;grid-template-columns:repeat(3,100px);grid-template-rows:repeat(2,100px);gap:10px;transform-style:preserve-3d}.cell{border-radius:12px;background:linear-gradient(135deg,#1a1a2e,#2a2a40);border:1px solid rgba(255,255,255,.08);display:grid;place-items:center;color:#fff;font-weight:700;transition:transform .25s cubic-bezier(.22,.61,.36,1)}.cell:nth-child(1){grid-column:span 2}`,
    body: `<div class="bento" id="b">${['Hero','A','B','C','D','E'].map(t=>`<div class="cell">${t}</div>`).join('')}</div>`,
    script: `const cells=[...document.querySelectorAll('.cell')];const b=document.getElementById('b');b.addEventListener('mousemove',e=>{const r=b.getBoundingClientRect();const x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;cells.forEach((c,i)=>{const cr=c.getBoundingClientRect();const dx=(e.clientX-(cr.left+cr.width/2))/r.width;const dy=(e.clientY-(cr.top+cr.height/2))/r.height;c.style.transform='rotateY('+(dx*25)+'deg) rotateX('+(-dy*25)+'deg) translateZ('+(20-i*2)+'px)';});});b.addEventListener('mouseleave',()=>cells.forEach(c=>c.style.transform=''));` },

  { slug: '3d-mouse-floating-ui', title: '3D Floating UI Panel', category: '3d-mouse', tags: ['3d', 'mouse', 'ui', 'float'],
    style: `body{margin:0;min-height:100vh;background:linear-gradient(180deg,#0d0d0f,#1a1a2e);display:grid;place-items:center;perspective:1000px;padding:2rem}.panel{width:min(320px,90vw);padding:2rem;border-radius:20px;background:rgba(26,26,46,.9);border:1px solid rgba(108,140,255,.2);color:#fff;box-shadow:0 24px 60px rgba(0,0,0,.4);transition:transform .12s ease-out;transform-style:preserve-3d}h3{font-size:1.2rem;margin-bottom:.5rem;transform:translateZ(30px)}p{color:#888;font-size:.9rem;transform:translateZ(15px)}.chip{display:inline-block;margin-top:1rem;padding:6px 14px;border-radius:99px;background:#6c8cff;font-size:.75rem;font-weight:700;transform:translateZ(40px)}`,
    body: `<div class="panel" id="p"><h3>Floating panel</h3><p>Tilts and floats toward your cursor in 3D space.</p><span class="chip">Interactive</span></div>`,
    script: tiltLocal('#p', 16) },

  { slug: '3d-mouse-diamond-tilt', title: '3D Diamond Mouse Tilt', category: '3d-mouse', tags: ['3d', 'mouse', 'diamond'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#000;perspective:800px}.diamond{width:100px;height:100px;background:linear-gradient(135deg,#6c8cff,#ff6cb0);transform:rotate(45deg);transition:transform .15s ease-out;box-shadow:0 20px 50px rgba(108,140,255,.4)}`,
    body: `<div class="diamond" id="d"></div>`,
    script: `const d=document.getElementById('d');addEventListener('mousemove',e=>{const x=(e.clientX/innerWidth-.5)*50,y=-(e.clientY/innerHeight-.5)*50;d.style.transform='rotate(45deg) rotateX('+y+'deg) rotateY('+x+'deg) translateZ(20px)';});` },

  { slug: '3d-mouse-gallery-shift', title: '3D Gallery Mouse Shift', category: '3d-mouse', tags: ['3d', 'mouse', 'gallery'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#111;perspective:1200px;padding:2rem;overflow:hidden}.row{display:flex;gap:20px;transform-style:preserve-3d;transition:transform .15s ease-out}.frame{width:min(140px,22vw);aspect-ratio:4/5;border-radius:12px;overflow:hidden;box-shadow:0 16px 40px rgba(0,0,0,.5)}.frame img{width:100%;height:100%;object-fit:cover}`,
    body: `<div class="row" id="r">${Array.from({length:5},()=>'<div class="frame"><img src="'+IMG45+'" alt=""></div>').join('')}</div>`,
    script: `const r=document.getElementById('r'),frames=[...r.children];addEventListener('mousemove',e=>{const x=(e.clientX/innerWidth-.5)*2,y=(e.clientY/innerHeight-.5)*2;r.style.transform='rotateY('+x*12+'deg) rotateX('+(-y*8)+'deg)';frames.forEach((f,i)=>{const o=i-2;f.style.transform='translateZ('+(Math.abs(o)*-20+Math.abs(x)*15)+'px) rotateY('+(o*x*5)+'deg)';});});` },

  { slug: '3d-mouse-typography-block', title: '3D Typography Mouse Block', category: '3d-mouse', tags: ['3d', 'mouse', 'typography'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#fafafa;perspective:900px;padding:2rem}.block{padding:2.5rem 3rem;border-radius:16px;background:#fff;box-shadow:0 20px 60px rgba(0,0,0,.08);transition:transform .12s ease-out;transform-style:preserve-3d}h1{font-size:2.5rem;font-weight:900;color:#111;transform:translateZ(35px)}p{margin-top:.5rem;color:#666;transform:translateZ(18px)}`,
    body: `<div class="block" id="b"><h1>TYPE 3D</h1><p>Move mouse to tilt</p></div>`,
    script: tiltLocal('#b', 14) },

  { slug: '3d-mouse-orbit-ring', title: '3D Orbit Ring Mouse', category: '3d-mouse', tags: ['3d', 'mouse', 'orbit'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#050508;perspective:900px}.orbit{position:relative;width:240px;height:240px;transform-style:preserve-3d;transition:transform .12s ease-out}.dot{position:absolute;width:14px;height:14px;border-radius:50%;background:#6c8cff;box-shadow:0 0 16px #6c8cff;top:50%;left:50%;margin:-7px}`,
    body: `<div class="orbit" id="o">${Array.from({length:12},(_,i)=>`<div class="dot" style="transform:rotateY(${i*30}deg) translateZ(100px)"></div>`).join('')}</div>`,
    script: `const o=document.getElementById('o');addEventListener('mousemove',e=>{const x=(e.clientX/innerWidth-.5)*60,y=-(e.clientY/innerHeight-.5)*40;o.style.transform='rotateX('+y+'deg) rotateY('+x+'deg)';});` },

  { slug: '3d-mouse-icon-cloud', title: '3D Icon Cloud Mouse', category: '3d-mouse', tags: ['3d', 'mouse', 'icons'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#0d0d0f;perspective:800px;padding:2rem}.cloud{position:relative;width:min(400px,90vw);height:min(300px,60vh);transform-style:preserve-3d}.icon{position:absolute;width:48px;height:48px;border-radius:12px;background:linear-gradient(135deg,#6c8cff,#764ba2);display:grid;place-items:center;color:#fff;font-weight:800;font-size:.85rem;transition:transform .3s cubic-bezier(.22,.61,.36,1);box-shadow:0 8px 24px rgba(0,0,0,.3)}`,
    body: `<div class="cloud" id="c">${['UI','UX','3D','CSS','JS','AI','WEB','APP','DEV','ART'].map((t,i)=>`<div class="icon" style="left:${10+(i%5)*18}%;top:${15+Math.floor(i/5)*40}%">${t}</div>`).join('')}</div>`,
    script: `const icons=[...document.querySelectorAll('.icon')];addEventListener('mousemove',e=>{icons.forEach(ic=>{const r=ic.getBoundingClientRect();const d=Math.hypot(e.clientX-(r.left+r.width/2),e.clientY-(r.top+r.height/2));const lift=Math.max(0,140-d)/140;ic.style.transform='translateZ('+(lift*45)+'px) scale('+(1+lift*.15)+')';});});` },

  { slug: '3d-mouse-button-tilt', title: '3D Button Mouse Tilt', category: '3d-mouse', tags: ['3d', 'mouse', 'button'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#111;perspective:600px}.btn{padding:18px 48px;border:none;border-radius:12px;background:linear-gradient(135deg,#6c8cff,#4a5fd4);color:#fff;font-weight:700;font-size:1rem;cursor:pointer;box-shadow:0 8px 0 #3a4fc4,0 16px 32px rgba(108,140,255,.3);transition:transform .1s,box-shadow .1s;transform-style:preserve-3d}`,
    body: `<button class="btn" id="b" type="button">Tilt Me</button>`,
    script: tiltLocal('#b', 20) },

  { slug: '3d-mouse-photo-stack', title: '3D Photo Stack Mouse', category: '3d-mouse', tags: ['3d', 'mouse', 'photos'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#1a1a2e;perspective:1000px;padding:2rem}.stack{position:relative;width:200px;height:260px;transform-style:preserve-3d}.photo{position:absolute;inset:0;border-radius:12px;overflow:hidden;border:3px solid #fff;box-shadow:0 12px 36px rgba(0,0,0,.4);transition:transform .35s cubic-bezier(.22,.61,.36,1)}.photo img{width:100%;height:100%;object-fit:cover}`,
    body: `<div class="stack">${Array.from({length:5},(_,i)=>`<div class="photo" data-i="${i}"><img src="${IMG45}" alt=""></div>`).join('')}</div>`,
    script: `const photos=[...document.querySelectorAll('.photo')];addEventListener('mousemove',e=>{const x=(e.clientX/innerWidth-.5)*2;photos.forEach((p,i)=>{const spread=(i-(photos.length-1)/2)*x*25;p.style.transform='translateX('+spread+'px) rotateY('+(spread*.15)+'deg) translateZ('+(-i*12)+'px)';p.style.zIndex=i;});});` },

  { slug: '3d-mouse-tunnel-depth', title: '3D Tunnel Depth Mouse', category: '3d-mouse', tags: ['3d', 'mouse', 'tunnel'],
    style: `body{margin:0;min-height:100vh;background:#000;perspective:500px;overflow:hidden;display:grid;place-items:center}.tunnel{position:relative;width:300px;height:300px;transform-style:preserve-3d}.ring{position:absolute;inset:0;border:2px solid rgba(108,140,255,.4);border-radius:12px;transition:transform .2s ease-out}`,
    body: `<div class="tunnel" id="t">${Array.from({length:8},(_,i)=>`<div class="ring" data-i="${i}"></div>`).join('')}</div>`,
    script: `const rings=[...document.querySelectorAll('.ring')];addEventListener('mousemove',e=>{const x=(e.clientX/innerWidth-.5)*2,y=(e.clientY/innerHeight-.5)*2;rings.forEach((r,i)=>{const z=-i*40+(x+y)*30;r.style.transform='translateZ('+z+'px) scale('+(1-i*.08)+')';r.style.opacity=1-i*.1;});});` },

  { slug: '3d-mouse-hero-float', title: '3D Hero Float Mouse', category: '3d-mouse', tags: ['3d', 'mouse', 'hero'],
    style: `body{margin:0;min-height:100vh;background:linear-gradient(135deg,#0d0d0f,#1a1a2e);perspective:1200px;overflow:hidden}.hero{min-height:100vh;display:grid;grid-template-columns:1fr 1fr;align-items:center;gap:2rem;padding:4rem 6%;transform-style:preserve-3d;transition:transform .1s ease-out}h1{font-size:clamp(2rem,4vw,3.2rem);font-weight:900;color:#fff;transform:translateZ(50px)}p{color:#888;transform:translateZ(25px);margin-top:1rem}.visual{border-radius:16px;overflow:hidden;transform:translateZ(70px);box-shadow:0 30px 60px rgba(0,0,0,.5)}.visual img{width:100%;aspect-ratio:16/10;object-fit:cover}@media(max-width:768px){.hero{grid-template-columns:1fr;padding:3rem 1.5rem}}`,
    body: `<div class="hero" id="h"><div><h1>Float in 3D</h1><p>Mouse-driven depth for hero sections.</p></div><div class="visual"><img src="${IMG}" alt=""></div></div>`,
    script: tiltLocal('#h', 8) },

  { slug: '3d-mouse-prism-follow', title: '3D Prism Follow Mouse', category: '3d-mouse', tags: ['3d', 'mouse', 'prism'],
    style: `body{margin:0;min-height:100vh;background:#0a0a0c;display:grid;place-items:center;perspective:800px;overflow:hidden}.prism{position:relative;width:0;height:0;transition:transform .12s ease-out}.tri{width:0;height:0;border-left:50px solid transparent;border-right:50px solid transparent;border-bottom:86px solid #6c8cff;filter:drop-shadow(0 12px 24px rgba(108,140,255,.4))}`,
    body: `<div class="prism" id="p"><div class="tri"></div></div>`,
    script: `const p=document.getElementById('p');let px=innerWidth/2,py=innerHeight/2,cx=px,cy=py;addEventListener('mousemove',e=>{px=e.clientX;py=e.clientY;});function tick(){cx+=(px-cx)*.1;cy+=(py-cy)*.1;const rx=-(cy/innerHeight-.5)*40,ry=(cx/innerWidth-.5)*50;p.style.position='fixed';p.style.left=cx+'px';p.style.top=cy+'px';p.style.transform='translate(-50%,-50%) rotateX('+rx+'deg) rotateY('+ry+'deg)';requestAnimationFrame(tick);}tick();` },

  { slug: '3d-mouse-ring-selector', title: '3D Ring Selector Mouse', category: '3d-mouse', tags: ['3d', 'mouse', 'selector'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#111;perspective:900px}.ring{position:relative;width:280px;height:280px;transform-style:preserve-3d;transition:transform .15s ease-out}.item{position:absolute;left:50%;top:50%;width:64px;height:64px;margin:-32px;border-radius:50%;background:#1a1a2e;border:2px solid #333;color:#fff;display:grid;place-items:center;font-weight:700;font-size:.8rem;transition:background .2s,border-color .2s,transform .2s}.item.on{background:#6c8cff;border-color:#6c8cff;box-shadow:0 0 24px rgba(108,140,255,.5)}`,
    body: `<div class="ring" id="r">${['A','B','C','D','E','F'].map((l,i)=>`<div class="item" data-i="${i}" style="transform:rotateY(${i*60}deg) translateZ(120px)">${l}</div>`).join('')}</div>`,
    script: `const items=[...document.querySelectorAll('.item')],r=document.getElementById('r');addEventListener('mousemove',e=>{const x=(e.clientX/innerWidth-.5)*50,y=-(e.clientY/innerHeight-.5)*35;r.style.transform='rotateX('+y+'deg) rotateY('+x+'deg)';let best=0,bd=1e9;items.forEach(it=>{const b=it.getBoundingClientRect();const d=Math.hypot(e.clientX-(b.left+b.width/2),e.clientY-(b.top+b.height/2));if(d<bd){bd=d;best=+it.dataset.i;}});items.forEach(it=>it.classList.toggle('on',+it.dataset.i===best));});` },

  { slug: '3d-mouse-scene-warp', title: '3D Scene Warp Mouse', category: '3d-mouse', tags: ['3d', 'mouse', 'warp'],
    style: `body{margin:0;min-height:100vh;background:#000;perspective:600px;overflow:hidden}.grid{position:fixed;inset:-50%;background-image:linear-gradient(rgba(108,140,255,.15) 1px,transparent 1px),linear-gradient(90deg,rgba(108,140,255,.15) 1px,transparent 1px);background-size:50px 50px;transition:transform .1s ease-out;transform-origin:center}.label{position:relative;z-index:1;min-height:100vh;display:grid;place-items:center;color:#fff;font-size:2.5rem;font-weight:900}`,
    body: `<div class="grid" id="g"></div><div class="label">Warp</div>`,
    script: `const g=document.getElementById('g');addEventListener('mousemove',e=>{const x=(e.clientX/innerWidth-.5)*30,y=-(e.clientY/innerHeight-.5)*30;g.style.transform='perspective(600px) rotateX('+y+'deg) rotateY('+x+'deg)';});` },

  { slug: '3d-mouse-card-flip-track', title: '3D Flip Track Mouse', category: '3d-mouse', tags: ['3d', 'mouse', 'flip'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#0d0d0f;perspective:1000px;padding:2rem}.card{width:min(260px,85vw);height:160px;position:relative;transform-style:preserve-3d;transition:transform .2s ease-out}.face{position:absolute;inset:0;border-radius:14px;backface-visibility:hidden;display:grid;place-items:center;font-weight:800;color:#fff}.front{background:linear-gradient(135deg,#6c8cff,#764ba2)}.back{background:linear-gradient(135deg,#ff6cb0,#6cffb8);color:#111;transform:rotateY(180deg)}`,
    body: `<div class="card" id="c"><div class="face front">Front</div><div class="face back">Back</div></div>`,
    script: `const c=document.getElementById('c');addEventListener('mousemove',e=>{const x=(e.clientX/innerWidth-.5)*120;const y=-(e.clientY/innerHeight-.5)*60;c.style.transform='rotateY('+x+'deg) rotateX('+y+'deg)';});` },

  { slug: '3d-mouse-sphere-dots', title: '3D Sphere Dots Mouse', category: '3d-mouse', tags: ['3d', 'mouse', 'sphere', 'canvas'],
    style: `body{margin:0;min-height:100vh;background:#050508;overflow:hidden}canvas{display:block}`,
    body: `<canvas id="c"></canvas>`,
    script: `const cv=document.getElementById('c'),x=cv.getContext('2d');let mx=0,my=0,rx=0,ry=0;const pts=[];for(let i=0;i<80;i++){const t=Math.acos(1-2*Math.random()),p=Math.random()*Math.PI*2;pts.push({x:Math.sin(t)*Math.cos(p),y:Math.sin(t)*Math.sin(p),z:Math.cos(t)});}function r(){cv.width=innerWidth;cv.height=innerHeight;}r();addEventListener('resize',r);addEventListener('mousemove',e=>{mx=(e.clientX/innerWidth-.5)*2;my=(e.clientY/innerHeight-.5)*2;});function d(){x.fillStyle='#050508';x.fillRect(0,0,cv.width,cv.height);rx+=(my*.6-rx)*.08;ry+=(mx*.8-ry)*.08;const cx=cv.width/2,cy=cv.height/2;const proj=pts.map(p=>{let{x:px,y:py,z:pz}=p;const cos=Math.cos(ry),sin=Math.sin(ry);let nx=px*cos-pz*sin,nz=px*sin+pz*cos;const cosy=Math.cos(rx),siny=Math.sin(rx);let ny=py*cosy-nz*siny,nz2=py*siny+nz*cosy;const s=180/(nz2+2.5);return{x:cx+nx*s,y:cy+ny*s,z:nz2,s};}).sort((a,b)=>a.z-b.z);proj.forEach(p=>{x.fillStyle='hsla(220,80%,65%,'+(0.3+p.s/300)+')';x.beginPath();x.arc(p.x,p.y,Math.max(1.5,p.s/15),0,Math.PI*2);x.fill();});requestAnimationFrame(d);}d();` },

  { slug: '3d-mouse-layers-shift', title: '3D Layers Shift Mouse', category: '3d-mouse', tags: ['3d', 'mouse', 'layers'],
    style: `body{margin:0;min-height:100vh;background:#111;perspective:1000px;overflow:hidden}.wrap{position:relative;height:100vh;display:grid;place-items:center}.layer{position:absolute;border-radius:16px;transition:transform .2s cubic-bezier(.22,.61,.36,1)}.l1{width:min(340px,85vw);height:200px;background:linear-gradient(135deg,#6c8cff44,#764ba244);border:1px solid rgba(108,140,255,.3)}.l2{width:min(300px,75vw);height:170px;background:linear-gradient(135deg,#ff6cb044,#d44a8a44);border:1px solid rgba(255,108,176,.3)}.l3{width:min(260px,65vw);height:140px;background:linear-gradient(135deg,#6cffb844,#3ad4a044);border:1px solid rgba(108,255,184,.3);display:grid;place-items:center;color:#fff;font-weight:800}`,
    body: `<div class="wrap" id="w"><div class="layer l1"></div><div class="layer l2"></div><div class="layer l3">Shift</div></div>`,
    script: `const layers=[...document.querySelectorAll('.layer')];addEventListener('mousemove',e=>{const x=(e.clientX/innerWidth-.5)*2,y=(e.clientY/innerHeight-.5)*2;layers.forEach((l,i)=>{l.style.transform='translateX('+(x*(i+1)*20)+'px) translateY('+(y*(i+1)*15)+'px) translateZ('+((i+1)*30)+'px) rotateX('+(-y*5)+'deg) rotateY('+(x*5)+'deg)';});});` },

  { slug: '3d-mouse-interactive-globe', title: '3D Interactive Globe Mouse', category: '3d-mouse', tags: ['3d', 'mouse', 'globe'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:radial-gradient(circle at center,#0d1a2e,#020408);perspective:900px}.globe{position:relative;width:200px;height:200px;transform-style:preserve-3d;transition:transform .1s ease-out}.line{position:absolute;inset:0;border:1px solid rgba(108,140,255,.25);border-radius:50%}.line:nth-child(2){transform:rotateY(60deg)}.line:nth-child(3){transform:rotateY(120deg)}.core{position:absolute;inset:20%;border-radius:50%;background:radial-gradient(circle at 30% 30%,#6c8cff,#1a1a4e);box-shadow:0 0 40px rgba(108,140,255,.4)}`,
    body: `<div class="globe" id="g"><div class="line"></div><div class="line"></div><div class="line"></div><div class="core"></div></div>`,
    script: `const g=document.getElementById('g');let rx=-10,ry=0,trx=-10,try2=0;addEventListener('mousemove',e=>{try2=(e.clientX/innerWidth-.5)*80;trx=-(e.clientY/innerHeight-.5)*50;});function tick(){rx+=(trx-rx)*.08;ry+=(try2-ry)*.08;g.style.transform='rotateX('+rx+'deg) rotateY('+ry+'deg)';requestAnimationFrame(tick);}tick();` },
];
