const IMG = '../stock/media/16-9 Aspect Ratio(image).png';
const IMG45 = '../stock/media/4-5 Aspect Ratio(image).png';
const EASE = 'cubic-bezier(.22,.61,.36,1)';
const EASE_OUT = 'cubic-bezier(.16,1,.3,1)';

module.exports = [
  { slug: 'ease-in-hero-headline', title: 'Hero Headline Ease', category: 'ease-in', tags: ['ease-in', 'hero', 'headline', 'professional'],
    style: `body{margin:0;min-height:100vh;background:#fafafa;display:grid;place-items:center;padding:3rem 2rem;font-family:system-ui,sans-serif}.wrap{max-width:640px;text-align:center}.eyebrow{font-size:.75rem;letter-spacing:.18em;text-transform:uppercase;color:#6c8cff;font-weight:600;margin-bottom:1.25rem;opacity:0;transform:translateY(16px);animation:up .7s ${EASE} .1s forwards}h1{font-size:clamp(2.2rem,5vw,3.5rem);font-weight:700;line-height:1.12;color:#111;margin-bottom:1rem}.line{display:block;overflow:hidden}.line span{display:block;transform:translateY(110%);animation:rise .9s ${EASE} forwards}.line:nth-child(1) span{animation-delay:.2s}.line:nth-child(2) span{animation-delay:.35s}p{color:#666;font-size:1.05rem;line-height:1.6;max-width:42ch;margin:1.5rem auto 0;opacity:0;animation:fade .8s ${EASE} .55s forwards}@keyframes rise{to{transform:none}}@keyframes up{to{opacity:1;transform:none}}@keyframes fade{to{opacity:1}}@media (prefers-reduced-motion:reduce){.eyebrow,h1 span,p{opacity:1;transform:none;animation:none}}`,
    body: `<div class="wrap"><p class="eyebrow">Studio Arc</p><h1><span class="line"><span>Design with</span></span><span class="line"><span>intention</span></span></h1><p>Polished headline reveal with staggered line ease for landing pages.</p></div>` },

  { slug: 'ease-in-split-lines', title: 'Split Lines Reveal', category: 'ease-in', tags: ['ease-in', 'lines', 'reveal', 'professional'],
    style: `body{margin:0;min-height:100vh;background:#0d0d0f;color:#fff;display:grid;place-items:center;padding:2rem;font-family:system-ui,sans-serif}h1{font-size:clamp(2rem,6vw,4rem);font-weight:800;line-height:1.15}.row{overflow:hidden}.row span{display:block;transform:translateY(105%);animation:up .85s ${EASE} forwards}.row:nth-child(1) span{animation-delay:.08s}.row:nth-child(2) span{animation-delay:.2s}.row:nth-child(3) span{animation-delay:.32s}@keyframes up{to{transform:none}}@media (prefers-reduced-motion:reduce){.row span{transform:none;animation:none}}`,
    body: `<h1><span class="row"><span>Build better</span></span><span class="row"><span>experiences</span></span><span class="row"><span>with ease</span></span></h1>` },

  { slug: 'ease-in-fade-up-card', title: 'Fade Up Card Ease', category: 'ease-in', tags: ['ease-in', 'card', 'fade', 'professional'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#f4f6fb;padding:2rem;font-family:system-ui,sans-serif}.card{max-width:400px;padding:2rem 2.25rem;background:#fff;border-radius:16px;border:1px solid #e8ecf4;box-shadow:0 4px 24px rgba(15,23,42,.06);opacity:0;transform:translateY(32px);animation:up .85s ${EASE} forwards}.label{font-size:.72rem;font-weight:600;letter-spacing:.1em;text-transform:uppercase;color:#6c8cff;margin-bottom:.75rem}h3{font-size:1.35rem;font-weight:700;color:#0f172a;margin-bottom:.5rem}p{color:#64748b;font-size:.95rem;line-height:1.65}@keyframes up{to{opacity:1;transform:none}}`,
    body: `<div class="card"><div class="label">Feature</div><h3>Seamless onboarding</h3><p>Guide users from signup to first value with calm, confident motion.</p></div>` },

  { slug: 'ease-in-stagger-features', title: 'Stagger Features Grid', category: 'ease-in', tags: ['ease-in', 'stagger', 'features', 'professional'],
    style: `body{margin:0;min-height:100vh;background:#fff;padding:4rem 2rem;font-family:system-ui,sans-serif}.grid{max-width:720px;margin:0 auto;display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.item{padding:1.5rem 1.25rem;border-radius:14px;background:#fafafa;border:1px solid #eee;opacity:0;transform:translateY(24px);animation:up .7s ${EASE} forwards}.item:nth-child(1){animation-delay:.05s}.item:nth-child(2){animation-delay:.12s}.item:nth-child(3){animation-delay:.19s}.item:nth-child(4){animation-delay:.26s}.item:nth-child(5){animation-delay:.33s}.item:nth-child(6){animation-delay:.4s}.icon{width:36px;height:36px;border-radius:10px;background:linear-gradient(135deg,#6c8cff,#764ba2);margin-bottom:.75rem}h4{font-size:.9rem;font-weight:700;color:#111;margin-bottom:.25rem}p{font-size:.8rem;color:#666;line-height:1.5}@keyframes up{to{opacity:1;transform:none}}@media(max-width:600px){.grid{grid-template-columns:1fr}}`,
    body: `<div class="grid">${['Fast','Secure','Scalable','Reliable','Flexible','Modern'].map(t=>`<div class="item"><div class="icon"></div><h4>${t}</h4><p>Professional feature block with eased entrance.</p></div>`).join('')}</div>` },

  { slug: 'ease-in-image-reveal', title: 'Image Reveal Ease', category: 'ease-in', tags: ['ease-in', 'image', 'reveal', 'professional'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#111;padding:2rem}.frame{width:min(420px,90vw);border-radius:16px;overflow:hidden;position:relative}.frame img{width:100%;display:block;transform:scale(1.08);animation:zoom 1.2s ${EASE} forwards}.frame::after{content:'';position:absolute;inset:0;background:#6c8cff;transform-origin:left;animation:wipe 1s ${EASE} forwards}@keyframes wipe{to{transform:scaleX(0)}}@keyframes zoom{to{transform:scale(1)}}@media (prefers-reduced-motion:reduce){.frame::after{display:none}.frame img{transform:none;animation:none}}`,
    body: `<div class="frame"><img src="${IMG}" alt=""></div>` },

  { slug: 'ease-in-underline-draw', title: 'Underline Draw Ease', category: 'ease-in', tags: ['ease-in', 'underline', 'draw', 'professional'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#fafafa;font-family:system-ui,sans-serif;padding:2rem}h1{font-size:clamp(2rem,5vw,3rem);font-weight:700;color:#111;position:relative;display:inline-block;padding-bottom:8px}h1::after{content:'';position:absolute;left:0;bottom:0;height:3px;width:100%;background:linear-gradient(90deg,#6c8cff,#ff6cb0);transform:scaleX(0);transform-origin:left;animation:draw .9s ${EASE} .3s forwards}@keyframes draw{to{transform:scaleX(1)}}`,
    body: `<h1>Underline reveal</h1>` },

  { slug: 'ease-in-nav-items', title: 'Nav Items Stagger Ease', category: 'ease-in', tags: ['ease-in', 'nav', 'stagger', 'professional'],
    style: `body{margin:0;min-height:100vh;background:#0d0d0f;display:grid;place-items:center;font-family:system-ui,sans-serif}.nav{display:flex;gap:2rem}.link{color:#888;text-decoration:none;font-size:.95rem;font-weight:500;opacity:0;transform:translateY(-12px);animation:down .6s ${EASE} forwards}.link:nth-child(1){animation-delay:.1s}.link:nth-child(2){animation-delay:.18s}.link:nth-child(3){animation-delay:.26s}.link:nth-child(4){animation-delay:.34s}.link:nth-child(5){animation-delay:.42s}.link:hover{color:#fff}@keyframes down{to{opacity:1;transform:none}}`,
    body: `<nav class="nav">${['Work','Studio','Services','Journal','Contact'].map(t=>`<a class="link" href="#">${t}</a>`).join('')}</nav>` },

  { slug: 'ease-in-stat-counters', title: 'Stat Counter Ease', category: 'ease-in', tags: ['ease-in', 'stats', 'counter', 'professional'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#fff;padding:2rem;font-family:system-ui,sans-serif}.stats{display:flex;gap:clamp(2rem,6vw,4rem)}.stat{text-align:center;opacity:0;transform:translateY(20px);animation:up .75s ${EASE} forwards}.stat:nth-child(1){animation-delay:.1s}.stat:nth-child(2){animation-delay:.22s}.stat:nth-child(3){animation-delay:.34s}.num{font-size:2.5rem;font-weight:800;color:#111;font-variant-numeric:tabular-nums}.label{font-size:.8rem;color:#888;margin-top:.25rem;text-transform:uppercase;letter-spacing:.08em}@keyframes up{to{opacity:1;transform:none}}`,
    body: `<div class="stats"><div class="stat"><div class="num" data-v="98">0</div><div class="label">Satisfaction</div></div><div class="stat"><div class="num" data-v="240">0</div><div class="label">Projects</div></div><div class="stat"><div class="num" data-v="12">0</div><div class="label">Years</div></div></div>`,
    script: `document.querySelectorAll('.num').forEach((el,i)=>{const target=+el.dataset.v;setTimeout(()=>{const t0=performance.now();(function tick(now){const p=Math.min((now-t0)/1200,1);const ease=1-Math.pow(1-p,3);el.textContent=Math.round(ease*target)+(target===98?'%':'');if(p<1)requestAnimationFrame(tick);else el.textContent=target+(target===98?'%':'');})(t0);},200+i*120);});` },

  { slug: 'ease-in-testimonial-card', title: 'Testimonial Card Ease', category: 'ease-in', tags: ['ease-in', 'testimonial', 'card', 'professional'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#f8fafc;padding:2rem;font-family:system-ui,sans-serif}.card{max-width:440px;padding:2rem 2.25rem;background:#fff;border-radius:20px;border:1px solid #e2e8f0;box-shadow:0 8px 32px rgba(15,23,42,.05);opacity:0;transform:translateY(28px) scale(.98);animation:up .9s ${EASE} forwards}blockquote{font-size:1.1rem;line-height:1.65;color:#334155;font-style:italic;margin-bottom:1.25rem}.author{display:flex;align-items:center;gap:12px;opacity:0;animation:fade .6s ${EASE} .5s forwards}.avatar{width:40px;height:40px;border-radius:50%;background:linear-gradient(135deg,#6c8cff,#764ba2)}.name{font-size:.9rem;font-weight:600;color:#111}.role{font-size:.78rem;color:#888}@keyframes up{to{opacity:1;transform:none}}@keyframes fade{to{opacity:1}}`,
    body: `<div class="card"><blockquote>"The motion design elevated our entire brand presence. Subtle, professional, and effective."</blockquote><div class="author"><div class="avatar"></div><div><div class="name">Sarah Chen</div><div class="role">Creative Director</div></div></div></div>` },

  { slug: 'ease-in-logo-mark', title: 'Logo Mark Ease', category: 'ease-in', tags: ['ease-in', 'logo', 'brand', 'professional'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#0a0a0c;font-family:system-ui,sans-serif}.brand{text-align:center}.mark{width:56px;height:56px;border-radius:14px;background:linear-gradient(135deg,#6c8cff,#764ba2);margin:0 auto 1rem;opacity:0;transform:scale(.6) rotate(-8deg);animation:mark .8s ${EASE} forwards}.name{font-size:1.25rem;font-weight:700;color:#fff;opacity:0;letter-spacing:.02em;animation:fade .6s ${EASE} .35s forwards}.tag{font-size:.8rem;color:#666;margin-top:.35rem;opacity:0;animation:fade .6s ${EASE} .5s forwards}@keyframes mark{to{opacity:1;transform:none}}@keyframes fade{to{opacity:1}}`,
    body: `<div class="brand"><div class="mark"></div><div class="name">Arc Studio</div><p class="tag">Brand identity</p></div>` },

  { slug: 'ease-in-form-fields', title: 'Form Fields Stagger Ease', category: 'ease-in', tags: ['ease-in', 'form', 'stagger', 'professional'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#fafafa;padding:2rem;font-family:system-ui,sans-serif}.form{width:min(360px,100%)}.field{margin-bottom:14px;opacity:0;transform:translateX(-16px);animation:slide .65s ${EASE} forwards}.field:nth-child(1){animation-delay:.08s}.field:nth-child(2){animation-delay:.16s}.field:nth-child(3){animation-delay:.24s}.field:nth-child(4){animation-delay:.32s}label{display:block;font-size:.78rem;font-weight:600;color:#555;margin-bottom:6px}input,textarea{width:100%;padding:11px 14px;border:1px solid #ddd;border-radius:10px;font:inherit;font-size:.9rem;background:#fff}textarea{min-height:80px;resize:vertical}.btn{width:100%;padding:12px;border:none;border-radius:10px;background:#111;color:#fff;font-weight:600;font-size:.9rem;margin-top:6px;opacity:0;animation:slide .65s ${EASE} .4s forwards}@keyframes slide{to{opacity:1;transform:none}}`,
    body: `<form class="form"><div class="field"><label>Name</label><input type="text" placeholder="Your name"></div><div class="field"><label>Email</label><input type="email" placeholder="you@company.com"></div><div class="field"><label>Message</label><textarea placeholder="How can we help?"></textarea></div><button class="btn" type="button">Send message</button></form>` },

  { slug: 'ease-in-badge-row', title: 'Badge Row Stagger Ease', category: 'ease-in', tags: ['ease-in', 'badges', 'stagger', 'professional'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#fff;padding:2rem;font-family:system-ui,sans-serif}.row{display:flex;flex-wrap:wrap;gap:10px;justify-content:center;max-width:480px}.badge{padding:8px 16px;border-radius:99px;font-size:.8rem;font-weight:600;background:#f1f5f9;color:#475569;opacity:0;transform:scale(.85);animation:pop .55s ${EASE} forwards}.badge:nth-child(1){animation-delay:.04s}.badge:nth-child(2){animation-delay:.1s}.badge:nth-child(3){animation-delay:.16s}.badge:nth-child(4){animation-delay:.22s}.badge:nth-child(5){animation-delay:.28s}.badge:nth-child(6){animation-delay:.34s}@keyframes pop{to{opacity:1;transform:none}}`,
    body: `<div class="row">${['Design','Development','Strategy','Branding','Motion','UX Research'].map(t=>`<span class="badge">${t}</span>`).join('')}</div>` },

  { slug: 'ease-in-clip-slide-reveal', title: 'Clip Slide Reveal Ease', category: 'ease-in', tags: ['ease-in', 'clip', 'slide', 'professional'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#eee;padding:2rem}.panel{width:min(360px,90vw);padding:2.5rem;border-radius:16px;background:linear-gradient(135deg,#1e293b,#334155);color:#fff;clip-path:inset(0 100% 0 0);animation:clip 1s ${EASE} forwards}h2{font-size:1.5rem;font-weight:700;margin-bottom:.5rem}p{opacity:.8;font-size:.95rem;line-height:1.6}@keyframes clip{to{clip-path:inset(0 0 0 0)}}`,
    body: `<div class="panel"><h2>Clip reveal</h2><p>Horizontal clip-path slide with smooth professional easing.</p></div>` },

  { slug: 'ease-in-blur-fade-in', title: 'Blur Fade In Ease', category: 'ease-in', tags: ['ease-in', 'blur', 'fade', 'professional'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#0d0d0f;color:#fff;font-family:system-ui,sans-serif;padding:2rem;text-align:center}h1{font-size:clamp(2rem,5vw,3.2rem);font-weight:800;opacity:0;filter:blur(16px);animation:clear 1s ${EASE} forwards}p{margin-top:1rem;color:#888;font-size:1rem;opacity:0;filter:blur(8px);animation:clear .8s ${EASE} .3s forwards}@keyframes clear{to{opacity:1;filter:blur(0)}}`,
    body: `<div><h1>Focus in</h1><p>From blur to sharp with refined ease-out.</p></div>` },

  { slug: 'ease-in-scale-fade-grid', title: 'Scale Fade Grid Ease', category: 'ease-in', tags: ['ease-in', 'grid', 'scale', 'professional'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#fafafa;padding:2rem}.grid{display:grid;grid-template-columns:repeat(2,120px);gap:12px}.cell{aspect-ratio:1;border-radius:12px;background:#fff;border:1px solid #e5e5e5;box-shadow:0 2px 8px rgba(0,0,0,.04);opacity:0;transform:scale(.88);animation:up .65s ${EASE} forwards}.cell:nth-child(1){animation-delay:.05s}.cell:nth-child(2){animation-delay:.12s}.cell:nth-child(3){animation-delay:.19s}.cell:nth-child(4){animation-delay:.26s}@keyframes up{to{opacity:1;transform:none}}`,
    body: `<div class="grid">${Array.from({length:4},()=>'<div class="cell"></div>').join('')}</div>` },

  { slug: 'ease-in-pricing-card', title: 'Pricing Card Ease', category: 'ease-in', tags: ['ease-in', 'pricing', 'card', 'professional'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#f4f6fb;padding:2rem;font-family:system-ui,sans-serif}.card{width:min(300px,90vw);padding:2rem;background:#fff;border-radius:20px;border:1px solid #e2e8f0;box-shadow:0 8px 30px rgba(15,23,42,.06);opacity:0;transform:translateY(36px);animation:up .85s ${EASE} forwards}.plan{font-size:.75rem;font-weight:600;text-transform:uppercase;letter-spacing:.1em;color:#6c8cff}.price{font-size:2.75rem;font-weight:800;color:#0f172a;margin:.5rem 0}.price span{font-size:1rem;font-weight:500;color:#888}ul{list-style:none;margin:1.25rem 0}.li{padding:.4rem 0;font-size:.9rem;color:#64748b;opacity:0;transform:translateX(-10px);animation:slide .5s ${EASE} forwards}.li:nth-child(1){animation-delay:.35s}.li:nth-child(2){animation-delay:.45s}.li:nth-child(3){animation-delay:.55s}@keyframes up{to{opacity:1;transform:none}}@keyframes slide{to{opacity:1;transform:none}}`,
    body: `<div class="card"><div class="plan">Pro</div><div class="price">$49<span>/mo</span></div><ul><li class="li">Unlimited projects</li><li class="li">Priority support</li><li class="li">Advanced analytics</li></ul></div>` },

  { slug: 'ease-in-cta-button', title: 'CTA Button Ease', category: 'ease-in', tags: ['ease-in', 'cta', 'button', 'professional'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#0d0d0f;padding:2rem;font-family:system-ui,sans-serif;text-align:center}p{color:#888;margin-bottom:1.5rem;font-size:.95rem;opacity:0;animation:fade .6s ${EASE} .1s forwards}.btn{padding:14px 36px;border:none;border-radius:10px;background:#6c8cff;color:#fff;font-weight:600;font-size:.95rem;opacity:0;transform:translateY(16px) scale(.95);animation:up .7s ${EASE} .25s forwards;box-shadow:0 8px 24px rgba(108,140,255,.35)}@keyframes up{to{opacity:1;transform:none}}@keyframes fade{to{opacity:1}}`,
    body: `<div><p>Ready to get started?</p><button class="btn" type="button">Start free trial</button></div>` },

  { slug: 'ease-in-sidebar-panel', title: 'Sidebar Panel Ease', category: 'ease-in', tags: ['ease-in', 'sidebar', 'panel', 'professional'],
    style: `body{margin:0;min-height:100vh;background:#e8ecf4;font-family:system-ui,sans-serif}.panel{position:fixed;top:0;left:0;bottom:0;width:min(280px,80vw);background:#fff;border-right:1px solid #e2e8f0;padding:2rem 1.5rem;box-shadow:4px 0 24px rgba(15,23,42,.06);transform:translateX(-100%);animation:slide .8s ${EASE} forwards}h3{font-size:1rem;font-weight:700;color:#111;margin-bottom:1.5rem}.item{padding:10px 12px;border-radius:8px;color:#64748b;font-size:.9rem;margin-bottom:4px;opacity:0;transform:translateX(-12px);animation:item .5s ${EASE} forwards}.item:nth-child(2){animation-delay:.2s}.item:nth-child(3){animation-delay:.3s}.item:nth-child(4){animation-delay:.4s}.item:nth-child(5){animation-delay:.5s}@keyframes slide{to{transform:none}}@keyframes item{to{opacity:1;transform:none}}`,
    body: `<aside class="panel"><h3>Dashboard</h3>${['Overview','Analytics','Projects','Settings'].map(t=>`<div class="item">${t}</div>`).join('')}</aside>` },

  { slug: 'ease-in-modal-enter', title: 'Modal Enter Ease', category: 'ease-in', tags: ['ease-in', 'modal', 'enter', 'professional'],
    style: `body{margin:0;min-height:100vh;background:rgba(15,23,42,.4);display:grid;place-items:center;padding:2rem;font-family:system-ui,sans-serif}.backdrop{position:fixed;inset:0;background:rgba(15,23,42,.5);opacity:0;animation:fade .4s ${EASE} forwards}.modal{position:relative;width:min(400px,92vw);padding:2rem;background:#fff;border-radius:20px;box-shadow:0 24px 80px rgba(15,23,42,.2);opacity:0;transform:translateY(24px) scale(.96);animation:up .65s ${EASE} .15s forwards}h2{font-size:1.25rem;font-weight:700;color:#111;margin-bottom:.5rem}p{color:#64748b;font-size:.9rem;line-height:1.6}@keyframes fade{to{opacity:1}}@keyframes up{to{opacity:1;transform:none}}`,
    body: `<div class="backdrop"></div><div class="modal"><h2>Welcome aboard</h2><p>Your account is ready. Start exploring the dashboard with smooth, professional transitions.</p></div>` },

  { slug: 'ease-in-toast-slide', title: 'Toast Slide Ease', category: 'ease-in', tags: ['ease-in', 'toast', 'notification', 'professional'],
    style: `body{margin:0;min-height:100vh;background:#f8fafc;font-family:system-ui,sans-serif}.toast{position:fixed;top:1.5rem;right:1.5rem;max-width:320px;padding:14px 18px;background:#fff;border-radius:12px;border:1px solid #e2e8f0;box-shadow:0 8px 30px rgba(15,23,42,.1);display:flex;align-items:center;gap:12px;opacity:0;transform:translateX(40px);animation:slide .7s ${EASE} .2s forwards}.dot{width:8px;height:8px;border-radius:50%;background:#22c55e;flex-shrink:0}.text{font-size:.88rem;color:#334155;font-weight:500}@keyframes slide{to{opacity:1;transform:none}}`,
    body: `<div class="toast"><div class="dot"></div><span class="text">Changes saved successfully</span></div>` },

  { slug: 'ease-in-avatar-group', title: 'Avatar Group Ease', category: 'ease-in', tags: ['ease-in', 'avatars', 'stagger', 'professional'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#fff;padding:2rem;font-family:system-ui,sans-serif}.group{display:flex}.av{width:44px;height:44px;border-radius:50%;border:3px solid #fff;margin-left:-12px;background:linear-gradient(135deg,var(--c),color-mix(in srgb,var(--c),#000 20%));opacity:0;transform:scale(.5);animation:pop .55s ${EASE} forwards}.av:first-child{margin-left:0}.av:nth-child(1){--c:#6c8cff;animation-delay:.05s}.av:nth-child(2){--c:#ff6cb0;animation-delay:.12s}.av:nth-child(3){--c:#6cffb8;animation-delay:.19s}.av:nth-child(4){--c:#f59e0b;animation-delay:.26s}.av:nth-child(5){--c:#764ba2;animation-delay:.33s}p{margin-top:1.25rem;font-size:.85rem;color:#888;text-align:center;opacity:0;animation:fade .5s ${EASE} .45s forwards}@keyframes pop{to{opacity:1;transform:none}}@keyframes fade{to{opacity:1}}`,
    body: `<div><div class="group">${Array.from({length:5},()=>'<div class="av"></div>').join('')}</div><p>2,400+ teams trust us</p></div>` },

  { slug: 'ease-in-progress-bar', title: 'Progress Bar Ease', category: 'ease-in', tags: ['ease-in', 'progress', 'bar', 'professional'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#0d0d0f;padding:2rem;font-family:system-ui,sans-serif}.wrap{width:min(360px,90vw)}.label{display:flex;justify-content:space-between;font-size:.8rem;color:#888;margin-bottom:8px}.track{height:6px;background:#222;border-radius:99px;overflow:hidden}.fill{height:100%;width:0;background:linear-gradient(90deg,#6c8cff,#6cffb8);border-radius:99px;animation:fill 1.8s ${EASE} .3s forwards}@keyframes fill{to{width:78%}}`,
    body: `<div class="wrap"><div class="label"><span>Uploading</span><span>78%</span></div><div class="track"><div class="fill"></div></div></div>` },

  { slug: 'ease-in-tab-indicator', title: 'Tab Indicator Ease', category: 'ease-in', tags: ['ease-in', 'tabs', 'indicator', 'professional'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#fafafa;padding:2rem;font-family:system-ui,sans-serif}.tabs{position:relative;display:flex;gap:2rem;border-bottom:1px solid #e5e5e5;padding-bottom:12px}.tab{font-size:.9rem;font-weight:500;color:#888;opacity:0;animation:fade .5s ${EASE} forwards}.tab:nth-child(1){animation-delay:.1s}.tab:nth-child(2){animation-delay:.18s}.tab:nth-child(3){animation-delay:.26s}.tab.active{color:#111;font-weight:600}.indicator{position:absolute;bottom:-1px;left:0;height:2px;width:60px;background:#6c8cff;border-radius:99px;transform:scaleX(0);transform-origin:left;animation:draw .6s ${EASE} .4s forwards}@keyframes fade{to{opacity:1}}@keyframes draw{to{transform:scaleX(1)}}`,
    body: `<div class="tabs"><span class="tab active">Overview</span><span class="tab">Analytics</span><span class="tab">Settings</span><div class="indicator"></div></div>` },

  { slug: 'ease-in-image-card-stack', title: 'Image Card Stack Ease', category: 'ease-in', tags: ['ease-in', 'image', 'stack', 'professional'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#111;padding:2rem}.stack{position:relative;width:min(240px,70vw);aspect-ratio:4/5}.card{position:absolute;inset:0;border-radius:14px;overflow:hidden;box-shadow:0 16px 40px rgba(0,0,0,.4);opacity:0;transform:translateY(24px) scale(.95);animation:up .75s ${EASE} forwards}.card img{width:100%;height:100%;object-fit:cover}.card:nth-child(1){animation-delay:.05s;z-index:3}.card:nth-child(2){animation-delay:.15s;z-index:2;transform:translateY(24px) scale(.95) rotate(-3deg)}.card:nth-child(3){animation-delay:.25s;z-index:1;transform:translateY(24px) scale(.95) rotate(3deg)}@keyframes up{to{opacity:1;transform:translateY(0) scale(1) rotate(0deg)}}`,
    body: `<div class="stack">${Array.from({length:3},()=>'<div class="card"><img src="'+IMG45+'" alt=""></div>').join('')}</div>` },

  { slug: 'ease-in-quote-mark', title: 'Quote Mark Ease', category: 'ease-in', tags: ['ease-in', 'quote', 'typography', 'professional'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#f5f5f5;padding:3rem 2rem;font-family:Georgia,serif}.quote{max-width:520px;text-align:center}.mark{font-size:5rem;line-height:1;color:#6c8cff;opacity:0;transform:scale(.5);animation:pop .7s ${EASE} forwards}blockquote{font-size:1.5rem;line-height:1.55;color:#333;margin:1rem 0;opacity:0;animation:fade .8s ${EASE} .25s forwards}cite{font-size:.9rem;color:#888;font-style:normal;opacity:0;animation:fade .6s ${EASE} .45s forwards}@keyframes pop{to{opacity:.3;transform:none}}@keyframes fade{to{opacity:1}}`,
    body: `<div class="quote"><div class="mark">"</div><blockquote>Simplicity is the ultimate sophistication in motion design.</blockquote><cite>— Leonardo da Vinci</cite></div>` },

  { slug: 'ease-in-divider-expand', title: 'Divider Expand Ease', category: 'ease-in', tags: ['ease-in', 'divider', 'expand', 'professional'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#fff;padding:2rem;font-family:system-ui,sans-serif;text-align:center}.divider{width:0;height:1px;background:#ddd;margin:0 auto 1.5rem;animation:expand .8s ${EASE} .2s forwards}h2{font-size:1.5rem;font-weight:700;color:#111;opacity:0;animation:fade .6s ${EASE} .5s forwards}@keyframes expand{to{width:120px}}@keyframes fade{to{opacity:1}}`,
    body: `<div><div class="divider"></div><h2>Section title</h2></div>` },

  { slug: 'ease-in-icon-pop', title: 'Icon Pop Ease', category: 'ease-in', tags: ['ease-in', 'icon', 'pop', 'professional'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#0d0d0f;padding:2rem}.icons{display:flex;gap:20px}.icon{width:52px;height:52px;border-radius:14px;background:#1a1a2e;border:1px solid #2a2a40;display:grid;place-items:center;color:#6c8cff;font-size:1.2rem;opacity:0;transform:scale(.5) rotate(-10deg);animation:pop .6s ${EASE} forwards}.icon:nth-child(1){animation-delay:.05s}.icon:nth-child(2){animation-delay:.12s}.icon:nth-child(3){animation-delay:.19s}.icon:nth-child(4){animation-delay:.26s}@keyframes pop{to{opacity:1;transform:none}}`,
    body: `<div class="icons">${['✦','◆','●','▲'].map(i=>`<div class="icon">${i}</div>`).join('')}</div>` },

  { slug: 'ease-in-hero-split', title: 'Hero Split Ease', category: 'ease-in', tags: ['ease-in', 'hero', 'split', 'professional'],
    style: `body{margin:0;min-height:100vh;background:#fafafa;display:grid;grid-template-columns:1fr 1fr;font-family:system-ui,sans-serif}@media(max-width:768px){body{grid-template-columns:1fr}}.copy{padding:4rem 3rem;display:flex;flex-direction:column;justify-content:center}.eyebrow{font-size:.72rem;letter-spacing:.15em;text-transform:uppercase;color:#6c8cff;font-weight:600;margin-bottom:1rem;opacity:0;animation:up .6s ${EASE} .1s forwards}h1{font-size:clamp(1.8rem,3vw,2.5rem);font-weight:700;color:#111;line-height:1.15;opacity:0;transform:translateY(20px);animation:up .8s ${EASE} .2s forwards}p{color:#666;margin-top:1rem;line-height:1.6;opacity:0;animation:up .7s ${EASE} .35s forwards}.visual{overflow:hidden;opacity:0;transform:translateX(30px);animation:slide .9s ${EASE} .25s forwards}.visual img{width:100%;height:100%;min-height:100vh;object-fit:cover}@keyframes up{to{opacity:1;transform:none}}@keyframes slide{to{opacity:1;transform:none}}`,
    body: `<div class="copy"><p class="eyebrow">Product launch</p><h1>Ship faster with polished motion</h1><p>Professional ease-in animations for modern landing pages.</p></div><div class="visual"><img src="${IMG}" alt=""></div>` },

  { slug: 'ease-in-checklist', title: 'Checklist Stagger Ease', category: 'ease-in', tags: ['ease-in', 'checklist', 'stagger', 'professional'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#fff;padding:2rem;font-family:system-ui,sans-serif}.list{max-width:320px}.item{display:flex;align-items:center;gap:12px;padding:10px 0;border-bottom:1px solid #f0f0f0;opacity:0;transform:translateX(-14px);animation:slide .55s ${EASE} forwards}.item:nth-child(1){animation-delay:.06s}.item:nth-child(2){animation-delay:.14s}.item:nth-child(3){animation-delay:.22s}.item:nth-child(4){animation-delay:.3s}.item:nth-child(5){animation-delay:.38s}.check{width:20px;height:20px;border-radius:50%;background:#6c8cff;color:#fff;display:grid;place-items:center;font-size:.65rem;font-weight:700;flex-shrink:0}span{font-size:.9rem;color:#334155}@keyframes slide{to{opacity:1;transform:none}}`,
    body: `<ul class="list">${['Setup complete','Team invited','Integrations connected','First project created','Go live'].map(t=>`<li class="item"><span class="check">✓</span><span>${t}</span></li>`).join('')}</ul>` },

  { slug: 'ease-in-mask-up-reveal', title: 'Mask Up Reveal Ease', category: 'ease-in', tags: ['ease-in', 'mask', 'reveal', 'professional'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#000;padding:2rem}.frame{width:min(400px,90vw);border-radius:16px;overflow:hidden;position:relative}.frame img{width:100%;display:block;transform:translateY(20px) scale(1.05);animation:img 1s ${EASE} .2s forwards}.mask{position:absolute;inset:0;background:#6c8cff;transform-origin:bottom;animation:mask .9s ${EASE} forwards}@keyframes mask{to{transform:scaleY(0)}}@keyframes img{to{transform:none}}`,
    body: `<div class="frame"><img src="${IMG45}" alt=""><div class="mask"></div></div>` },

  { slug: 'ease-in-subtle-bounce', title: 'Subtle Bounce Ease', category: 'ease-in', tags: ['ease-in', 'bounce', 'subtle', 'professional'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#f8fafc;padding:2rem;font-family:system-ui,sans-serif}.card{width:min(280px,85vw);padding:2rem;background:#fff;border-radius:16px;border:1px solid #e2e8f0;text-align:center;opacity:0;animation:enter .9s cubic-bezier(.34,1.2,.64,1) forwards}h3{font-size:1.1rem;font-weight:700;color:#111;margin-bottom:.35rem}p{font-size:.85rem;color:#888}@keyframes enter{from{opacity:0;transform:translateY(30px) scale(.92)}to{opacity:1;transform:none}}`,
    body: `<div class="card"><h3>Subtle bounce</h3><p>Refined overshoot for professional UI</p></div>` },
];
