const M = require('../lib/media');
const { getPalette } = require('../lib/palettes');

function wc(extra = '') {
  return `body{display:grid;place-items:center;min-height:100vh;${extra}}`;
}

function section(extra = '') {
  return `body{margin:0;min-height:100vh;${extra}}`;
}

function recipe(category, slug, title, tags, build) {
  return { category, slug: `${category}-${slug}`, title, tags: [category, ...tags], build };
}

function variants(category, items) {
  return items.map(([slug, title, tags, build]) => recipe(category, slug, title, tags, build));
}

// ─── Motion & cursor ───────────────────────────────────────────────
const motion = [
  ...variants('cursor-trails', [
    ['paint-trail', 'Paint Cursor Trail', ['paint'], () => ({ style: `${wc('background:#0a0a0c;cursor:crosshair')} canvas{position:fixed;inset:0;pointer-events:none}`, body: '<canvas id="c"></canvas>', script: `const c=document.getElementById('c'),x=c.getContext('2d');function r(){c.width=innerWidth;c.height=innerHeight;}r();addEventListener('resize',r);const pts=[];addEventListener('mousemove',e=>{pts.push({x:e.clientX,y:e.clientY,a:1});if(pts.length>40)pts.shift();});function d(){x.clearRect(0,0,c.width,c.height);pts.forEach((p,i)=>{x.beginPath();x.arc(p.x,p.y,8-i*.15,0,Math.PI*2);x.fillStyle='hsla('+(i*8+200)+',80%,60%,'+(i/pts.length)+')';x.fill();});requestAnimationFrame(d);}d();` })],
    ['particle-follow', 'Particle Follow Trail', ['particle'], () => ({ style: wc('background:#0d0d0f'), body: '<div id="d" style="position:fixed;width:12px;height:12px;background:#6c8cff;border-radius:50%;pointer-events:none;transform:translate(-50%,-50%)"></div>', script: `const d=document.getElementById('d');let mx=innerWidth/2,my=innerHeight/2,x=mx,y=my;addEventListener('mousemove',e=>{mx=e.clientX;my=e.clientY;});function a(){x+=(mx-x)*.12;y+=(my-y)*.12;d.style.left=x+'px';d.style.top=y+'px';requestAnimationFrame(a);}a();` })],
    ['text-trail', 'Text Cursor Trail', ['text'], () => ({ style: wc('background:#111;color:#6cffb8;font-family:monospace;font-size:1.5rem'), body: '<p id="t">Move cursor</p>', script: `const t=document.getElementById('t');const ch=[];addEventListener('mousemove',e=>{ch.push({x:e.clientX,y:e.clientY});if(ch.length>12)ch.shift();t.textContent=ch.map((_,i)=>'·').join('');});` })],
    ['gradient-comet', 'Gradient Comet Trail', ['gradient'], () => ({ style: `${wc('background:#000')} canvas{position:fixed;inset:0}`, body: '<canvas id="c"></canvas>', script: `const c=document.getElementById('c'),g=c.getContext('2d');c.width=innerWidth;c.height=innerHeight;let mx=0,my=0,tx=0,ty=0;addEventListener('mousemove',e=>{tx=e.clientX;ty=e.clientY;});function l(){mx+=(tx-mx)*.15;my+=(ty-my)*.15;g.fillStyle='rgba(0,0,0,.15)';g.fillRect(0,0,c.width,c.height);const gr=g.createRadialGradient(mx,my,0,mx,my,60);gr.addColorStop(0,'#ff6cb0');gr.addColorStop(1,'transparent');g.fillStyle=gr;g.fillRect(mx-60,my-60,120,120);requestAnimationFrame(l);}l();` })],
  ]),
  ...variants('mouse-effects', [
    ['parallax-image', 'Parallax Image on Mouse', ['parallax'], () => ({ style: `${wc('background:#111;overflow:hidden')} .img{width:min(80vw,500px);aspect-ratio:16/9;border-radius:12px;overflow:hidden;transition:transform .1s}`, body: `<div class="img" id="i"><img src="${M.IMG169}" style="width:100%;height:100%;object-fit:cover"></div>`, script: `const i=document.getElementById('i');i.parentElement.addEventListener('mousemove',e=>{const r=i.getBoundingClientRect();const x=(e.clientX-r.left)/r.width-.5;const y=(e.clientY-r.top)/r.height-.5;i.style.transform='translate('+x*20+'px,'+y*20+'px)';});` })],
    ['video-spotlight', 'Video Spotlight Follow', ['video'], () => ({ style: `${section('background:#000')} .spot{position:fixed;inset:0;background:radial-gradient(circle 120px at var(--x,50%) var(--y,50%),transparent,#000 100%)} video{position:fixed;inset:0;width:100%;height:100%;object-fit:cover;z-index:-1}`, body: `<video src="${M.VID169}" autoplay muted loop playsinline></video><div class="spot" id="s"></div>`, script: `document.addEventListener('mousemove',e=>document.getElementById('s').style.setProperty('--x',e.clientX+'px'),document.getElementById('s').style.setProperty('--y',e.clientY+'px'));` })],
    ['button-glow-follow', 'Button Glow Follow', ['button'], () => ({ style: `${wc('background:#0d0d0f;padding:2rem')} .btn{position:relative;padding:16px 40px;border:1px solid #2a2a40;border-radius:12px;background:#1a1a2e;color:#fff;font-weight:600;overflow:hidden;cursor:pointer;--on:0} .btn::before{content:'';position:absolute;left:var(--x,50%);top:var(--y,50%);width:180px;height:180px;transform:translate(-50%,-50%);background:radial-gradient(circle,rgba(108,140,255,.55) 0%,transparent 70%);opacity:var(--on);transition:opacity .15s;pointer-events:none} .btn span{position:relative;z-index:1}`, body: '<button class="btn" id="b" type="button"><span>Hover Me</span></button>', script: `const b=document.getElementById('b');b.addEventListener('mousemove',e=>{const r=b.getBoundingClientRect();b.style.setProperty('--x',(e.clientX-r.left)+'px');b.style.setProperty('--y',(e.clientY-r.top)+'px');b.style.setProperty('--on','1');});b.addEventListener('mouseleave',()=>b.style.setProperty('--on','0'));` })],
    ['background-warp', 'Background Warp on Mouse', ['warp'], () => ({ style: `${wc('background:#0d0d0f')} .grid{position:fixed;inset:0;background-image:linear-gradient(rgba(108,140,255,.08) 1px,transparent 1px),linear-gradient(90deg,rgba(108,140,255,.08) 1px,transparent 1px);background-size:40px 40px;transition:transform .1s}`, body: '<div class="grid" id="g"></div><h1 style="position:relative;z-index:1;color:#fff;font-size:2rem">Warp</h1>', script: `const g=document.getElementById('g');addEventListener('mousemove',e=>{const x=(e.clientX/innerWidth-.5)*20;const y=(e.clientY/innerHeight-.5)*20;g.style.transform='perspective(600px) rotateX('+(-y)+'deg) rotateY('+x+'deg)';});` })],
  ]),
  ...variants('ease-in', [
    ['fade-up-stagger', 'Fade Up Stagger', ['fade'], () => ({ style: `${wc('background:#fafafa;gap:12px')} .item{opacity:0;transform:translateY(24px);animation:up .6s forwards;padding:12px 24px;background:#fff;border-radius:8px;box-shadow:0 2px 8px rgba(0,0,0,.06)} .item:nth-child(1){animation-delay:.1s}.item:nth-child(2){animation-delay:.2s}.item:nth-child(3){animation-delay:.3s}.item:nth-child(4){animation-delay:.4s} @keyframes up{to{opacity:1;transform:translateY(0)}}`, body: '<div style="display:flex;flex-direction:column;gap:12px">'+[1,2,3,4].map(n=>`<div class="item">Item ${n}</div>`).join('')+'</div>' })],
    ['scale-in-grid', 'Scale In Grid', ['scale'], () => ({ style: `${wc('background:#111')} .g{display:grid;grid-template-columns:repeat(3,60px);gap:8px} .c{aspect-ratio:1;background:#6c8cff;border-radius:8px;opacity:0;transform:scale(0);animation:pop .5s forwards} .c:nth-child(1){animation-delay:.05s}.c:nth-child(2){animation-delay:.1s}.c:nth-child(3){animation-delay:.15s}.c:nth-child(4){animation-delay:.2s}.c:nth-child(5){animation-delay:.25s}.c:nth-child(6){animation-delay:.3s} @keyframes pop{to{opacity:1;transform:scale(1)}}`, body: '<div class="g">'+Array(6).fill('<div class="c"></div>').join('')+'</div>' })],
    ['blur-in-headline', 'Blur In Headline', ['blur'], () => ({ style: `${wc('background:#0d0d0f')} h1{font-size:3rem;font-weight:800;color:#fff;filter:blur(12px);opacity:0;animation:clear 1s forwards} @keyframes clear{to{filter:blur(0);opacity:1}}`, body: '<h1>Focus In</h1>' })],
    ['slide-in-cards', 'Slide In Cards', ['slide'], () => ({ style: `${wc('background:#eee;gap:16px;flex-direction:row;flex-wrap:wrap;padding:2rem')} .card{width:140px;padding:1.5rem;background:#fff;border-radius:12px;opacity:0;transform:translateX(-40px);animation:sl .6s forwards} .card:nth-child(2){animation-delay:.15s}.card:nth-child(3){animation-delay:.3s} @keyframes sl{to{opacity:1;transform:translateX(0)}}`, body: [1,2,3].map(n=>`<div class="card">Card ${n}</div>`).join('') })],
  ]),
  ...variants('scroll-animations', [
    ['reveal-on-scroll', 'Reveal On Scroll', ['reveal'], () => ({ style: `${section('background:#f5f5f5')} .sp{height:50vh;display:grid;place-items:center;color:#888} .box{max-width:500px;margin:0 auto 50vh;padding:2rem;background:#fff;border-radius:12px;opacity:0;transform:translateY(40px);transition:all .7s} .box.vis{opacity:1;transform:translateY(0)}`, body: '<div class="sp">Scroll</div>'+[1,2,3].map(n=>`<div class="box">Section ${n}</div>`).join(''), script: `const obs=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('vis')),{threshold:.2});document.querySelectorAll('.box').forEach(b=>obs.observe(b));` })],
    ['pin-fade-section', 'Pin Fade Section', ['pin'], () => ({ style: `${section('background:#0d0d0f;color:#fff')} .pin{height:200vh;position:relative} .sticky{position:sticky;top:0;height:100vh;display:grid;place-items:center} h1{font-size:3rem;opacity:var(--o,1);transition:opacity .1s}`, body: '<section class="pin"><div class="sticky"><h1 id="h">Pinned</h1></div></section>', script: `const h=document.getElementById('h');addEventListener('scroll',()=>{const r=document.querySelector('.pin').getBoundingClientRect();const p=Math.min(1,Math.max(0,-r.top/(r.height-innerHeight)));h.style.setProperty('--o',1-p);});` })],
    ['horizontal-scrub', 'Horizontal Text Scrub', ['scrub'], () => ({ style: `${section('background:#111')} .track{height:300vh} .sticky{position:sticky;top:0;height:100vh;display:flex;align-items:center;overflow:hidden} .text{font-size:4rem;font-weight:900;color:#fff;white-space:nowrap;transform:translateX(var(--x,0))}`, body: '<div class="track"><div class="sticky"><div class="text" id="t">SCROLL TO MOVE →</div></div></div>', script: `const t=document.getElementById('t'),tr=document.querySelector('.track');addEventListener('scroll',()=>{const r=tr.getBoundingClientRect();const p=Math.min(1,Math.max(0,-r.top/(r.height-innerHeight)));t.style.setProperty('--x',-p*400+'px');});` })],
    ['stacked-cards-unroll', 'Stacked Cards Unroll', ['cards'], () => ({ style: `${section('background:#eee;padding:4rem 2rem')} .card{max-width:400px;margin:0 auto 2rem;padding:2rem;background:#fff;border-radius:12px;box-shadow:0 4px 20px rgba(0,0,0,.08);opacity:0;transform:translateY(60px) scale(.95);transition:all .6s} .card.vis{opacity:1;transform:none}`, body: [1,2,3,4].map(n=>`<div class="card">Card ${n}</div>`).join(''), script: `new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('vis')),{threshold:.15}).observe.bind(null);document.querySelectorAll('.card').forEach(c=>new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('vis')),{threshold:.15}).observe(c));` })],
  ]),
];

module.exports = motion;
