const base = 'font-family:system-ui,-apple-system,sans-serif';
const reduced = '@media (prefers-reduced-motion:reduce){*{animation:none!important;transition:none!important}}';

function extractNavDesc(slug) {
  if (RECIPES[slug]) return slug;
  if (slug.startsWith('menu-fullscreen-')) return slug;
  if (slug.startsWith('navigation-')) {
    return slug.replace(/^navigation-/, '').replace(/-\d+$/, '');
  }
  return slug;
}

const RECIPES = {
  'minimal-top-nav': () => ({
    style: `body{margin:0;min-height:100vh;background:#fafafa;color:#111;${base}}${reduced}nav{display:flex;align-items:center;justify-content:space-between;padding:1.1rem 2rem;background:#fff;border-bottom:1px solid #e8e8e8}.logo{font-weight:800;font-size:1.1rem;letter-spacing:-.02em;color:#000}.links{display:flex;gap:2rem;list-style:none;margin:0;padding:0}.links a{text-decoration:none;color:#888;font-size:.9rem;font-weight:500;transition:color .25s}.links a:hover{color:#000}.hero{padding:6rem 2rem;text-align:center}h1{font-size:clamp(2rem,5vw,2.75rem);font-weight:800;letter-spacing:-.03em}`,
    body: `<nav><div class="logo">Northline</div><ul class="links"><li><a href="#">Work</a></li><li><a href="#">Studio</a></li><li><a href="#">Contact</a></li></ul></nav><div class="hero"><h1>Minimal Navigation</h1></div>`,
    script: '',
  }),

  'transparent-scroll-nav': () => ({
    style: `body{margin:0;background:#111;color:#fff;${base}}${reduced}nav{position:fixed;top:0;left:0;right:0;padding:1.1rem 2rem;display:flex;justify-content:space-between;align-items:center;z-index:10;transition:background .35s,backdrop-filter .35s,box-shadow .35s}nav.scrolled{background:rgba(255,255,255,.92);backdrop-filter:blur(14px);box-shadow:0 1px 0 rgba(0,0,0,.06);color:#111}.logo{font-weight:800;letter-spacing:-.02em}nav .links{display:flex;gap:1.5rem}nav .links a{color:inherit;text-decoration:none;font-size:.88rem;opacity:.75;transition:opacity .2s}nav .links a:hover{opacity:1}nav.scrolled .links a{opacity:.55}nav.scrolled .links a:hover{opacity:1}.hero{height:100vh;display:grid;place-items:center;background:linear-gradient(180deg,#1a1a1a 0%,#0a0a0a 100%)}.hero h1{font-size:clamp(2.5rem,6vw,3.5rem);font-weight:800;letter-spacing:-.03em}.content{min-height:120vh;padding:4rem 2rem;color:#888;text-align:center}`,
    body: `<nav id="nav"><div class="logo">ScrollNav</div><div class="links"><a href="#">Work</a><a href="#">About</a></div></nav><section class="hero"><h1>Scroll to reveal</h1></section><section class="content">Content continues below the navigation bar.</section>`,
    script: `const nav=document.getElementById('nav');addEventListener('scroll',()=>nav.classList.toggle('scrolled',scrollY>48),{passive:true});`,
  }),

  'fullscreen-hamburger-menu': () => ({
    style: `body{margin:0;min-height:100vh;background:#fff;color:#111;${base}}${reduced}header{display:flex;justify-content:space-between;align-items:center;padding:1.4rem 2rem;position:relative;z-index:30}.logo{font-weight:800}.burger{width:28px;height:18px;cursor:pointer;z-index:30}.burger span{display:block;height:2px;background:#111;margin:5px 0;transition:transform .35s,opacity .35s}.burger.open span:nth-child(1){transform:translateY(7px) rotate(45deg)}.burger.open span:nth-child(2){opacity:0}.burger.open span:nth-child(3){transform:translateY(-7px) rotate(-45deg)}.menu{position:fixed;inset:0;background:#000;display:grid;place-items:center;opacity:0;pointer-events:none;transition:opacity .4s;z-index:20}.menu.open{opacity:1;pointer-events:auto}.menu a{display:block;font-size:clamp(2.2rem,6vw,3.2rem);font-weight:800;color:#fff;text-decoration:none;padding:.45rem 0;opacity:0;transform:translateY(24px);transition:opacity .45s,transform .45s}.menu.open a{opacity:1;transform:none}.menu.open a:nth-child(1){transition-delay:.08s}.menu.open a:nth-child(2){transition-delay:.16s}.menu.open a:nth-child(3){transition-delay:.24s}.menu.open a:nth-child(4){transition-delay:.32s}`,
    body: `<header><div class="logo">Studio</div><div class="burger" id="b"><span></span><span></span><span></span></div></header><div class="menu" id="m"><div><a href="#">Home</a><a href="#">Work</a><a href="#">About</a><a href="#">Contact</a></div></div>`,
    script: `const b=document.getElementById('b'),m=document.getElementById('m');b.onclick=()=>{b.classList.toggle('open');m.classList.toggle('open');};`,
  }),

  'animated-underline-tabs': () => ({
    style: `body{margin:0;min-height:100vh;display:grid;place-items:center;background:#fafafa;color:#111;${base}}${reduced}.wrap{width:min(92vw,520px)}.tabs{display:flex;position:relative;border-bottom:2px solid #e5e5e5}.tab{padding:1rem 1.5rem;border:none;background:none;font-size:.95rem;color:#999;cursor:pointer;font-weight:500;transition:color .25s}.tab.on{color:#000;font-weight:600}.ind{position:absolute;bottom:-2px;height:2px;background:#000;transition:left .35s cubic-bezier(.22,.61,.36,1),width .35s cubic-bezier(.22,.61,.36,1)}.panel{padding:2rem 0;color:#666;font-size:.95rem;line-height:1.6}`,
    body: `<div class="wrap"><div class="tabs" id="tabs">${['Overview','Features','Pricing'].map((t,i)=>`<button class="tab${i?'':' on'}" data-i="${i}">${t}</button>`).join('')}<div class="ind" id="ind"></div></div><div class="panel" id="p">Overview content goes here.</div></div>`,
    script: `const tabs=[...document.querySelectorAll('.tab')],ind=document.getElementById('ind'),p=document.getElementById('p'),tx=['Overview content goes here.','Features content goes here.','Pricing content goes here.'];function mv(t){const r=t.getBoundingClientRect(),b=t.parentElement.getBoundingClientRect();ind.style.left=r.left-b.left+'px';ind.style.width=r.width+'px';}mv(tabs[0]);tabs.forEach(t=>t.onclick=()=>{tabs.forEach(x=>x.classList.remove('on'));t.classList.add('on');mv(t);p.textContent=tx[t.dataset.i];});`,
  }),

  'sticky-nav': () => ({
    style: `body{margin:0;min-height:100vh;background:#f4f4f4;color:#111;${base}}${reduced}.nav{position:sticky;top:0;background:#fff;padding:1rem 2rem;display:flex;gap:2rem;align-items:center;border-bottom:1px solid #e8e8e8;z-index:10;box-shadow:0 1px 0 rgba(0,0,0,.04)}.logo{font-weight:800;letter-spacing:-.02em}.nav a{color:#666;text-decoration:none;font-size:.9rem;font-weight:500;transition:color .2s}.nav a:hover{color:#000}.spacer{min-height:150vh;padding:3rem 2rem;color:#888;line-height:1.7}`,
    body: `<nav class="nav"><span class="logo">Brand</span><a href="#">Home</a><a href="#">About</a><a href="#">Services</a><a href="#">Contact</a></nav><div class="spacer"><p>Scroll to see the navigation stick to the top of the viewport.</p></div>`,
    script: '',
  }),

  'pill-nav': () => ({
    style: `body{margin:0;min-height:100vh;display:grid;place-items:center;background:#fff;color:#111;${base}}${reduced}.nav{position:relative;display:inline-flex;gap:4px;background:#f0f0f0;padding:4px;border-radius:999px}.indicator{position:absolute;top:4px;left:4px;height:calc(100% - 8px);border-radius:999px;background:#000;box-shadow:0 4px 14px rgba(0,0,0,.18);transition:transform .38s cubic-bezier(.22,.61,.36,1),width .38s cubic-bezier(.22,.61,.36,1);z-index:0;pointer-events:none}.tab{position:relative;z-index:1;padding:10px 22px;border:none;background:transparent;color:#888;font-size:.88rem;font-weight:600;border-radius:999px;cursor:pointer;transition:color .28s}.tab.on{color:#fff}`,
    body: `<nav class="nav" id="nav" role="tablist"><span class="indicator" id="indicator" aria-hidden="true"></span>${['Day','Week','Month','Year'].map((t,i)=>`<button class="tab${i?'':' on'}" type="button" role="tab" aria-selected="${i===0?'true':'false'}">${t}</button>`).join('')}</nav>`,
    script: `const nav=document.getElementById('nav'),indicator=document.getElementById('indicator'),tabs=[...document.querySelectorAll('.tab')],reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;function moveIndicator(tab){const x=tab.offsetLeft-4;indicator.style.width=tab.offsetWidth+'px';indicator.style.transform='translateX('+x+'px)'}function select(tab){tabs.forEach(t=>{const on=t===tab;t.classList.toggle('on',on);t.setAttribute('aria-selected',on?'true':'false')});moveIndicator(tab)}tabs.forEach(t=>t.addEventListener('click',()=>select(t)));if(reduced)indicator.style.transition='none';select(tabs.find(t=>t.classList.contains('on'))||tabs[0]);addEventListener('resize',()=>{const on=tabs.find(t=>t.classList.contains('on'));if(on)moveIndicator(on)},{passive:true});`,
  }),

  'sidebar-nav': () => ({
    style: `body{margin:0;min-height:100vh;display:flex;background:#f5f5f5;color:#111;${base}}${reduced}.nav{width:220px;background:#000;padding:1.5rem 0;min-height:100vh;flex-shrink:0}.nav a{display:block;padding:11px 1.5rem;color:#888;text-decoration:none;font-size:.9rem;font-weight:500;border-left:3px solid transparent;transition:color .25s,background .25s,border-color .25s}.nav a.on,.nav a:hover{color:#fff;background:rgba(255,255,255,.06)}.nav a.on{border-color:#fff}.main{flex:1;padding:2.5rem;color:#444}`,
    body: `<nav class="nav" id="nav"><a href="#" class="on">Dashboard</a><a href="#">Projects</a><a href="#">Analytics</a><a href="#">Settings</a></nav><main class="main">Main content area</main>`,
    script: `document.querySelectorAll('.nav a').forEach(a=>a.onclick=e=>{e.preventDefault();document.querySelectorAll('.nav a').forEach(x=>x.classList.remove('on'));a.classList.add('on');});`,
  }),

  'breadcrumb-nav': () => ({
    style: `body{margin:0;min-height:100vh;background:#fff;color:#111;${base}}${reduced}.nav{padding:1rem 2rem;border-bottom:1px solid #eee;display:flex;gap:8px;align-items:center;font-size:.88rem}.nav a{color:#999;text-decoration:none;transition:color .2s}.nav a:hover{color:#000}.sep{color:#ddd;user-select:none}.cur{color:#000;font-weight:600}.content{padding:2rem;color:#666}`,
    body: `<nav class="nav" aria-label="Breadcrumb"><a href="#">Home</a><span class="sep">/</span><a href="#">Products</a><span class="sep">/</span><span class="cur">Widget Pro</span></nav><div class="content">Product detail page content.</div>`,
    script: '',
  }),

  'centered-nav': () => ({
    style: `body{margin:0;min-height:100vh;background:#fafafa;color:#111;${base}}${reduced}nav{display:grid;grid-template-columns:1fr auto 1fr;align-items:center;padding:1rem 2rem;background:#fff;border-bottom:1px solid #e8e8e8}.logo{font-weight:800;letter-spacing:-.02em}.links{display:flex;gap:1.75rem;justify-content:center}.links a{color:#666;text-decoration:none;font-size:.88rem;font-weight:500;transition:color .2s}.links a:hover{color:#000}.cta{justify-self:end;padding:9px 20px;background:#000;color:#fff;text-decoration:none;font-size:.85rem;font-weight:600;border-radius:6px;transition:opacity .2s}.cta:hover{opacity:.85}`,
    body: `<nav><div class="logo">Acme</div><div class="links"><a href="#">Work</a><a href="#">About</a><a href="#">Blog</a></div><a href="#" class="cta">Get Started</a></nav>`,
    script: '',
  }),

  'transparent-nav': () => ({
    style: `body{margin:0;min-height:100vh;background:linear-gradient(180deg,#e8e8e8 0%,#d0d0d0 100%);color:#111;${base}}${reduced}nav{position:fixed;top:1rem;left:50%;transform:translateX(-50%);display:flex;gap:1.5rem;align-items:center;padding:.65rem 1.5rem;background:rgba(255,255,255,.72);backdrop-filter:blur(16px);border:1px solid rgba(0,0,0,.08);border-radius:999px;box-shadow:0 8px 32px rgba(0,0,0,.08);z-index:10}.logo{font-weight:800;font-size:.95rem}.links{display:flex;gap:1.25rem}.links a{color:#666;text-decoration:none;font-size:.85rem;font-weight:500;transition:color .2s}.links a:hover{color:#000}.hero{height:100vh;display:grid;place-items:center}.hero h1{font-size:2.5rem;font-weight:800;letter-spacing:-.03em}`,
    body: `<nav><div class="logo">Glass</div><div class="links"><a href="#">Home</a><a href="#">Work</a><a href="#">Contact</a></div></nav><section class="hero"><h1>Frosted glass bar</h1></section>`,
    script: '',
  }),

  'split-nav': () => ({
    style: `body{margin:0;min-height:100vh;background:#fff;color:#111;${base}}${reduced}nav{display:flex;justify-content:space-between;align-items:center;padding:1.2rem 2.5rem;border-bottom:1px solid #eee}.logo{font-weight:800;font-size:1.1rem;letter-spacing:-.02em}.links{display:flex;gap:2rem}.links a{color:#666;text-decoration:none;font-size:.9rem;font-weight:500;position:relative;transition:color .25s}.links a::after{content:'';position:absolute;left:0;bottom:-4px;width:0;height:1px;background:#000;transition:width .3s}.links a:hover{color:#000}.links a:hover::after{width:100%}`,
    body: `<nav><div class="logo">Split</div><div class="links"><a href="#">Products</a><a href="#">Solutions</a><a href="#">Pricing</a><a href="#">Contact</a></div></nav>`,
    script: '',
  }),

  'search-nav': () => ({
    style: `body{margin:0;min-height:100vh;background:#fafafa;color:#111;${base}}${reduced}nav{display:flex;align-items:center;gap:1rem;padding:1rem 2rem;background:#fff;border-bottom:1px solid #e8e8e8}.logo{font-weight:800;margin-right:auto}.links{display:flex;gap:1.5rem}.links a{color:#666;text-decoration:none;font-size:.88rem;transition:color .2s}.links a:hover{color:#000}.search{display:flex;align-items:center;overflow:hidden;border:1px solid #ddd;border-radius:999px;background:#f8f8f8;transition:width .4s cubic-bezier(.22,.61,.36,1),border-color .3s;width:40px}.search.open{width:220px;border-color:#000}.search input{border:none;background:transparent;padding:8px 14px;font-size:.88rem;outline:none;width:100%;opacity:0;transition:opacity .25s .1s}.search.open input{opacity:1}.search-btn{width:40px;height:36px;border:none;background:none;cursor:pointer;display:grid;place-items:center;flex-shrink:0}.search-btn svg{width:16px;height:16px;stroke:#333;stroke-width:2;fill:none}`,
    body: `<nav><div class="logo">Find</div><div class="links"><a href="#">Browse</a><a href="#">Collections</a></div><div class="search" id="s"><button class="search-btn" id="btn" aria-label="Search"><svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg></button><input type="search" placeholder="Search…"></div></nav>`,
    script: `const s=document.getElementById('s'),btn=document.getElementById('btn'),inp=s.querySelector('input');btn.onclick=()=>{s.classList.toggle('open');if(s.classList.contains('open'))inp.focus();};document.onclick=e=>{if(!s.contains(e.target))s.classList.remove('open');};`,
  }),

  'mega-nav': () => ({
    style: `body{margin:0;min-height:100vh;background:#f8f8f8;color:#111;${base}}${reduced}nav{display:flex;gap:2rem;padding:1rem 2rem;background:#fff;border-bottom:1px solid #e8e8e8;position:relative}.logo{font-weight:800;margin-right:1rem}nav>a{color:#666;text-decoration:none;font-size:.88rem;font-weight:500;transition:color .2s}nav>a:hover{color:#000}.mega{position:absolute;top:100%;left:0;right:0;background:#fff;border-bottom:1px solid #e8e8e8;padding:2rem 2.5rem;display:grid;grid-template-columns:repeat(3,1fr);gap:2rem;box-shadow:0 12px 40px rgba(0,0,0,.06);opacity:0;transform:translateY(-8px);pointer-events:none;transition:opacity .3s,transform .3s}.mega.open{opacity:1;transform:none;pointer-events:auto}.mega h4{font-size:.72rem;text-transform:uppercase;letter-spacing:.12em;color:#aaa;margin-bottom:.85rem;font-weight:600}.mega a{display:block;padding:5px 0;color:#444;text-decoration:none;font-size:.9rem;transition:color .2s,padding-left .2s}.mega a:hover{color:#000;padding-left:6px}.content{padding:3rem 2rem;color:#888}`,
    body: `<nav><div class="logo">Mega</div><a href="#">Home</a><a href="#" id="trig">Products</a><a href="#">About</a><div class="mega" id="mega"><div><h4>Platform</h4><a href="#">Analytics</a><a href="#">Automation</a><a href="#">Integrations</a></div><div><h4>Tools</h4><a href="#">Editor</a><a href="#">API</a><a href="#">CLI</a></div><div><h4>Support</h4><a href="#">Docs</a><a href="#">Community</a><a href="#">Contact</a></div></div></nav><div class="content">Hover Products to open the mega panel.</div>`,
    script: `const trig=document.getElementById('trig'),mega=document.getElementById('mega');let open=false;trig.onmouseenter=()=>{open=true;mega.classList.add('open');};trig.parentElement.onmouseleave=()=>{open=false;mega.classList.remove('open');};trig.onclick=e=>{e.preventDefault();mega.classList.toggle('open');};`,
  }),

  'mobile-nav': () => ({
    style: `body{margin:0;min-height:100vh;background:#f0f0f0;color:#111;${base}}${reduced}.page{min-height:100vh;padding-bottom:72px}.content{padding:2rem;color:#666}.dock{position:fixed;bottom:0;left:0;right:0;display:flex;justify-content:space-around;padding:.6rem .5rem;background:#fff;border-top:1px solid #e5e5e5;box-shadow:0 -4px 24px rgba(0,0,0,.06)}.item{display:flex;flex-direction:column;align-items:center;gap:.25rem;border:none;background:none;cursor:pointer;color:#aaa;font-size:.65rem;font-weight:500;padding:.35rem .75rem;transition:color .25s}.item.on{color:#000}.item svg{width:22px;height:22px;stroke:currentColor;stroke-width:2;fill:none;stroke-linecap:round;transition:transform .25s}.item.on svg{transform:scale(1.08)}`,
    body: `<div class="page"><div class="content" id="c">Home view</div></div><nav class="dock" aria-label="Mobile navigation">${[['Home','m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z M9 22V12h6v10'],['Search','M11 19a8 8 0 1 0 0-16 8 8 0 0 0 0 16z M21 21l-4.3-4.3'],['Add','M12 5v14 M5 12h14'],['Profile','M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2 M12 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8z']].map(([l,d],i)=>`<button class="item${i?'':' on'}" type="button" data-l="${l}"><svg viewBox="0 0 24 24"><path d="${d}"/></svg>${l}</button>`).join('')}</nav>`,
    script: `document.querySelectorAll('.item').forEach(b=>b.onclick=()=>{document.querySelectorAll('.item').forEach(x=>x.classList.remove('on'));b.classList.add('on');document.getElementById('c').textContent=b.dataset.l+' view';});`,
  }),

  'underline-nav': () => ({
    style: `body{margin:0;min-height:100vh;display:grid;place-items:center;background:#fff;color:#111;${base}}${reduced}nav{display:flex;gap:2rem;padding:1rem 0}.nav a{color:#999;text-decoration:none;font-size:.95rem;font-weight:500;position:relative;padding:.25rem 0;transition:color .25s}.nav a::after{content:'';position:absolute;left:0;bottom:0;width:100%;height:2px;background:#000;transform:scaleX(0);transform-origin:left;transition:transform .35s cubic-bezier(.22,.61,.36,1)}.nav a:hover,.nav a.on{color:#000}.nav a:hover::after,.nav a.on::after{transform:scaleX(1)}`,
    body: `<nav class="nav" id="nav">${['Home','Work','About','Contact'].map((t,i)=>`<a href="#" class="${i?'':'on'}">${t}</a>`).join('')}</nav>`,
    script: `document.querySelectorAll('.nav a').forEach(a=>a.onclick=e=>{e.preventDefault();document.querySelectorAll('.nav a').forEach(x=>x.classList.remove('on'));a.classList.add('on');});`,
  }),

  'floating-nav': () => ({
    style: `body{margin:0;min-height:100vh;background:#e8e8e8;color:#111;${base}}${reduced}.hero{height:100vh;display:grid;place-items:center}h1{font-size:2.5rem;font-weight:800;letter-spacing:-.03em}nav{position:fixed;top:1.25rem;left:50%;transform:translateX(-50%);display:flex;gap:.25rem;padding:.4rem;background:#fff;border-radius:14px;box-shadow:0 8px 32px rgba(0,0,0,.12),0 1px 0 rgba(0,0,0,.04);z-index:10}nav a{padding:10px 18px;color:#888;text-decoration:none;font-size:.85rem;font-weight:600;border-radius:10px;transition:background .25s,color .25s}nav a.on,nav a:hover{background:#000;color:#fff}`,
    body: `<nav id="nav">${['Home','Features','Pricing','Contact'].map((t,i)=>`<a href="#" class="${i?'':'on'}">${t}</a>`).join('')}</nav><section class="hero"><h1>Floating navigation</h1></section>`,
    script: `document.querySelectorAll('nav a').forEach(a=>a.onclick=e=>{e.preventDefault();document.querySelectorAll('nav a').forEach(x=>x.classList.remove('on'));a.classList.add('on');});`,
  }),

  'gradient-nav': () => ({
    style: `body{margin:0;min-height:100vh;background:#f5f5f5;color:#111;${base}}${reduced}nav{background:#000;padding:1rem 2rem;display:flex;justify-content:space-between;align-items:center}.logo{font-weight:800;color:#fff;letter-spacing:-.02em}.links{display:flex;gap:2rem}.links a{color:rgba(255,255,255,.65);text-decoration:none;font-size:.88rem;font-weight:500;transition:color .25s}.links a:hover,.links a.on{color:#fff}.cta{padding:8px 18px;background:#fff;color:#000;text-decoration:none;font-size:.82rem;font-weight:700;border-radius:6px;transition:opacity .2s}.cta:hover{opacity:.9}.content{padding:3rem 2rem;color:#888}`,
    body: `<nav><div class="logo">Mono</div><div class="links"><a href="#" class="on">Home</a><a href="#">Work</a><a href="#">About</a></div><a href="#" class="cta">Sign in</a></nav><div class="content">Inverted monochrome navigation bar.</div>`,
    script: `document.querySelectorAll('.links a').forEach(a=>a.onclick=e=>{e.preventDefault();document.querySelectorAll('.links a').forEach(x=>x.classList.remove('on'));a.classList.add('on');});`,
  }),

  'menu-fullscreen-split-reveal': () => ({
    style: `body{margin:0;min-height:100vh;background:#fff;color:#111;${base}}${reduced}.top{display:flex;justify-content:space-between;align-items:center;padding:1.4rem 2rem;position:relative;z-index:30}.logo{font-weight:800}.burger{width:28px;height:18px;cursor:pointer;z-index:30}.burger span{display:block;height:2px;background:#111;margin:5px 0;transition:transform .35s,opacity .35s}.burger.open span:nth-child(1){transform:translateY(7px) rotate(45deg)}.burger.open span:nth-child(2){opacity:0}.burger.open span:nth-child(3){transform:translateY(-7px) rotate(-45deg)}.overlay{position:fixed;inset:0;z-index:20;pointer-events:none}.pane{position:absolute;top:0;bottom:0;width:50%;transition:transform .55s cubic-bezier(.22,.61,.36,1)}.pane--l{left:0;background:#fff;transform:translateX(-100%)}.pane--r{right:0;background:#000;transform:translateX(100%)}.overlay.open{pointer-events:auto}.overlay.open .pane{transform:translateX(0)}.nav{position:absolute;inset:0;display:grid;place-items:center;z-index:25;opacity:0;transition:opacity .35s .15s}.overlay.open .nav{opacity:1}.nav a{display:block;font-size:clamp(2rem,5vw,3rem);font-weight:800;color:#fff;text-decoration:none;padding:.4rem 0;opacity:0;transform:translateY(16px);transition:opacity .4s,transform .4s}.overlay.open a{opacity:1;transform:none}.overlay.open a:nth-child(1){transition-delay:.2s}.overlay.open a:nth-child(2){transition-delay:.28s}.overlay.open a:nth-child(3){transition-delay:.36s}.overlay.open a:nth-child(4){transition-delay:.44s}`,
    body: `<div class="top"><strong class="logo">Studio</strong><div class="burger" id="b"><span></span><span></span><span></span></div></div><div class="overlay" id="o"><div class="pane pane--l"></div><div class="pane pane--r"></div><nav class="nav"><div><a href="#">Work</a><a href="#">Studio</a><a href="#">News</a><a href="#">Contact</a></div></nav></div>`,
    script: `const b=document.getElementById('b'),o=document.getElementById('o');b.onclick=()=>{b.classList.toggle('open');o.classList.toggle('open');};`,
  }),

  'menu-fullscreen-curtain': () => ({
    style: `body{margin:0;min-height:100vh;background:#fafafa;color:#111;${base}}${reduced}.bar{display:flex;justify-content:space-between;align-items:center;padding:1.2rem 2rem;position:relative;z-index:30}.logo{font-weight:800}.burger{width:30px;height:20px;cursor:pointer;display:flex;flex-direction:column;justify-content:center;gap:5px;z-index:30}.burger span{height:2px;background:#111;transition:transform .35s,opacity .35s}.burger.open span:nth-child(1){transform:translateY(7px) rotate(45deg)}.burger.open span:nth-child(2){opacity:0}.burger.open span:nth-child(3){transform:translateY(-7px) rotate(-45deg)}.curtain{position:fixed;inset:0;background:#000;z-index:20;transform:translateY(-100%);transition:transform .6s cubic-bezier(.22,.61,.36,1);display:grid;place-items:center}.curtain.open{transform:translateY(0)}.curtain a{display:block;font-size:clamp(2rem,6vw,2.8rem);font-weight:800;color:#fff;text-decoration:none;padding:.45rem;opacity:0;transform:translateY(-24px);transition:opacity .4s,transform .4s}.curtain.open a{opacity:1;transform:none}.curtain.open a:nth-child(1){transition-delay:.25s}.curtain.open a:nth-child(2){transition-delay:.35s}.curtain.open a:nth-child(3){transition-delay:.45s}`,
    body: `<div class="bar"><strong class="logo">Brand</strong><div class="burger" id="b"><span></span><span></span><span></span></div></div><div class="curtain" id="c"><div><a href="#">Projects</a><a href="#">About</a><a href="#">Contact</a></div></div>`,
    script: `const b=document.getElementById('b'),c=document.getElementById('c');b.onclick=()=>{b.classList.toggle('open');c.classList.toggle('open');};`,
  }),

  'menu-fullscreen-stagger-lines': () => ({
    style: `body{margin:0;min-height:100vh;background:#fff;color:#111;${base}}${reduced}.head{display:flex;justify-content:space-between;padding:1.4rem 2rem;position:relative;z-index:30}.logo{font-weight:800}.burger{cursor:pointer;font-size:.75rem;letter-spacing:.14em;text-transform:uppercase;font-weight:600;z-index:30}.menu{position:fixed;inset:0;background:#000;z-index:20;display:flex;flex-direction:column;justify-content:center;padding:4rem;clip-path:inset(0 0 100% 0);transition:clip-path .55s cubic-bezier(.22,.61,.36,1)}.menu.open{clip-path:inset(0)}.menu a{font-size:clamp(2.4rem,7vw,4.2rem);font-weight:900;color:#fff;text-decoration:none;line-height:1.15;overflow:hidden;display:block}.menu a span{display:block;transform:translateY(110%);transition:transform .5s cubic-bezier(.22,.61,.36,1)}.menu.open a span{transform:none}.menu.open a:nth-child(1) span{transition-delay:.12s}.menu.open a:nth-child(2) span{transition-delay:.2s}.menu.open a:nth-child(3) span{transition-delay:.28s}.menu.open a:nth-child(4) span{transition-delay:.36s}`,
    body: `<div class="head"><strong class="logo">AGENCY</strong><div class="burger" id="b">Menu</div></div><div class="menu" id="m"><a href="#"><span>Work</span></a><a href="#"><span>Services</span></a><a href="#"><span>Team</span></a><a href="#"><span>Contact</span></a></div>`,
    script: `const b=document.getElementById('b'),m=document.getElementById('m');b.onclick=()=>m.classList.toggle('open');`,
  }),

  'menu-fullscreen-blur-glass': () => ({
    style: `body{margin:0;min-height:100vh;background:linear-gradient(135deg,#ccc 0%,#999 50%,#bbb 100%);color:#fff;${base}}${reduced}.bar{display:flex;justify-content:space-between;align-items:center;padding:1.4rem 2rem;position:relative;z-index:30}.logo{font-weight:800;color:#111}.burger{width:28px;height:18px;cursor:pointer;z-index:30}.burger span{display:block;height:2px;background:#111;margin:5px 0;transition:transform .3s,opacity .3s}.burger.open span:nth-child(1){transform:translateY(7px) rotate(45deg)}.burger.open span:nth-child(2){opacity:0}.burger.open span:nth-child(3){transform:translateY(-7px) rotate(-45deg)}.overlay{position:fixed;inset:0;background:rgba(255,255,255,.35);backdrop-filter:blur(24px);-webkit-backdrop-filter:blur(24px);z-index:20;display:grid;place-items:center;opacity:0;pointer-events:none;transition:opacity .4s}.overlay.open{opacity:1;pointer-events:auto}.links{text-align:center}.links a{display:block;font-size:2rem;font-weight:700;text-decoration:none;color:#111;padding:.7rem;opacity:0;transform:scale(.92);transition:opacity .35s,transform .35s}.overlay.open a{opacity:1;transform:none}.overlay.open a:nth-child(1){transition-delay:.08s}.overlay.open a:nth-child(2){transition-delay:.16s}.overlay.open a:nth-child(3){transition-delay:.24s}`,
    body: `<div class="bar"><strong class="logo">Lens</strong><div class="burger" id="b"><span></span><span></span><span></span></div></div><div class="overlay" id="o"><div class="links"><a href="#">Gallery</a><a href="#">Journal</a><a href="#">About</a></div></div>`,
    script: `const b=document.getElementById('b'),o=document.getElementById('o');b.onclick=()=>{b.classList.toggle('open');o.classList.toggle('open');};`,
  }),

  'menu-fullscreen-circle-expand': () => ({
    style: `body{margin:0;min-height:100vh;background:#f5f5f5;color:#111;${base}}${reduced}.nav{display:flex;justify-content:space-between;padding:1.4rem 2rem;position:relative;z-index:30}.logo{font-weight:800}.burger{width:44px;height:44px;border-radius:50%;background:#000;cursor:pointer;z-index:30;display:grid;place-items:center}.burger span{display:block;width:18px;height:2px;background:#fff;margin:3px 0;transition:transform .35s,opacity .35s}.burger.open span:nth-child(1){transform:translateY(5px) rotate(45deg)}.burger.open span:nth-child(2){opacity:0}.burger.open span:nth-child(3){transform:translateY(-5px) rotate(-45deg)}.expand{position:fixed;inset:0;z-index:20;pointer-events:none}.expand .bg{position:absolute;width:44px;height:44px;border-radius:50%;background:#000;top:1.4rem;right:2rem;transform:scale(0);transform-origin:top right;transition:transform .65s cubic-bezier(.22,.61,.36,1)}.expand.open{pointer-events:auto}.expand.open .bg{transform:scale(40)}.links{position:absolute;inset:0;display:grid;place-items:center;opacity:0;transition:opacity .3s .15s;z-index:1}.expand.open .links{opacity:1}.links a{display:block;font-size:2.2rem;font-weight:800;color:#fff;text-decoration:none;padding:.4rem;opacity:0;transform:translateY(12px);transition:opacity .35s,transform .35s}.expand.open a{opacity:1;transform:none}.expand.open a:nth-child(1){transition-delay:.2s}.expand.open a:nth-child(2){transition-delay:.28s}.expand.open a:nth-child(3){transition-delay:.36s}`,
    body: `<div class="nav"><strong class="logo">Orbit</strong><div class="burger" id="b"><span></span><span></span><span></span></div></div><div class="expand" id="e"><div class="bg"></div><div class="links"><div><a href="#">Home</a><a href="#">Work</a><a href="#">Contact</a></div></div></div>`,
    script: `const b=document.getElementById('b'),e=document.getElementById('e');b.onclick=()=>{b.classList.toggle('open');e.classList.toggle('open');};`,
  }),
};

module.exports = { RECIPES, extractNavDesc };
