const IMG = '../stock/media/16-9 Aspect Ratio(image).png';
const IMG45 = '../stock/media/4-5 Aspect Ratio(image).png';
const VID = '../stock/media/16-9 Aspect Ratio(video).mp4';
const { RECIPES: navRecipes } = require('./navigation');

function navMenu(slug, title, tags) {
  const r = navRecipes[slug]();
  return { slug, title, category: 'navigation', tags, style: r.style, body: r.body, script: r.script || '' };
}

const cards5 = (cls = 'card') => Array.from({ length: 5 }, (_, i) =>
  `<div class="${cls}"><img src="${IMG45}" alt="Photo ${i + 1}"></div>`
).join('');

module.exports = [
  // ── Image stack & spread ──
  { slug: 'stack-image-hover-spread', title: 'Image Stack Hover Spread', category: 'stack-gallery', tags: ['stack', 'images', 'hover', 'spread'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#0d0d0f;padding:2rem}.stack{position:relative;width:min(280px,80vw);aspect-ratio:4/5;cursor:pointer}.card{position:absolute;inset:0;border-radius:16px;overflow:hidden;box-shadow:0 20px 50px rgba(0,0,0,.4);transition:transform .55s cubic-bezier(.22,.61,.36,1)}.card img{width:100%;height:100%;object-fit:cover}.card:nth-child(1){z-index:5;transform:rotate(-2deg)}.card:nth-child(2){z-index:4;transform:translateY(10px) scale(.97) rotate(1deg)}.card:nth-child(3){z-index:3;transform:translateY(20px) scale(.94)}.card:nth-child(4){z-index:2;transform:translateY(30px) scale(.91)}.card:nth-child(5){z-index:1;transform:translateY(40px) scale(.88)}.stack:hover .card:nth-child(1){transform:translateX(-90px) rotate(-12deg)}.stack:hover .card:nth-child(2){transform:translateX(-45px) rotate(-5deg)}.stack:hover .card:nth-child(3){transform:translateY(-15px) scale(1.02)}.stack:hover .card:nth-child(4){transform:translateX(45px) rotate(5deg)}.stack:hover .card:nth-child(5){transform:translateX(90px) rotate(12deg)}`,
    body: `<div class="stack">${cards5()}</div>` },

  { slug: 'stack-image-scroll-fan', title: 'Scroll Image Fan Spread', category: 'stack-gallery', tags: ['stack', 'images', 'scroll', 'fan'],
    style: `body{margin:0;background:#111;color:#fff}.scene{height:300vh}.stage{position:sticky;top:0;height:100vh;display:grid;place-items:center;overflow:hidden}.deck{position:relative;width:min(260px,70vw);aspect-ratio:4/5}.card{position:absolute;inset:0;border-radius:14px;overflow:hidden;box-shadow:0 16px 40px rgba(0,0,0,.5);will-change:transform}.card img{width:100%;height:100%;object-fit:cover}`,
    body: `<div class="scene"><div class="stage"><div class="deck">${cards5()}</div></div></div>`,
    script: `const cards=[...document.querySelectorAll('.card')];const scene=document.querySelector('.scene');function u(){const r=scene.getBoundingClientRect();const p=Math.min(1,Math.max(0,-r.top/(r.height-innerHeight)));cards.forEach((c,i)=>{const o=i-(cards.length-1)/2;const spread=o*110*p;const rot=o*14*p;c.style.transform='translateX('+spread+'px) rotate('+rot+'deg) translateY('+(i*6*(1-p))+'px) scale('+(0.88+i*.03+p*.1)+')';c.style.zIndex=i+1;});}addEventListener('scroll',u,{passive:true});u();` },

  { slug: 'stack-gallery-click-cycle', title: 'Gallery Stack Click Cycle', category: 'stack-gallery', tags: ['stack', 'gallery', 'images', 'click'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#f5f5f5;padding:2rem}.wrap{text-align:center}.stack{position:relative;width:min(300px,85vw);aspect-ratio:4/5;margin:0 auto 1rem;cursor:pointer}.card{position:absolute;inset:0;border-radius:18px;overflow:hidden;transition:transform .5s cubic-bezier(.22,.61,.36,1),opacity .4s;box-shadow:0 12px 36px rgba(0,0,0,.15)}.card img{width:100%;height:100%;object-fit:cover}.hint{font-size:.85rem;color:#888}`,
    body: `<div class="wrap"><div class="stack" id="s">${cards5()}</div><p class="hint">Click to cycle through the gallery</p></div>`,
    script: `const s=document.getElementById('s');const cards=[...s.children];let top=0;function layout(){cards.forEach((c,i)=>{const pos=(i-top+cards.length)%cards.length;c.style.zIndex=cards.length-pos;c.style.transform='translateY('+(pos*8)+'px) scale('+(1-pos*.04)+') rotate('+(pos*2-4)+'deg)';c.style.opacity=pos>3?0:1;});}s.onclick=()=>{top=(top+1)%cards.length;layout();};layout();` },

  { slug: 'stack-scroll-polaroid-wall', title: 'Polaroid Scroll Wall', category: 'stack-gallery', tags: ['stack', 'polaroid', 'scroll', 'images'],
    style: `body{margin:0;background:#e8e4dc;padding:20vh 2rem 80vh;font-family:Georgia,serif}.wall{max-width:900px;margin:0 auto;display:grid;grid-template-columns:repeat(3,1fr);gap:2rem}.pol{position:sticky;top:calc(15vh + var(--i)*12px);background:#fff;padding:12px 12px 40px;box-shadow:0 8px 30px rgba(0,0,0,.12);transform:rotate(var(--r));transition:transform .4s}.pol img{width:100%;aspect-ratio:1;object-fit:cover;display:block}.pol span{display:block;text-align:center;margin-top:10px;font-size:.85rem;color:#666}`,
    body: `<div class="wall">${['Venice','Tokyo','Paris','NYC','London','Sydney'].map((t,i)=>`<div class="pol" style="--i:${i};--r:${(i%3-1)*4}deg"><img src="${IMG45}" alt=""><span>${t}</span></div>`).join('')}</div>` },

  { slug: 'stack-image-arc-gallery', title: 'Arc Image Gallery Spread', category: 'stack-gallery', tags: ['stack', 'arc', 'gallery', 'images'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#0a0a0c;padding:2rem;overflow:hidden}.gallery{position:relative;width:100%;max-width:700px;height:min(420px,70vh)}.card{position:absolute;left:50%;top:50%;width:min(180px,28vw);aspect-ratio:4/5;border-radius:14px;overflow:hidden;box-shadow:0 20px 50px rgba(0,0,0,.45);transform:translate(-50%,-50%);transition:transform .6s cubic-bezier(.22,.61,.36,1)}.card img{width:100%;height:100%;object-fit:cover}.gallery:hover .card{transform:translate(-50%,-50%) rotate(var(--a)) translateY(var(--y))}`,
    body: `<div class="gallery">${[-24,-12,0,12,24].map((a,i)=>`<div class="card" style="--a:${a}deg;--y:${-80-Math.abs(a)*2}px;z-index:${5-Math.abs(a)}"><img src="${IMG45}" alt=""></div>`).join('')}</div>` },

  { slug: 'stack-scroll-horizontal-strip', title: 'Stack to Horizontal Strip', category: 'stack-gallery', tags: ['stack', 'horizontal', 'scroll', 'images'],
    style: `body{margin:0;background:#000}.pin{height:350vh}.sticky{position:sticky;top:0;height:100vh;display:grid;place-items:center;overflow:hidden}.track{display:flex;gap:20px;align-items:center;will-change:transform;padding:0 10vw}.card{flex:0 0 min(220px,40vw);aspect-ratio:4/5;border-radius:16px;overflow:hidden;box-shadow:0 20px 60px rgba(0,0,0,.5)}.card img{width:100%;height:100%;object-fit:cover}`,
    body: `<div class="pin"><div class="sticky"><div class="track" id="t">${cards5()}</div></div></div>`,
    script: `const pin=document.querySelector('.pin'),t=document.getElementById('t');function u(){const r=pin.getBoundingClientRect();const p=Math.min(1,Math.max(0,-r.top/(r.height-innerHeight)));const max=t.scrollWidth-innerWidth*.5;t.style.transform='translateX('+(-p*max)+'px)';}addEventListener('scroll',u,{passive:true});u();` },

  { slug: 'stack-image-deck-drag', title: 'Image Deck Drag Spread', category: 'stack-gallery', tags: ['stack', 'deck', 'drag', 'images'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#1a1a2e;padding:2rem;overflow:hidden}.deck{position:relative;width:min(260px,75vw);aspect-ratio:4/5;touch-action:none}.card{position:absolute;inset:0;border-radius:16px;overflow:hidden;cursor:grab;box-shadow:0 16px 40px rgba(0,0,0,.35);transition:transform .35s cubic-bezier(.22,.61,.36,1)}.card:active{cursor:grabbing}.card img{width:100%;height:100%;object-fit:cover}.card.top{transition:transform .4s cubic-bezier(.22,.61,.36,1)}`,
    body: `<div class="deck" id="d">${cards5()}</div><p style="position:fixed;bottom:1.5rem;left:0;right:0;text-align:center;color:#666;font-size:.8rem">Drag top card to spread</p>`,
    script: `const d=document.getElementById('d');let cards=[...d.children].reverse();function layout(){cards.forEach((c,i)=>{c.style.zIndex=i;c.classList.toggle('top',i===cards.length-1);if(i<cards.length-1)c.style.transform='translateY('+(cards.length-1-i)*6+'px) scale('+(1-(cards.length-1-i)*.03)+')';else c.style.transform='';});bind();}let drag=false,sx=0,active=null;function bind(){const top=cards[cards.length-1];top.onpointerdown=e=>{drag=true;active=top;sx=e.clientX;top.setPointerCapture(e.pointerId);};top.onpointermove=e=>{if(!drag||active!==top)return;const dx=e.clientX-sx;top.style.transform='translateX('+dx+'px) rotate('+(dx*.05)+'deg)';};top.onpointerup=e=>{if(!drag||active!==top)return;drag=false;const dx=e.clientX-sx;if(Math.abs(dx)>80){top.style.transform='translateX('+(dx>0?400:-400)+'px) rotate('+(dx*.15)+'deg)';setTimeout(()=>{cards=[top,...cards.filter(c=>c!==top)];cards.forEach(c=>c.style.transform='');layout();},300);}else top.style.transform='';active=null;};}layout();` },

  { slug: 'stack-masonry-reveal', title: 'Masonry Stack Reveal', category: 'stack-gallery', tags: ['stack', 'masonry', 'gallery', 'reveal'],
    style: `body{margin:0;background:#fafafa;padding:3rem 2rem 6rem}.grid{max-width:900px;margin:0 auto;columns:3;column-gap:16px}.item{break-inside:avoid;margin-bottom:16px;border-radius:12px;overflow:hidden;opacity:0;transform:translateY(30px);transition:opacity .7s cubic-bezier(.22,.61,.36,1),transform .7s cubic-bezier(.22,.61,.36,1)}.item.vis{opacity:1;transform:none}.item img{width:100%;display:block}.item:nth-child(3n+2){margin-top:24px}`,
    body: `<div class="grid">${Array.from({length:9},(_,i)=>`<div class="item"><img src="${i%2?IMG45:IMG}" alt="" style="aspect-ratio:${i%3?'4/5':'16/10'};object-fit:cover;width:100%"></div>`).join('')}</div>`,
    script: `const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('vis')}),{threshold:.15});document.querySelectorAll('.item').forEach((el,i)=>{el.style.transitionDelay=i*.08+'s';obs.observe(el);});` },

  // ── Professional & animated timelines ──
  { slug: 'timeline-pro-vertical', title: 'Pro Vertical Timeline', category: 'timeline', tags: ['timeline', 'vertical', 'professional'],
    style: `body{margin:0;background:#fafafa;color:#111;padding:4rem 2rem;font-family:system-ui,sans-serif}.wrap{max-width:640px;margin:0 auto}.head{margin-bottom:3rem}.head h2{font-size:1.75rem;font-weight:700;margin-bottom:.35rem}.head p{color:#666;font-size:.95rem}.timeline{position:relative;padding-left:2.5rem}.timeline::before{content:'';position:absolute;left:11px;top:8px;bottom:8px;width:2px;background:linear-gradient(180deg,#6c8cff,#ff6cb0)}.item{position:relative;padding:0 0 2.5rem 1.5rem}.dot{position:absolute;left:-2.5rem;top:4px;width:24px;height:24px;border-radius:50%;background:#fff;border:3px solid #6c8cff;box-shadow:0 0 0 4px rgba(108,140,255,.15)}.item h4{font-size:1rem;font-weight:700;margin-bottom:.25rem}.meta{font-size:.75rem;color:#6c8cff;font-weight:600;letter-spacing:.04em;text-transform:uppercase;margin-bottom:.5rem}.item p{color:#666;font-size:.9rem;line-height:1.6}`,
    body: `<div class="wrap"><div class="head"><h2>Product roadmap</h2><p>Milestones that shaped the release</p></div><div class="timeline">${[['Q1 2025','Research','User interviews and competitive audit'],['Q2 2025','Design','Design system and prototype testing'],['Q3 2025','Build','Core platform and integrations'],['Q4 2025','Launch','Public release and onboarding']].map(([m,t,d])=>`<div class="item"><div class="dot"></div><div class="meta">${m}</div><h4>${t}</h4><p>${d}</p></div>`).join('')}</div></div>` },

  { slug: 'timeline-pro-horizontal', title: 'Pro Horizontal Timeline', category: 'timeline', tags: ['timeline', 'horizontal', 'professional'],
    style: `body{margin:0;background:#0d0d0f;color:#fff;padding:4rem 2rem;font-family:system-ui,sans-serif}.wrap{max-width:960px;margin:0 auto}.head{text-align:center;margin-bottom:3rem}.head h2{font-size:1.75rem;font-weight:700}.head p{color:#666;margin-top:.5rem}.rail{display:flex;gap:0;overflow-x:auto;padding:2rem 0;scrollbar-width:none}.rail::-webkit-scrollbar{display:none}.step{flex:0 0 200px;text-align:center;position:relative;padding-top:2rem}.step::before{content:'';position:absolute;top:28px;left:50%;right:-50%;height:2px;background:#2a2a32;z-index:0}.step:last-child::before{display:none}.node{width:56px;height:56px;border-radius:50%;background:linear-gradient(135deg,#6c8cff,#764ba2);display:grid;place-items:center;margin:0 auto 1rem;font-weight:800;font-size:.9rem;position:relative;z-index:1;box-shadow:0 8px 24px rgba(108,140,255,.35)}.step h4{font-size:.95rem;font-weight:600;margin-bottom:.35rem}.step p{font-size:.8rem;color:#888;line-height:1.5;padding:0 .5rem}`,
    body: `<div class="wrap"><div class="head"><h2>Growth milestones</h2><p>From idea to scale</p></div><div class="rail">${[['01','Ideation','Problem validation'],['02','MVP','First paying users'],['03','Growth','Series A funding'],['04','Scale','Global expansion'],['05','Leader','Category defining']].map(([n,t,d])=>`<div class="step"><div class="node">${n}</div><h4>${t}</h4><p>${d}</p></div>`).join('')}</div></div>` },

  { slug: 'timeline-stepper-next', title: 'Animated Stepper Timeline', category: 'timeline', tags: ['timeline', 'animated', 'stepper', 'progress'],
    style: `body{margin:0;min-height:100vh;background:#fff;color:#111;display:grid;place-items:center;padding:2rem;font-family:system-ui,sans-serif}.panel{width:min(520px,100%);padding:2rem;border-radius:20px;border:1px solid #eee;box-shadow:0 8px 40px rgba(0,0,0,.06)}.steps{display:flex;justify-content:space-between;margin-bottom:2rem;position:relative}.steps::before{content:'';position:absolute;top:14px;left:0;right:0;height:2px;background:#e5e5e5}.progress{position:absolute;top:14px;left:0;height:2px;background:#6c8cff;transition:width .5s cubic-bezier(.22,.61,.36,1);width:0}.dot{width:30px;height:30px;border-radius:50%;background:#fff;border:2px solid #ddd;display:grid;place-items:center;font-size:.7rem;font-weight:700;position:relative;z-index:1;transition:border-color .3s,background .3s,color .3s}.dot.on{border-color:#6c8cff;background:#6c8cff;color:#fff}.dot.done{border-color:#6c8cff;color:#6c8cff}.content{min-height:120px;margin-bottom:1.5rem}.content h3{font-size:1.25rem;margin-bottom:.5rem}.content p{color:#666;line-height:1.6;font-size:.95rem}.actions{display:flex;gap:.75rem}.btn{padding:10px 20px;border-radius:8px;border:none;font-weight:600;font-size:.9rem;cursor:pointer}.next{background:#6c8cff;color:#fff}.next:disabled{opacity:.4;cursor:not-allowed}.back{background:#f5f5f5;color:#333}`,
    body: `<div class="panel"><div class="steps"><div class="progress" id="p"></div>${[1,2,3,4].map(i=>`<div class="dot" data-i="${i-1}">${i}</div>`).join('')}</div><div class="content" id="c"></div><div class="actions"><button class="back" id="back">Back</button><button class="next" id="next">Next →</button></div></div>`,
    script: `const steps=[{t:'Discovery',d:'Research user needs and define project scope.'},{t:'Design',d:'Create wireframes, prototypes, and visual direction.'},{t:'Development',d:'Build core features with performance in mind.'},{t:'Launch',d:'Ship to production and monitor key metrics.'}];let cur=0;const dots=[...document.querySelectorAll('.dot')],c=document.getElementById('c'),p=document.getElementById('p'),next=document.getElementById('next'),back=document.getElementById('back');function render(){c.innerHTML='<h3>'+steps[cur].t+'</h3><p>'+steps[cur].d+'</p>';dots.forEach((d,i)=>{d.classList.toggle('on',i===cur);d.classList.toggle('done',i<cur);});p.style.width=(cur/(steps.length-1)*100)+'%';back.disabled=cur===0;next.textContent=cur===steps.length-1?'Finish':'Next →';}next.onclick=()=>{if(cur<steps.length-1){cur++;render();}};back.onclick=()=>{if(cur>0){cur--;render();}};render();` },

  { slug: 'timeline-progress-rail', title: 'Progress Rail Timeline', category: 'timeline', tags: ['timeline', 'progress', 'rail', 'animated'],
    style: `body{margin:0;min-height:100vh;background:#0d0d0f;color:#fff;display:grid;place-items:center;padding:2rem}.card{width:min(560px,100%);background:#16161a;border-radius:20px;padding:2rem;border:1px solid #2a2a32}.rail{position:relative;height:4px;background:#2a2a32;border-radius:99px;margin:2rem 0;overflow:hidden}.fill{height:100%;width:0;background:linear-gradient(90deg,#6c8cff,#6cffb8);border-radius:99px;transition:width .6s cubic-bezier(.22,.61,.36,1)}.milestones{display:flex;justify-content:space-between;margin-bottom:2rem}.m{text-align:center;flex:1;opacity:.4;transition:opacity .4s}.m.on{opacity:1}.m .yr{font-size:.7rem;color:#6c8cff;letter-spacing:.08em}.m h4{font-size:.85rem;margin-top:.25rem}.detail{min-height:80px}.detail h3{font-size:1.2rem;margin-bottom:.5rem}.detail p{color:#888;font-size:.9rem;line-height:1.6}.ctrl{display:flex;justify-content:flex-end;gap:.5rem}.btn{width:40px;height:40px;border-radius:50%;border:1px solid #333;background:transparent;color:#fff;cursor:pointer;font-size:1rem}.btn:hover{border-color:#6c8cff;color:#6c8cff}`,
    body: `<div class="card"><div class="milestones" id="ms">${[['2023','Founded'],['2024','Seed'],['2025','Series A'],['2026','Global']].map(([y,t],i)=>`<div class="m" data-i="${i}"><div class="yr">${y}</div><h4>${t}</h4></div>`).join('')}</div><div class="rail"><div class="fill" id="f"></div></div><div class="detail" id="d"></div><div class="ctrl"><button class="btn" id="prev">←</button><button class="btn" id="fwd">→</button></div></div>`,
    script: `const data=[{t:'Founded',d:'Started in a small studio with a vision for better web tools.'},{t:'Seed round',d:'Raised funding to expand the team and ship v1.'},{t:'Series A',d:'Scaled to 50k users across 12 countries.'},{t:'Global',d:'Opened offices and launched enterprise tier.'}];let i=0;const ms=[...document.querySelectorAll('.m')],f=document.getElementById('f'),d=document.getElementById('d');function go(n){i=Math.max(0,Math.min(data.length-1,n));f.style.width=(i/(data.length-1)*100)+'%';ms.forEach((m,j)=>m.classList.toggle('on',j<=i));d.innerHTML='<h3>'+data[i].t+'</h3><p>'+data[i].d+'</p>';}document.getElementById('fwd').onclick=()=>go(i+1);document.getElementById('prev').onclick=()=>go(i-1);go(0);` },

  { slug: 'timeline-card-milestones', title: 'Card Milestone Timeline', category: 'timeline', tags: ['timeline', 'cards', 'milestones'],
    style: `body{margin:0;background:linear-gradient(180deg,#f8fafc,#eef2ff);padding:4rem 2rem;font-family:system-ui,sans-serif}.wrap{max-width:700px;margin:0 auto}.wrap h2{font-size:1.75rem;font-weight:800;text-align:center;margin-bottom:2.5rem;color:#0f172a}.list{display:flex;flex-direction:column;gap:1rem}.card{display:grid;grid-template-columns:auto 1fr;gap:1.25rem;padding:1.25rem 1.5rem;background:#fff;border-radius:14px;border:1px solid #e2e8f0;box-shadow:0 4px 20px rgba(15,23,42,.04);align-items:start}.badge{width:48px;height:48px;border-radius:12px;background:linear-gradient(135deg,#6c8cff,#4a5fd4);color:#fff;display:grid;place-items:center;font-weight:800;font-size:.85rem;flex-shrink:0}.card h4{font-size:1rem;font-weight:700;color:#0f172a;margin-bottom:.25rem}.card p{font-size:.88rem;color:#64748b;line-height:1.55}.date{font-size:.72rem;color:#6c8cff;font-weight:600;text-transform:uppercase;letter-spacing:.06em}`,
    body: `<div class="wrap"><h2>Delivery timeline</h2><div class="list">${[['WK1','Kickoff','Align on goals and success metrics','Mar 3'],['WK4','Alpha','Internal testing with core flows','Mar 24'],['WK8','Beta','Invite-only release to early users','Apr 21'],['WK12','Launch','Public release with marketing push','May 19']].map(([b,t,d,dt])=>`<div class="card"><div class="badge">${b}</div><div><div class="date">${dt}</div><h4>${t}</h4><p>${d}</p></div></div>`).join('')}</div></div>` },

  { slug: 'timeline-interactive-dots', title: 'Interactive Dot Timeline', category: 'timeline', tags: ['timeline', 'dots', 'interactive'],
    style: `body{margin:0;min-height:100vh;background:#111;color:#fff;display:grid;place-items:center;padding:2rem}.box{width:min(500px,100%)}.dots{display:flex;align-items:center;justify-content:center;gap:0;margin-bottom:2rem}.dots .line{flex:1;height:2px;background:#333;max-width:60px;transition:background .4s}.dots .line.on{background:#6c8cff}.dot{width:14px;height:14px;border-radius:50%;background:#333;border:2px solid #444;cursor:pointer;transition:all .35s cubic-bezier(.22,.61,.36,1);flex-shrink:0}.dot.on{background:#6c8cff;border-color:#6c8cff;box-shadow:0 0 0 6px rgba(108,140,255,.25);transform:scale(1.2)}.dot.done{background:#6c8cff;border-color:#6c8cff}.panel{background:#1a1a2e;border-radius:16px;padding:2rem;min-height:140px;border:1px solid #2a2a40}.panel h3{font-size:1.2rem;margin-bottom:.5rem}.panel p{color:#888;font-size:.9rem;line-height:1.6}`,
    body: `<div class="box"><div class="dots" id="dots"></div><div class="panel" id="panel"></div></div>`,
    script: `const items=[{t:'Plan',d:'Define scope, timeline, and deliverables.'},{t:'Create',d:'Design and build the core experience.'},{t:'Test',d:'QA, user testing, and iteration.'},{t:'Ship',d:'Deploy and measure success.'}];const dotsEl=document.getElementById('dots'),panel=document.getElementById('panel');let active=0;function build(){dotsEl.innerHTML=items.map((_,i)=>(i>0?'<div class="line"></div>':'')+'<div class="dot" data-i="'+i+'"></div>').join('');[...dotsEl.querySelectorAll('.dot')].forEach(d=>d.onclick=()=>{active=+d.dataset.i;render();});render();}function render(){const dots=[...dotsEl.querySelectorAll('.dot')];const lines=[...dotsEl.querySelectorAll('.line')];dots.forEach((d,i)=>{d.classList.toggle('on',i===active);d.classList.toggle('done',i<active);});lines.forEach((l,i)=>l.classList.toggle('on',i<active));panel.innerHTML='<h3>'+items[active].t+'</h3><p>'+items[active].d+'</p>';}build();` },

  // ── Dot components ──
  { slug: 'dots-pulse-loader', title: 'Pulse Dot Loader', category: 'dots', tags: ['dots', 'loader', 'pulse'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#0d0d0f}.loader{display:flex;gap:10px}.dot{width:12px;height:12px;border-radius:50%;background:#6c8cff;animation:pulse 1.2s ease-in-out infinite}.dot:nth-child(2){animation-delay:.15s;background:#ff6cb0}.dot:nth-child(3){animation-delay:.3s;background:#6cffb8}@keyframes pulse{0%,80%,100%{transform:scale(.6);opacity:.4}40%{transform:scale(1);opacity:1}}`,
    body: `<div class="loader"><div class="dot"></div><div class="dot"></div><div class="dot"></div></div>` },

  { slug: 'dots-orbit-spinner', title: 'Orbit Dot Spinner', category: 'dots', tags: ['dots', 'orbit', 'spinner'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#fafafa}.orbit{width:64px;height:64px;position:relative;animation:spin 1.4s linear infinite}@keyframes spin{to{transform:rotate(360deg)}}.dot{position:absolute;width:10px;height:10px;border-radius:50%;background:#6c8cff;top:0;left:50%;margin-left:-5px;box-shadow:0 0 12px rgba(108,140,255,.6)}.dot:nth-child(2){top:auto;bottom:0;background:#ff6cb0;box-shadow:0 0 12px rgba(255,108,176,.6)}.dot:nth-child(3){top:50%;left:0;margin:0;margin-top:-5px;background:#6cffb8}`,
    body: `<div class="orbit"><div class="dot"></div><div class="dot"></div><div class="dot"></div></div>` },

  { slug: 'dots-step-pips', title: 'Step Pip Dots', category: 'dots', tags: ['dots', 'steps', 'pips'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#fff;padding:2rem}.wrap{text-align:center}.pips{display:flex;gap:8px;justify-content:center;margin-bottom:2rem}.pip{width:8px;height:8px;border-radius:50%;background:#ddd;cursor:pointer;transition:all .35s cubic-bezier(.22,.61,.36,1)}.pip.on{width:28px;border-radius:99px;background:#6c8cff}.panel{width:min(360px,90vw);padding:2rem;border-radius:16px;background:#f8f8f8}.panel h3{font-size:1.1rem;margin-bottom:.35rem}.panel p{color:#666;font-size:.9rem}`,
    body: `<div class="wrap"><div class="pips" id="pips"></div><div class="panel" id="panel"></div></div>`,
    script: `const slides=['Upload files','Review details','Confirm payment','Done'];let i=0;const pips=document.getElementById('pips'),panel=document.getElementById('panel');function r(){pips.innerHTML=slides.map((_,j)=>'<div class="pip'+(j===i?' on':'')+'" data-j="'+j+'"></div>').join('');panel.innerHTML='<h3>'+slides[i]+'</h3><p>Step '+(i+1)+' of '+slides.length+'</p>';[...pips.children].forEach(p=>p.onclick=()=>{i=+p.dataset.j;r();});setInterval(()=>{i=(i+1)%slides.length;r();},2500);}r();` },

  { slug: 'dots-connecting-network', title: 'Connecting Dot Network', category: 'dots', tags: ['dots', 'network', 'canvas'],
    style: `body{margin:0;min-height:100vh;background:#0a0a0c;overflow:hidden}canvas{display:block}`,
    body: `<canvas id="c"></canvas>`,
    script: `const c=document.getElementById('c'),x=c.getContext('2d');let pts=[],mx=0,my=0;function r(){c.width=innerWidth;c.height=innerHeight;pts=Array.from({length:55},()=>({x:Math.random()*c.width,y:Math.random()*c.height,vx:(Math.random()-.5)*.4,vy:(Math.random()-.5)*.4}));}r();addEventListener('resize',r);addEventListener('mousemove',e=>{mx=e.clientX;my=e.clientY;});function d(){x.clearRect(0,0,c.width,c.height);pts.forEach(p=>{p.x+=p.vx;p.y+=p.vy;if(p.x<0||p.x>c.width)p.vx*=-1;if(p.y<0||p.y>c.height)p.vy*=-1;const dx=p.x-mx,dy=p.y-my,d=Math.hypot(dx,dy);if(d<120){p.x+=dx/d*2;p.y+=dy/d*2;}});for(let i=0;i<pts.length;i++)for(let j=i+1;j<pts.length;j++){const a=pts[i],b=pts[j],dist=Math.hypot(a.x-b.x,a.y-b.y);if(dist<130){x.strokeStyle='rgba(108,140,255,'+(1-dist/130)*.35+')';x.beginPath();x.moveTo(a.x,a.y);x.lineTo(b.x,b.y);x.stroke();}}pts.forEach(p=>{x.fillStyle='#6c8cff';x.beginPath();x.arc(p.x,p.y,2.5,0,Math.PI*2);x.fill();});requestAnimationFrame(d);}d();` },

  { slug: 'dots-magnetic-cluster', title: 'Magnetic Dot Cluster', category: 'dots', tags: ['dots', 'magnetic', 'interactive'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#111;overflow:hidden}.field{position:relative;width:min(400px,90vw);height:min(400px,70vh)}.dot{position:absolute;width:var(--s,12px);height:var(--s,12px);border-radius:50%;background:var(--c,#6c8cff);transition:transform .15s ease-out;box-shadow:0 0 20px var(--c,#6c8cff)}`,
    body: `<div class="field" id="f">${Array.from({length:24},(_,i)=>`<div class="dot" style="--c:${['#6c8cff','#ff6cb0','#6cffb8'][i%3]};--s:${8+Math.random()*8}px;left:${20+Math.random()*60}%;top:${20+Math.random()*60}%"></div>`).join('')}</div>`,
    script: `const f=document.getElementById('f');const dots=[...f.querySelectorAll('.dot')];f.onmousemove=e=>{const r=f.getBoundingClientRect();const mx=e.clientX-r.left,my=e.clientY-r.top;dots.forEach(d=>{const dr=d.getBoundingClientRect();const dx=dr.left+dr.width/2-r.left-mx,dy=dr.top+dr.height/2-r.top-my;const dist=Math.hypot(dx,dy);const push=Math.max(0,80-dist);d.style.transform='translate('+(dx/dist*push||0)+'px,'+(dy/dist*push||0)+'px)';});};f.onmouseleave=()=>dots.forEach(d=>d.style.transform='');` },

  { slug: 'dots-status-indicator', title: 'Status Dot Indicator', category: 'dots', tags: ['dots', 'status', 'indicator'],
    style: `body{display:grid;place-items:center;min-height:100vh;background:#fafafa;gap:1rem}.row{display:flex;align-items:center;gap:12px;padding:12px 20px;background:#fff;border-radius:12px;box-shadow:0 2px 12px rgba(0,0,0,.06);min-width:240px}.status{width:10px;height:10px;border-radius:50%;flex-shrink:0}.status--live{background:#22c55e;box-shadow:0 0 0 3px rgba(34,197,94,.25);animation:live 2s ease-in-out infinite}.status--busy{background:#f59e0b}.status--away{background:#94a3b8}.status--offline{background:#e2e8f0}@keyframes live{0%,100%{box-shadow:0 0 0 3px rgba(34,197,94,.25)}50%{box-shadow:0 0 0 6px rgba(34,197,94,.1)}}.row span{font-size:.9rem;font-weight:500;color:#334155}`,
    body: `<div style="display:flex;flex-direction:column;gap:10px">${[['live','Online — Available'],['busy','In a meeting'],['away','Away'],['offline','Offline']].map(([s,t])=>`<div class="row"><div class="status status--${s}"></div><span>${t}</span></div>`).join('')}</div>` },

  // ── Fullscreen hamburger menus ──
  navMenu('menu-fullscreen-split-reveal', 'Split Reveal Menu', ['menu', 'hamburger', 'fullscreen', 'split']),
  navMenu('menu-fullscreen-curtain', 'Curtain Drop Menu', ['menu', 'hamburger', 'curtain']),
  navMenu('menu-fullscreen-stagger-lines', 'Stagger Lines Menu', ['menu', 'hamburger', 'stagger']),
  navMenu('menu-fullscreen-blur-glass', 'Blur Glass Menu', ['menu', 'hamburger', 'blur', 'glass']),
  navMenu('menu-fullscreen-circle-expand', 'Circle Expand Menu', ['menu', 'hamburger', 'circle']),

  // ── Interactive mouse hero landings ──
  { slug: 'hero-mouse-repel-particles', title: 'Mouse Repel Particle Hero', category: 'heroes', tags: ['heroes', 'mouse', 'particles', 'interactive'],
    style: `body{margin:0;min-height:100vh;background:#050508;color:#fff;overflow:hidden;position:relative}canvas{position:absolute;inset:0}main{position:relative;z-index:1;min-height:100vh;display:grid;place-items:center;text-align:center;padding:2rem}h1{font-size:clamp(2.5rem,7vw,4.5rem);font-weight:900;max-width:14ch;line-height:1.05;margin-bottom:1rem}p{color:#888;max-width:40ch;margin:0 auto 2rem;font-size:1.05rem}.cta{padding:14px 32px;border:none;border-radius:99px;background:#6c8cff;color:#fff;font-weight:600;font-size:.95rem}`,
    body: `<canvas id="c"></canvas><main><h1>Push the field</h1><p>Move your cursor — particles scatter away from your presence.</p><button class="cta">Explore</button></main>`,
    script: `const c=document.getElementById('c'),x=c.getContext('2d');let pts=[],mx=-999,my=-999;function r(){c.width=innerWidth;c.height=innerHeight;pts=Array.from({length:90},()=>({x:Math.random()*c.width,y:Math.random()*c.height,vx:0,vy:0,r:Math.random()*2+1}));}r();addEventListener('resize',r);addEventListener('mousemove',e=>{mx=e.clientX;my=e.clientY;});function d(){x.clearRect(0,0,c.width,c.height);pts.forEach(p=>{const dx=p.x-mx,dy=p.y-my,d=Math.hypot(dx,dy);if(d<140&&d>0){const f=(140-d)/140;p.vx+=dx/d*f*3;p.vy+=dy/d*f*3;}p.vx*=.92;p.vy*=.92;p.x+=p.vx;p.y+=p.vy;if(p.x<0)p.x=c.width;if(p.x>c.width)p.x=0;if(p.y<0)p.y=c.height;if(p.y>c.height)p.y=0;x.fillStyle='rgba(108,140,255,.7)';x.beginPath();x.arc(p.x,p.y,p.r,0,Math.PI*2);x.fill();});requestAnimationFrame(d);}d();` },

  { slug: 'hero-mouse-gradient-follow', title: 'Mouse Gradient Hero', category: 'heroes', tags: ['heroes', 'mouse', 'gradient', 'interactive'],
    style: `body{margin:0;min-height:100vh;background:#0a0a0c;color:#fff;overflow:hidden;position:relative}.glow{position:absolute;width:600px;height:600px;border-radius:50%;background:radial-gradient(circle,rgba(108,140,255,.35),transparent 70%);pointer-events:none;transform:translate(-50%,-50%);transition:opacity .3s}main{position:relative;z-index:1;min-height:100vh;display:grid;place-items:center;text-align:center;padding:2rem}h1{font-size:clamp(2.2rem,6vw,4rem);font-weight:800}p{color:#666;margin-top:1rem}`,
    body: `<div class="glow" id="g"></div><main><h1>Light follows you</h1><p>Cursor-driven ambient gradient</p></main>`,
    script: `const g=document.getElementById('g');addEventListener('mousemove',e=>{g.style.left=e.clientX+'px';g.style.top=e.clientY+'px';});` },

  { slug: 'hero-mouse-text-magnetic', title: 'Magnetic Text Hero', category: 'heroes', tags: ['heroes', 'mouse', 'text', 'magnetic'],
    style: `body{margin:0;min-height:100vh;background:#000;color:#fff;display:grid;place-items:center;overflow:hidden}h1{font-size:clamp(3rem,10vw,7rem);font-weight:900;display:flex;gap:.05em;cursor:default}.ch{display:inline-block;transition:transform .15s ease-out}`,
    body: `<h1 id="h">${'MAGNETIC'.split('').map(c=>`<span class="ch">${c}</span>`).join('')}</h1>`,
    script: `const h=document.getElementById('h');h.onmousemove=e=>{const r=h.getBoundingClientRect();[...h.children].forEach(ch=>{const cr=ch.getBoundingClientRect();const x=(e.clientX-(cr.left+cr.width/2))*.15;const y=(e.clientY-(cr.top+cr.height/2))*.15;ch.style.transform='translate('+x+'px,'+y+'px)';});};h.onmouseleave=()=>[...h.children].forEach(ch=>ch.style.transform='');` },

  { slug: 'hero-mouse-parallax-layers', title: 'Mouse Parallax Hero', category: 'heroes', tags: ['heroes', 'mouse', 'parallax', 'layers'],
    style: `body{margin:0;min-height:100vh;background:#0d0d0f;color:#fff;overflow:hidden;position:relative}.layer{position:absolute;inset:0;display:grid;place-items:center;will-change:transform}.layer img{width:110%;height:110%;object-fit:cover;opacity:.35}.layer--fg{z-index:2;text-align:center;padding:2rem}h1{font-size:clamp(2.5rem,6vw,4rem);font-weight:900;text-shadow:0 4px 30px rgba(0,0,0,.8)}`,
    body: `<div class="layer layer--bg" id="bg"><img src="${IMG}" alt=""></div><div class="layer layer--mid" id="mid"><img src="${IMG}" alt="" style="opacity:.2;filter:blur(2px)"></div><div class="layer layer--fg"><h1>Depth in motion</h1></div>`,
    script: `const bg=document.getElementById('bg'),mid=document.getElementById('mid');addEventListener('mousemove',e=>{const x=(e.clientX/innerWidth-.5)*2,y=(e.clientY/innerHeight-.5)*2;bg.style.transform='translate('+x*12+'px,'+y*12+'px)';mid.style.transform='translate('+x*24+'px,'+y*24+'px)';});` },

  { slug: 'hero-mouse-spotlight', title: 'Spotlight Text Hero', category: 'heroes', tags: ['heroes', 'mouse', 'spotlight', 'text'],
    style: `body{margin:0;min-height:100vh;background:#000;color:#fff;overflow:hidden;cursor:none}h1{font-size:clamp(3rem,9vw,6rem);font-weight:900;text-align:center;position:absolute;inset:0;display:grid;place-items:center;background:linear-gradient(#fff,#fff);-webkit-background-clip:text;background-clip:text;color:transparent}.spot{position:fixed;width:280px;height:280px;border-radius:50%;background:radial-gradient(circle,#fff 0%,transparent 70%);pointer-events:none;transform:translate(-50%,-50%);mix-blend-mode:overlay}`,
    body: `<h1>REVEAL</h1><div class="spot" id="s"></div>`,
    script: `const s=document.getElementById('s');addEventListener('mousemove',e=>{s.style.left=e.clientX+'px';s.style.top=e.clientY+'px';});` },

  { slug: 'hero-mouse-wave-letters', title: 'Wave Letter Hero', category: 'heroes', tags: ['heroes', 'mouse', 'text', 'wave'],
    style: `body{margin:0;min-height:100vh;background:linear-gradient(180deg,#0d0d0f,#1a1a2e);color:#fff;display:grid;place-items:center}h1{font-size:clamp(2.5rem,7vw,5rem);font-weight:800;display:flex;gap:2px}.ch{display:inline-block;transition:transform .2s cubic-bezier(.22,.61,.36,1)}`,
    body: `<h1 id="h">${'CURSOR'.split('').map(c=>`<span class="ch">${c}</span>`).join('')}</h1>`,
    script: `const h=document.getElementById('h'),chs=[...h.children];h.onmousemove=e=>{const r=h.getBoundingClientRect();chs.forEach((ch,i)=>{const cr=ch.getBoundingClientRect();const dist=Math.hypot(e.clientX-(cr.left+cr.width/2),e.clientY-(cr.top+cr.height/2));const lift=Math.max(0,120-dist)/120;ch.style.transform='translateY('+(-lift*20)+'px)';});};h.onmouseleave=()=>chs.forEach(ch=>ch.style.transform='');` },

  { slug: 'hero-mouse-video-push', title: 'Video Particle Push Hero', category: 'heroes', tags: ['heroes', 'mouse', 'video', 'particles'],
    style: `body{margin:0;min-height:100vh;overflow:hidden;position:relative;color:#fff}video{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;filter:brightness(.5)}canvas{position:absolute;inset:0;z-index:1}main{position:relative;z-index:2;min-height:100vh;display:grid;place-items:center;text-align:center;padding:2rem}h1{font-size:clamp(2rem,5vw,3.5rem);font-weight:800;text-shadow:0 2px 20px rgba(0,0,0,.8)}`,
    body: `<video src="${VID}" autoplay muted loop playsinline></video><canvas id="c"></canvas><main><h1>Disrupt the field</h1></main>`,
    script: `const c=document.getElementById('c'),x=c.getContext('2d');let pts=[],mx=0,my=0;function r(){c.width=innerWidth;c.height=innerHeight;pts=Array.from({length:70},()=>({x:Math.random()*c.width,y:Math.random()*c.height,vx:(Math.random()-.5)*.3,vy:(Math.random()-.5)*.3}));}r();addEventListener('resize',r);addEventListener('mousemove',e=>{mx=e.clientX;my=e.clientY;});function d(){x.clearRect(0,0,c.width,c.height);pts.forEach(p=>{p.x+=p.vx;p.y+=p.vy;const dx=p.x-mx,dy=p.y-my,d=Math.hypot(dx,dy);if(d<100){p.vx+=dx/d*2;p.vy+=dy/d*2;}p.vx*=.95;p.vy*=.95;if(p.x<0||p.x>c.width)p.vx*=-1;if(p.y<0||p.y>c.height)p.vy*=-1;x.fillStyle='rgba(255,255,255,.6)';x.beginPath();x.arc(p.x,p.y,2,0,Math.PI*2);x.fill();});requestAnimationFrame(d);}d();` },

  { slug: 'hero-mouse-cta-glow', title: 'Mouse Glow CTA Hero', category: 'heroes', tags: ['heroes', 'mouse', 'cta', 'glow'],
    style: `body{margin:0;min-height:100vh;background:#0a0a0c;color:#fff;display:grid;place-items:center;text-align:center;padding:2rem;position:relative;overflow:hidden}.bg{position:absolute;inset:0;background:radial-gradient(circle at var(--x,50%) var(--y,50%),rgba(108,140,255,.2),transparent 50%)}main{position:relative;z-index:1}h1{font-size:clamp(2.2rem,5vw,3.5rem);font-weight:800;margin-bottom:1rem}p{color:#888;margin-bottom:2rem}.btn{position:relative;padding:16px 40px;border:none;border-radius:99px;background:#6c8cff;color:#fff;font-weight:700;font-size:1rem;overflow:hidden}.btn::before{content:'';position:absolute;inset:0;background:radial-gradient(circle at var(--bx,50%) var(--by,50%),rgba(255,255,255,.3),transparent 60%);opacity:0;transition:opacity .2s}.btn:hover::before{opacity:1}`,
    body: `<div class="bg" id="bg"></div><main><h1>Start building</h1><p>Interactive glow follows your cursor across the hero.</p><button class="btn" id="btn">Get started</button></main>`,
    script: `const bg=document.getElementById('bg'),btn=document.getElementById('btn');addEventListener('mousemove',e=>{bg.style.setProperty('--x',e.clientX/innerWidth*100+'%');bg.style.setProperty('--y',e.clientY/innerHeight*100+'%');const r=btn.getBoundingClientRect();btn.style.setProperty('--bx',(e.clientX-r.left)/r.width*100+'%');btn.style.setProperty('--by',(e.clientY-r.top)/r.height*100+'%');});` },

  // ── Experimental mouse effects ──
  { slug: 'experimental-mouse-fluid-trail', title: 'Fluid Mouse Trail', category: 'experimental', tags: ['experimental', 'mouse', 'trail', 'fluid'],
    style: `body{margin:0;min-height:100vh;background:#000;overflow:hidden;cursor:none}canvas{display:block}`,
    body: `<canvas id="c"></canvas>`,
    script: `const c=document.getElementById('c'),x=c.getContext('2d');let pts=[];function r(){c.width=innerWidth;c.height=innerHeight;}r();addEventListener('resize',r);addEventListener('mousemove',e=>pts.push({x:e.clientX,y:e.clientY,t:Date.now()}));function d(){x.fillStyle='rgba(0,0,0,.08)';x.fillRect(0,0,c.width,c.height);const now=Date.now();pts=pts.filter(p=>now-p.t<800);if(pts.length>1){x.strokeStyle='#6c8cff';x.lineWidth=3;x.lineCap='round';x.beginPath();pts.forEach((p,i)=>{if(i===0)x.moveTo(p.x,p.y);else x.lineTo(p.x,p.y);});x.stroke();}requestAnimationFrame(d);}d();` },

  { slug: 'experimental-mouse-ripple', title: 'Mouse Ripple Canvas', category: 'experimental', tags: ['experimental', 'mouse', 'ripple'],
    style: `body{margin:0;min-height:100vh;background:#0d0d0f;overflow:hidden}canvas{display:block}`,
    body: `<canvas id="c"></canvas>`,
    script: `const c=document.getElementById('c'),x=c.getContext('2d');let ripples=[];function r(){c.width=innerWidth;c.height=innerHeight;}r();addEventListener('resize',r);addEventListener('mousemove',e=>{if(Math.random()>.7)ripples.push({x:e.clientX,y:e.clientY,r:0,a:1});});function d(){x.fillStyle='rgba(13,13,15,.15)';x.fillRect(0,0,c.width,c.height);ripples=ripples.filter(rp=>rp.a>.01);ripples.forEach(rp=>{rp.r+=2;rp.a-=.015;x.strokeStyle='rgba(108,140,255,'+rp.a+')';x.lineWidth=2;x.beginPath();x.arc(rp.x,rp.y,rp.r,0,Math.PI*2);x.stroke();});requestAnimationFrame(d);}d();` },

  { slug: 'experimental-mouse-gravity-orbs', title: 'Gravity Orbs Mouse', category: 'experimental', tags: ['experimental', 'mouse', 'gravity', 'orbs'],
    style: `body{margin:0;min-height:100vh;background:#050508;overflow:hidden}canvas{display:block}`,
    body: `<canvas id="c"></canvas>`,
    script: `const c=document.getElementById('c'),x=c.getContext('2d');let orbs=[],mx=0,my=0;function r(){c.width=innerWidth;c.height=innerHeight;orbs=Array.from({length:20},()=>({x:Math.random()*c.width,y:Math.random()*c.height,vx:0,vy:0,r:8+Math.random()*16,hue:200+Math.random()*80}));}r();addEventListener('resize',r);addEventListener('mousemove',e=>{mx=e.clientX;my=e.clientY;});function d(){x.fillStyle='rgba(5,5,8,.2)';x.fillRect(0,0,c.width,c.height);orbs.forEach(o=>{const dx=mx-o.x,dy=my-o.y,d=Math.hypot(dx,dy);if(d<200){o.vx+=dx/d*.8;o.vy+=dy/d*.8;}o.vx*=.94;o.vy*=.94;o.x+=o.vx;o.y+=o.vy;o.x=Math.max(o.r,Math.min(c.width-o.r,o.x));o.y=Math.max(o.r,Math.min(c.height-o.r,o.y));x.fillStyle='hsla('+o.hue+',80%,65%,.8)';x.beginPath();x.arc(o.x,o.y,o.r,0,Math.PI*2);x.fill();});requestAnimationFrame(d);}d();` },

  { slug: 'experimental-mouse-text-scatter', title: 'Scatter Text on Mouse', category: 'experimental', tags: ['experimental', 'mouse', 'text', 'scatter'],
    style: `body{margin:0;min-height:100vh;background:#111;color:#fff;display:grid;place-items:center}h1{font-size:clamp(2rem,6vw,4rem);font-weight:900;display:flex;flex-wrap:wrap;justify-content:center;gap:.1em;max-width:90vw}.w{display:inline-block;transition:transform .35s cubic-bezier(.22,.61,.36,1)}`,
    body: `<h1 id="h">${'MOVE YOUR MOUSE'.split(' ').map(w=>'<span class="w">'+w+'</span>').join(' ')}</h1>`,
    script: `const words=[...document.querySelectorAll('.w')];addEventListener('mousemove',e=>{words.forEach(w=>{const r=w.getBoundingClientRect();const dx=e.clientX-(r.left+r.width/2);const dy=e.clientY-(r.top+r.height/2);const d=Math.hypot(dx,dy);const push=Math.max(0,150-d)/150;w.style.transform='translate('+(dx/d*push*30||0)+'px,'+(dy/d*push*30||0)+'px)';});});` },

  { slug: 'experimental-mouse-lens', title: 'Lens Distort Mouse', category: 'experimental', tags: ['experimental', 'mouse', 'lens', 'distort'],
    style: `body{margin:0;min-height:100vh;overflow:hidden;position:relative}img{width:100%;height:100vh;object-fit:cover;display:block}.lens{position:fixed;width:180px;height:180px;border-radius:50%;border:3px solid rgba(255,255,255,.5);pointer-events:none;transform:translate(-50%,-50%);overflow:hidden;box-shadow:0 0 40px rgba(0,0,0,.5)}.lens img{position:absolute;width:100vw;height:100vh;object-fit:cover;max-width:none}`,
    body: `<img src="${IMG}" alt="" id="bg"><div class="lens" id="l"><img src="${IMG}" alt="" id="li"></div>`,
    script: `const l=document.getElementById('l'),li=document.getElementById('li');addEventListener('mousemove',e=>{l.style.left=e.clientX+'px';l.style.top=e.clientY+'px';li.style.left=-e.clientX+90+'px';li.style.top=-e.clientY+90+'px';li.style.width=innerWidth+'px';li.style.height=innerHeight+'px';});` },

  { slug: 'experimental-mouse-blob-follow', title: 'Blob Follow Cursor', category: 'experimental', tags: ['experimental', 'mouse', 'blob'],
    style: `body{margin:0;min-height:100vh;background:#fafafa;display:grid;place-items:center;overflow:hidden}.blob{position:fixed;width:120px;height:120px;border-radius:50%;background:linear-gradient(135deg,#6c8cff,#ff6cb0);filter:blur(2px);pointer-events:none;transform:translate(-50%,-50%);transition:width .3s,height .3s}h1{font-size:2.5rem;font-weight:800;color:#111;position:relative;z-index:1}`,
    body: `<div class="blob" id="b"></div><h1>Organic motion</h1>`,
    script: `const b=document.getElementById('b');let x=0,y=0,cx=0,cy=0;addEventListener('mousemove',e=>{x=e.clientX;y=e.clientY;});function tick(){cx+=(x-cx)*.12;cy+=(y-cy)*.12;b.style.left=cx+'px';b.style.top=cy+'px';requestAnimationFrame(tick);}tick();` },
];
