const M = require('../lib/media');
const { getPalette } = require('../lib/palettes');

function p(i) { return getPalette(i); }

function center(body, extra = '') {
  return `body{display:grid;place-items:center;min-height:100vh;${extra}}`;
}

const buttons = [
  { slug: 'glow-outline-button', title: 'Glow Outline Button', tags: ['glow', 'outline'],
    build: () => ({ style: `${center('', 'background:#0d0d0f')} .btn{padding:14px 36px;border:2px solid #6c8cff;border-radius:99px;background:transparent;color:#6c8cff;font-weight:600;box-shadow:0 0 20px rgba(108,140,255,.3);transition:box-shadow .3s,background .3s} .btn:hover{background:#6c8cff;color:#fff;box-shadow:0 0 40px rgba(108,140,255,.6)}`, body: `<button class="btn">Get Started</button>` }) },
  { slug: 'gradient-fill-button', title: 'Gradient Fill Button', tags: ['gradient'],
    build: () => ({ style: `@property --angle{syntax:'<angle>';initial-value:0deg;inherits:false} ${center('', 'background:radial-gradient(ellipse 60% 50% at 50% 45%,#1a1b22,#0a0a0c 70%)')} .btn{position:relative;isolation:isolate;padding:18px 46px;border:none;border-radius:14px;background:linear-gradient(135deg,#6c8cff,#b06cff 45%,#ff6cb0);background-size:200% 200%;color:#fff;font-weight:700;font-size:1rem;letter-spacing:.02em;cursor:pointer;overflow:hidden;animation:drift 6s ease infinite;box-shadow:0 8px 24px rgba(108,140,255,.35),0 2px 6px rgba(0,0,0,.3);transition:transform .25s cubic-bezier(.22,1,.36,1),box-shadow .25s ease} .btn::before{content:'';position:absolute;inset:-2px;z-index:-2;border-radius:inherit;background:conic-gradient(from var(--angle),#6c8cff,#ff6cb0,#ffd16c,#6cffb8,#6c8cff);filter:blur(7px);opacity:0;transition:opacity .35s ease;animation:spin 4s linear infinite} .btn::after{content:'';position:absolute;inset:0;z-index:-1;border-radius:inherit;background:linear-gradient(115deg,transparent 20%,rgba(255,255,255,.45) 48%,transparent 60%);background-size:250% 100%;background-position:150% 0;transition:background-position .7s ease} .btn:hover{transform:translateY(-3px) scale(1.02);box-shadow:0 14px 40px rgba(176,108,255,.5),0 4px 10px rgba(0,0,0,.35)} .btn:hover::before{opacity:1} .btn:hover::after{background-position:-80% 0} .btn:active{transform:translateY(-1px) scale(.99)} .btn__label{position:relative;display:inline-flex;align-items:center;gap:.55rem} .btn__arrow{transition:transform .3s cubic-bezier(.22,1,.36,1)} .btn:hover .btn__arrow{transform:translateX(4px)} @keyframes drift{0%,100%{background-position:0% 50%}50%{background-position:100% 50%}} @keyframes spin{to{--angle:360deg}} @media(prefers-reduced-motion:reduce){.btn,.btn::before{animation:none}}`, body: `<button class="btn" type="button"><span class="btn__label">Explore<svg class="btn__arrow" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M5 12h14M13 6l6 6-6 6"/></svg></span></button>` }) },
  { slug: 'icon-arrow-button', title: 'Icon Arrow Button', tags: ['icon'],
    build: () => ({ style: `${center('', 'background:#fafafa')} .btn{display:inline-flex;align-items:center;gap:10px;padding:12px 28px;border:none;border-radius:8px;background:#111;color:#fff;font-weight:600;cursor:pointer} .btn span{transition:transform .2s} .btn:hover span{transform:translateX(4px)}`, body: `<button class="btn">Continue <span>→</span></button>` }) },
  { slug: 'loading-button', title: 'Loading Button', tags: ['loading'],
    build: () => ({ style: `${center('', 'background:#0d0d0f')} .btn{padding:14px 32px;border:none;border-radius:8px;background:#6c8cff;color:#fff;font-weight:600;cursor:pointer;min-width:140px} .btn.loading{opacity:.8;pointer-events:none} .spin{display:inline-block;width:16px;height:16px;border:2px solid rgba(255,255,255,.3);border-top-color:#fff;border-radius:50%;animation:sp .6s linear infinite;vertical-align:middle} @keyframes sp{to{transform:rotate(360deg)}}`, body: `<button class="btn" id="b">Submit</button>`, script: `document.getElementById('b').onclick=function(){this.classList.add('loading');this.innerHTML='<span class="spin"></span>';setTimeout(()=>{this.classList.remove('loading');this.textContent='Done!'},2000)};` }) },
  { slug: 'press-3d-button', title: '3D Press Button', tags: ['3d'],
    build: () => ({ style: `${center('', 'background:#1a1a2e')} .btn{padding:16px 36px;border:none;border-radius:10px;background:#6c8cff;color:#fff;font-weight:700;box-shadow:0 6px 0 #3a5ccc;transform:translateY(0);transition:transform .1s,box-shadow .1s;cursor:pointer} .btn:active{transform:translateY(4px);box-shadow:0 2px 0 #3a5ccc}`, body: `<button class="btn">Press Me</button>` }) },
];

const tabs = [
  { slug: 'vertical-tabs', title: 'Vertical Tabs', tags: ['vertical'],
    build: () => ({ style: `body{display:flex;min-height:100vh;background:#f5f5f5;margin:0} .tabs{display:flex;flex-direction:column;width:180px;background:#fff;border-right:1px solid #eee;padding:1rem 0} .tab{padding:12px 24px;border:none;background:none;text-align:left;cursor:pointer;color:#666;font-size:.95rem;border-left:3px solid transparent} .tab.active{color:#111;font-weight:600;border-color:#6c8cff;background:#f8f9ff} .panel{flex:1;padding:3rem;font-size:1.2rem;color:#333}`, body: `<div class="tabs">${['Overview','Analytics','Settings'].map((t,i)=>`<button class="tab${i===0?' active':''}" data-t="${t}">${t}</button>`).join('')}</div><div class="panel" id="p">Overview content</div>`, script: `document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');document.getElementById('p').textContent=t.dataset.t+' content';});` }) },
  { slug: 'pill-tabs', title: 'Pill Tabs', tags: ['pill'],
    build: () => ({ style: `${center('', 'background:#0d0d0f')} .tabs{display:flex;gap:4px;background:#1a1a2e;padding:4px;border-radius:12px} .tab{padding:10px 20px;border:none;background:transparent;color:#888;border-radius:8px;cursor:pointer;font-size:.9rem} .tab.active{background:#6c8cff;color:#fff}`, body: `<div class="tabs">${['Day','Week','Month'].map((t,i)=>`<button class="tab${i===0?' active':''}">${t}</button>`).join('')}</div>`, script: `document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');});` }) },
  { slug: 'card-tabs', title: 'Card Tabs', tags: ['card'],
    build: () => ({ style: `${center('', 'background:#eee;padding:2rem')} .wrap{background:#fff;border-radius:16px;padding:2rem;max-width:400px;box-shadow:0 4px 24px rgba(0,0,0,.08)} .tabs{display:flex;gap:8px;margin-bottom:1.5rem} .tab{flex:1;padding:10px;border:1px solid #ddd;border-radius:8px;background:#fafafa;cursor:pointer;text-align:center;font-size:.85rem} .tab.active{border-color:#6c8cff;background:#f0f4ff;color:#3a5ccc;font-weight:600}`, body: `<div class="wrap"><div class="tabs"><button class="tab active">Free</button><button class="tab">Pro</button></div><p>Plan details here</p></div>`, script: `document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');});` }) },
  { slug: 'underline-tabs-v2', title: 'Underline Tabs V2', tags: ['underline'],
    build: () => ({ style: `${center('', 'background:#fafafa')} .tabs{display:flex;position:relative;border-bottom:2px solid #eee} .tab{padding:1rem 1.5rem;border:none;background:none;color:#888;cursor:pointer;font-size:1rem} .tab.active{color:#111;font-weight:600} .ind{position:absolute;bottom:-2px;height:2px;background:#6c8cff;transition:left .3s,width .3s}`, body: `<div class="tabs" id="tabs">${['Home','Products','About'].map((t,i)=>`<button class="tab${i===0?' active':''}">${t}</button>`).join('')}<div class="ind" id="ind"></div></div>`, script: `const tabs=document.querySelectorAll('.tab'),ind=document.getElementById('ind');function m(t){const r=t.getBoundingClientRect(),p=t.parentElement.getBoundingClientRect();ind.style.left=(r.left-p.left)+'px';ind.style.width=r.width+'px';}m(tabs[0]);tabs.forEach(t=>t.onclick=()=>{tabs.forEach(x=>x.classList.remove('active'));t.classList.add('active');m(t);});` }) },
];

const dropdowns = [
  { slug: 'basic-dropdown', title: 'Basic Dropdown', tags: ['menu'],
    build: () => ({ style: `${center('', 'background:#f5f5f5')} .dd{position:relative} .btn{padding:10px 20px;border:1px solid #ddd;border-radius:8px;background:#fff;cursor:pointer} .menu{position:absolute;top:calc(100% + 4px);left:0;min-width:160px;background:#fff;border:1px solid #eee;border-radius:8px;box-shadow:0 8px 24px rgba(0,0,0,.1);display:none;overflow:hidden} .menu.open{display:block} .menu a{display:block;padding:10px 16px;color:#333;text-decoration:none;font-size:.9rem} .menu a:hover{background:#f5f5f5}`, body: `<div class="dd"><button class="btn" id="b">Options ▾</button><div class="menu" id="m"><a href="#">Edit</a><a href="#">Duplicate</a><a href="#">Delete</a></div></div>`, script: `const b=document.getElementById('b'),m=document.getElementById('m');b.onclick=e=>{e.stopPropagation();m.classList.toggle('open');};document.onclick=()=>m.classList.remove('open');` }) },
  { slug: 'mega-menu-dropdown', title: 'Mega Menu', tags: ['mega'],
    build: () => ({ style: `body{margin:0;background:#fafafa} nav{display:flex;gap:2rem;padding:1rem 2rem;background:#fff;border-bottom:1px solid #eee;position:relative} nav a{color:#333;text-decoration:none;font-size:.9rem} .mega{position:absolute;top:100%;left:0;right:0;background:#fff;border-bottom:1px solid #eee;padding:2rem;display:none;grid-template-columns:repeat(3,1fr);gap:2rem;box-shadow:0 8px 24px rgba(0,0,0,.06)} .mega.open{display:grid} .mega h4{font-size:.8rem;text-transform:uppercase;color:#888;margin-bottom:.8rem} .mega a{display:block;padding:4px 0;color:#333;text-decoration:none;font-size:.9rem}`, body: `<nav><a href="#">Home</a><a href="#" id="p">Products</a><a href="#">About</a><div class="mega" id="mega"><div><h4>Features</h4><a href="#">Analytics</a><a href="#">Automation</a></div><div><h4>Tools</h4><a href="#">Editor</a><a href="#">API</a></div><div><h4>Support</h4><a href="#">Docs</a><a href="#">Contact</a></div></div></nav>`, script: `document.getElementById('p').onclick=e=>{e.preventDefault();document.getElementById('mega').classList.toggle('open');};` }) },
  { slug: 'nested-submenu', title: 'Nested Submenu', tags: ['nested'],
    build: () => ({ style: `${center('', 'background:#0d0d0f')} .menu{background:#1a1a2e;border-radius:8px;padding:8px 0;min-width:180px} .item{padding:10px 16px;color:#ccc;font-size:.9rem;cursor:pointer;position:relative} .item:hover{background:#2a2a40;color:#fff} .sub{position:absolute;left:100%;top:0;background:#1a1a2e;border-radius:8px;padding:8px 0;min-width:140px;display:none} .item:hover .sub{display:block}`, body: `<div class="menu"><div class="item">File</div><div class="item">Edit<div class="sub"><div class="item">Cut</div><div class="item">Copy</div><div class="item">Paste</div></div></div><div class="item">View</div></div>` }) },
  { slug: 'animated-chevron-dropdown', title: 'Animated Chevron Dropdown', tags: ['chevron'],
    build: () => ({ style: `${center('', 'background:#fafafa')} .acc{max-width:360px;width:100%;border:1px solid #eee;border-radius:12px;overflow:hidden} .head{padding:1rem 1.25rem;display:flex;justify-content:space-between;align-items:center;cursor:pointer;background:#fff;font-weight:600} .head .ch{transition:transform .3s} .head.open .ch{transform:rotate(180deg)} .body{max-height:0;overflow:hidden;transition:max-height .3s;background:#fafafa} .body.open{max-height:120px} .body p{padding:1rem 1.25rem;color:#666;font-size:.9rem}`, body: `<div class="acc"><div class="head" id="h">Account Settings <span class="ch">▾</span></div><div class="body" id="b"><p>Manage your profile, password, and notifications.</p></div></div>`, script: `const h=document.getElementById('h'),b=document.getElementById('b');h.onclick=()=>{h.classList.toggle('open');b.classList.toggle('open');};` }) },
];

function withCategory(items, category) {
  return items.map((r) => ({ ...r, category }));
}

module.exports = [
  ...withCategory(buttons, 'buttons'),
  ...withCategory(tabs, 'tabs'),
  ...withCategory(dropdowns, 'dropdowns'),
];
